// Golden Threads — curated thematic verse chains through the whole Bible.
// Each thread is an ordered chain: every stop carries a one-line link note
// explaining how it advances the theme. Refs use Rhema book keys (MSB).
// Curation follows a literal, grammatical-historical reading; the salvation
// threads reflect free grace theology (salvation as a free gift through faith
// alone, distinct from costly discipleship and rewards).
window.BibleThreads = {
  version: 1,
  categories: [
    { id: 'heart',    icon: '💛', title: "God's Heart",        blurb: 'Who God is — His love, grace, and character.' },
    { id: 'gift',     icon: '🎁', title: 'The Free Gift',      blurb: 'Salvation: free, by faith, forever.' },
    { id: 'walk',     icon: '👣', title: 'Walking With God',   blurb: 'Discipleship, growth, and rewards.' },
    { id: 'jesus',    icon: '✝️', title: 'Jesus',              blurb: 'His person, His work, His return.' },
    { id: 'promises', icon: '⚓', title: 'Promises to Stand On', blurb: 'Peace, courage, provision, comfort.' },
    { id: 'wisdom',   icon: '🦉', title: 'Wisdom for Life',    blurb: 'Everyday life, examined by Scripture.' },
    { id: 'story',    icon: '📜', title: 'The Big Story',      blurb: 'Covenants, Israel, the Church, the Kingdom.' }
  ],
  topics: [

  // ═══ GOD'S HEART ═══
  { id: 'love-of-god', cat: 'heart', icon: '❤️', title: 'The Love of God',
    tagline: 'From everlasting love to a cross on a hill.',
    intro: 'God’s love is not a mood — it is His settled, everlasting disposition toward you, proven in history at the cross.',
    verses: [
      { r: 'DEU 7:7', n: 'God’s love begins in God, not in anything attractive about us.' },
      { r: 'PSA 103:8', n: 'Compassionate, gracious, slow to anger — His own self-description.' },
      { r: 'PSA 103:11', n: 'His loving devotion is measured in sky-heights, not inches.' },
      { r: 'ISA 49:15', n: 'More constant than a nursing mother — He cannot forget you.' },
      { r: 'JER 31:3', n: '"I have loved you with an everlasting love" — no start date, no expiry.' },
      { r: 'ZEP 3:17', n: 'He rejoices over His people with singing.' },
      { r: 'JOH 3:16', n: 'The love becomes a gift: His one and only Son, for the world.' },
      { r: 'ROM 5:8', n: 'Proof supplied: Christ died for us while we were still sinners.' },
      { r: 'EPH 2:4', n: '"Because of His great love" — the engine behind your salvation.' },
      { r: '1JO 4:9', n: 'Love was displayed, not merely declared: He sent His Son.' },
      { r: '1JO 4:10', n: 'Real love defined: not that we loved God, but that He loved us.' },
      { r: '1JO 4:19', n: 'The thread’s end becomes your beginning: we love because He first loved.' }
    ] },

  { id: 'grace-of-god', cat: 'heart', icon: '🕊️', title: 'The Grace of God',
    tagline: 'Favor you did not earn and cannot repay.',
    intro: 'Grace is God giving what we could never deserve. Trace it from Noah’s day to the throne you may now approach boldly.',
    verses: [
      { r: 'GEN 6:8', n: 'The Bible’s first "grace": Noah found favor — before he built anything.' },
      { r: 'EXO 34:6', n: 'God proclaims His own name: compassionate and gracious.' },
      { r: 'PSA 86:15', n: 'David banks his prayer on that same self-revelation.' },
      { r: 'PRO 3:34', n: 'Grace flows downhill — to the humble.' },
      { r: 'JOH 1:14', n: 'Grace gets a face: the Word became flesh, full of grace and truth.' },
      { r: 'JOH 1:16', n: 'From His fullness: grace upon grace — waves of it.' },
      { r: 'JOH 1:17', n: 'Law came through Moses; grace and truth came through Jesus Christ.' },
      { r: 'ROM 5:20', n: 'Where sin increased, grace increased all the more — grace outruns sin.' },
      { r: 'EPH 2:8', n: 'By grace, through faith, not from yourselves — it is God’s gift.' },
      { r: 'TIT 2:11', n: 'Grace has appeared, bringing salvation — then it trains us to live.' },
      { r: 'HEB 4:16', n: 'The destination: a throne OF grace, approached with confidence.' }
    ] },

  { id: 'faithfulness', cat: 'heart', icon: '🌅', title: 'Great Is His Faithfulness',
    tagline: 'New every morning — even in Lamentations.',
    intro: 'The Bible’s boldest claim about God’s reliability sits in its saddest book. He keeps His word even when we cannot keep ours.',
    verses: [
      { r: 'DEU 7:9', n: 'The faithful God keeps covenant to a thousand generations.' },
      { r: 'JOS 21:45', n: 'Audit result: not one of the LORD’s good promises failed.' },
      { r: 'PSA 36:5', n: 'His faithfulness reaches to the clouds.' },
      { r: 'PSA 119:90', n: 'It runs through all generations — as stable as the earth He founded.' },
      { r: 'LAM 3:22', n: 'Sung from the rubble of Jerusalem: His mercies never fail.' },
      { r: 'LAM 3:23', n: 'New every morning — great is Your faithfulness.' },
      { r: 'ISA 25:1', n: 'Plans formed long ago, executed in perfect faithfulness.' },
      { r: '1CO 1:9', n: 'God is faithful — He called you into fellowship with His Son.' },
      { r: '1CO 10:13', n: 'Faithful in your temptation: He provides the way out.' },
      { r: '1TH 5:24', n: 'The One who calls you is faithful, and He will do it.' },
      { r: '2TI 2:13', n: 'Even if we are faithless, He remains faithful — He cannot deny Himself.' },
      { r: 'HEB 10:23', n: 'So hold your hope without wavering: the Promiser is faithful.' }
    ] },

  { id: 'shepherd', cat: 'heart', icon: '🐑', title: 'The Good Shepherd',
    tagline: 'One flock, one Shepherd, no lost sheep.',
    intro: 'From Jacob’s deathbed to the throne of heaven, God insists on being pictured with a staff in His hand.',
    verses: [
      { r: 'GEN 48:15', n: 'Jacob’s testimony: God has been my shepherd all my life long.' },
      { r: 'PSA 23:1', n: 'The LORD is MY shepherd — the psalm every heart memorizes first.' },
      { r: 'ISA 40:11', n: 'He gathers the lambs in His arms and carries them close.' },
      { r: 'EZK 34:11', n: 'When human shepherds fail, God says: I Myself will search for My flock.' },
      { r: 'JOH 10:11', n: 'Jesus claims the title: the good shepherd lays down His life for the sheep.' },
      { r: 'JOH 10:14', n: 'He knows His sheep by name — and they know Him.' },
      { r: 'JOH 10:27', n: 'His sheep hear His voice and follow.' },
      { r: 'JOH 10:28', n: 'And He gives them eternal life; they will never perish. Ever.' },
      { r: 'HEB 13:20', n: 'The great Shepherd, raised from the dead by the God of peace.' },
      { r: '1PE 2:25', n: 'You were straying like sheep — but have returned to the Shepherd of your souls.' },
      { r: '1PE 5:4', n: 'The Chief Shepherd will appear — with unfading crowns for faithful under-shepherds.' },
      { r: 'REV 7:17', n: 'Forever: the Lamb Himself will shepherd them to springs of living water.' }
    ] },

  { id: 'father', cat: 'heart', icon: '🏠', title: 'The Father’s Heart',
    tagline: 'Adopted, embraced, and never disowned.',
    intro: 'Believers are not employees of God — they are children in the family. Trace what it means that God is your Father.',
    verses: [
      { r: 'PSA 103:13', n: 'As a father has compassion on his children — God’s own comparison.' },
      { r: 'ISA 64:8', n: 'You are our Father; we are the clay, You are the potter.' },
      { r: 'MAT 7:11', n: 'If flawed fathers give good gifts, how much more your Father in heaven.' },
      { r: 'LUK 15:20', n: 'The father RUNS to the returning son — compassion outruns confession.' },
      { r: 'JOH 1:12', n: 'How you enter the family: receive Him, believe in His name — become God’s child.' },
      { r: 'ROM 8:15', n: 'Not a spirit of slavery but of adoption: "Abba! Father!"' },
      { r: 'GAL 4:6', n: 'The Spirit of His Son in your heart cries out to the Father.' },
      { r: '2CO 6:18', n: '"I will be a Father to you" — the covenant promise made personal.' },
      { r: 'HEB 12:7', n: 'Discipline is family business: God treats you as sons, not strangers.' },
      { r: '1JO 3:1', n: 'Behold what manner of love: that we should be called children of God. And we are.' },
      { r: 'JAM 1:17', n: 'Every good gift descends from the Father of lights, who does not change.' }
    ] },

  { id: 'holiness', cat: 'heart', icon: '🔥', title: 'Holy, Holy, Holy',
    tagline: 'The only attribute Scripture triples.',
    intro: 'Angels do not cry "love, love, love" or "power, power, power." Holiness is the blazing center of who God is.',
    verses: [
      { r: 'EXO 15:11', n: 'Israel’s first worship song: who is like You — majestic in holiness?' },
      { r: 'LEV 19:2', n: 'The standard set: be holy, because I the LORD your God am holy.' },
      { r: '1SA 2:2', n: 'Hannah’s theology: there is no one holy like the LORD.' },
      { r: 'PSA 99:9', n: 'Exalt the LORD and worship — for the LORD our God is holy.' },
      { r: 'ISA 6:3', n: 'The seraphim’s triple cry — and Isaiah’s undoing.' },
      { r: 'ISA 57:15', n: 'The High and Holy One dwells — with the contrite and lowly.' },
      { r: 'HAB 1:13', n: 'Eyes too pure to look upon evil — the problem the cross will solve.' },
      { r: '1PE 1:15', n: 'The Leviticus call renewed for believers: be holy in all you do.' },
      { r: '1PE 1:16', n: 'Peter quotes it straight: "Be holy, because I am holy."' },
      { r: 'REV 4:8', n: 'Heaven’s throne room still rings with it: holy, holy, holy.' },
      { r: 'REV 15:4', n: 'The end of the story: all nations will worship — for You alone are holy.' }
    ] },

  // ═══ THE FREE GIFT ═══
  { id: 'free-gift', cat: 'gift', icon: '🎁', title: 'Salvation Is a Free Gift',
    tagline: 'Without money, without cost, without strings.',
    intro: 'From Isaiah’s market cry to the Bible’s final invitation, God’s salvation is priced the same way: free. A gift earned is a wage — and salvation is never a wage.',
    verses: [
      { r: 'ISA 55:1', n: 'Come, buy wine and milk — without money and without cost.' },
      { r: 'JOH 4:10', n: 'Jesus calls salvation "the gift of God" — living water for the asking.' },
      { r: 'ROM 3:24', n: 'Justified FREELY by His grace — the word means "without cause in us."' },
      { r: 'ROM 5:15', n: 'The gift is not like the trespass — grace overflows to the many.' },
      { r: 'ROM 6:23', n: 'Wages vs. gift: sin pays death; God gives eternal life in Christ.' },
      { r: 'EPH 2:8', n: 'Grace, through faith, not of yourselves — it is the gift of God.' },
      { r: 'EPH 2:9', n: 'Not of works, so that no one can boast — gifts exclude bragging rights.' },
      { r: 'TIT 3:5', n: 'He saved us — not by righteous deeds we had done, but by His mercy.' },
      { r: 'REV 21:6', n: 'From the throne: to the thirsty I will give freely from the spring of life.' },
      { r: 'REV 22:17', n: 'The Bible’s last invitation: whoever wishes, take the water of life — freely.' }
    ] },

  { id: 'believe', cat: 'gift', icon: '🙌', title: 'Believe and Live',
    tagline: 'One condition, stated about 160 times: faith.',
    intro: 'John wrote his Gospel so that you may believe and have life (John 20:31) — and he never once adds a second condition. Look and live.',
    verses: [
      { r: 'GEN 15:6', n: 'The pattern set early: Abram believed the LORD — credited as righteousness.' },
      { r: 'NUM 21:8', n: 'A serpent on a pole: whoever looks, lives. No climbing, only looking.' },
      { r: 'HAB 2:4', n: 'The verse that echoes through Romans, Galatians, Hebrews: the righteous will live by faith.' },
      { r: 'JOH 3:14', n: 'Jesus claims the serpent picture for His own cross.' },
      { r: 'JOH 3:15', n: '...so that everyone who believes in Him may have eternal life.' },
      { r: 'JOH 5:24', n: 'Hears, believes, HAS eternal life — and will not come into judgment.' },
      { r: 'JOH 6:47', n: 'As plain as Jesus ever said it: he who believes has eternal life.' },
      { r: 'JOH 11:25', n: 'To Martha: I am the resurrection and the life — the one believing will live.' },
      { r: 'JOH 20:31', n: 'John’s stated purpose: written that you may believe, and by believing have life.' },
      { r: 'ACT 16:31', n: 'The jailer’s question answered in one line: believe in the Lord Jesus.' },
      { r: 'ROM 4:5', n: 'To the one who does NOT work but believes — faith is credited as righteousness.' },
      { r: 'GAL 2:16', n: 'By faith in Christ and not by works of the law — stated three times in one verse.' }
    ] },

  { id: 'eternal-security', cat: 'gift', icon: '🔒', title: 'Kept Forever',
    tagline: 'Held in two hands that never let go.',
    intro: 'Eternal life that could be lost was never eternal. This chain stacks the promises: sealed, kept, never cast out, never snatched away.',
    verses: [
      { r: 'JOH 5:24', n: 'Present tense "has," and a settled verdict: passed from death to life.' },
      { r: 'JOH 6:37', n: 'The one who comes to Me I will NEVER cast out — a double negative in Greek.' },
      { r: 'JOH 6:39', n: 'The Father’s will: that Jesus lose NONE of all He has been given.' },
      { r: 'JOH 10:28', n: 'They will never perish; no one can snatch them out of My hand.' },
      { r: 'JOH 10:29', n: 'And the Father’s hand closes over the Son’s — double grip.' },
      { r: 'ROM 8:1', n: 'Therefore: NO condemnation for those in Christ Jesus. None.' },
      { r: 'ROM 8:38', n: 'Paul’s inventory begins: neither death nor life nor angels...' },
      { r: 'ROM 8:39', n: '...nothing in all creation can separate us from the love of God in Christ.' },
      { r: 'EPH 1:13', n: 'Having believed, you were SEALED with the promised Holy Spirit.' },
      { r: 'EPH 4:30', n: 'Sealed for the day of redemption — the seal has an expiration event, not an escape clause.' },
      { r: 'PHP 1:6', n: 'He who began the work will carry it to completion. He finishes what He starts.' },
      { r: '1PE 1:5', n: 'Shielded by God’s power through faith for a salvation ready to be revealed.' },
      { r: 'JUD 1:24', n: 'To Him who is ABLE to keep you from stumbling and present you blameless — with great joy.' }
    ] },

  { id: 'assurance', cat: 'gift', icon: '✅', title: 'How You Can Know',
    tagline: 'Assurance rests on His promise, not your performance.',
    intro: 'God wants His children certain. Assurance is not arrogance — it is taking Jesus at His word. If it depended on your works, you could never know; because it depends on His promise, you can.',
    verses: [
      { r: 'JOH 6:47', n: 'The ground of assurance: Jesus’ own promise, in the present tense.' },
      { r: 'JOH 5:24', n: 'Will not come into judgment; HAS passed from death to life — verdict rendered.' },
      { r: 'JOH 20:31', n: 'Written so you may KNOW the life you have by believing.' },
      { r: 'ROM 8:16', n: 'The Spirit Himself testifies with our spirit: we are God’s children.' },
      { r: '2TI 1:12', n: 'Paul’s certainty: I know WHOM I have believed — persuaded He can guard my deposit.' },
      { r: 'TIT 1:2', n: 'Eternal life promised by the God who cannot lie — your assurance is His honesty.' },
      { r: 'HEB 10:22', n: 'Draw near in FULL assurance of faith — hearts sprinkled clean.' },
      { r: '1JO 5:11', n: 'The testimony: God has given us eternal life, and this life is in His Son.' },
      { r: '1JO 5:12', n: 'The math is binary: whoever has the Son has life.' },
      { r: '1JO 5:13', n: 'Written that you may KNOW — not hope, not guess — that you have eternal life.' }
    ] },

  { id: 'justified', cat: 'gift', icon: '⚖️', title: 'Declared Righteous',
    tagline: 'The courtroom verdict that cannot be appealed.',
    intro: 'Justification is a legal declaration, not a gradual improvement. God credits Christ’s righteousness to the believing sinner — and no one can re-open the case.',
    verses: [
      { r: 'GEN 15:6', n: 'The first credit entry: faith counted as righteousness.' },
      { r: 'PSA 32:1', n: 'Blessed is he whose transgressions are forgiven — David knew the verdict.' },
      { r: 'PSA 32:2', n: 'Blessed is the man whose sin the LORD does NOT count against him.' },
      { r: 'ISA 53:11', n: 'By His knowledge My righteous Servant will justify many.' },
      { r: 'LUK 18:13', n: 'The tax collector’s whole case: "God, be merciful to me, the sinner."' },
      { r: 'LUK 18:14', n: 'Jesus’ ruling: THIS man went home justified — not the religious one.' },
      { r: 'ROM 3:26', n: 'The cross lets God be both just AND the justifier of the one who believes.' },
      { r: 'ROM 3:28', n: 'Conclusion: a man is justified by faith apart from works of the law.' },
      { r: 'ROM 5:1', n: 'Therefore, having been justified by faith, we have peace with God.' },
      { r: 'ROM 8:33', n: 'Who will bring a charge against God’s elect? It is God who justifies.' },
      { r: '2CO 5:21', n: 'The great exchange: He became sin for us; we become God’s righteousness in Him.' },
      { r: 'PHP 3:9', n: 'Paul trades his resume for a righteousness from God on the basis of faith.' }
    ] },

  { id: 'new-birth', cat: 'gift', icon: '🌱', title: 'Born Again',
    tagline: 'You cannot be unborn.',
    intro: 'Birth happens once and establishes a permanent relationship. That is exactly the picture Jesus chose for how eternal life begins.',
    verses: [
      { r: 'EZK 36:26', n: 'The promise behind the picture: a new heart and a new spirit within you.' },
      { r: 'JOH 1:12', n: 'Receive Him, believe His name — the right to become children of God.' },
      { r: 'JOH 1:13', n: 'Born not of blood nor human decision, but of God.' },
      { r: 'JOH 3:3', n: 'To Nicodemus: unless one is born again, he cannot see the kingdom.' },
      { r: 'JOH 3:7', n: 'Do not be amazed: you MUST be born again — necessity, not suggestion.' },
      { r: '2CO 5:17', n: 'In Christ: a new creation. The old has passed; the new has come.' },
      { r: 'TIT 3:5', n: 'The washing of new birth and renewal by the Holy Spirit — His mercy, not our deeds.' },
      { r: 'JAM 1:18', n: 'He chose to give us birth through the word of truth.' },
      { r: '1PE 1:3', n: 'Born again into a LIVING hope through the resurrection.' },
      { r: '1PE 1:23', n: 'Born of imperishable seed — the birth cannot decay.' },
      { r: '1JO 5:1', n: 'Everyone who believes that Jesus is the Christ has been born of God. Believing = born.' }
    ] },

  { id: 'not-by-works', cat: 'gift', icon: '🚫', title: 'Not by Works',
    tagline: 'The scandal of grace: your best deeds don’t count toward it.',
    intro: 'Scripture is relentless: works cannot start, sustain, or secure salvation. Works matter enormously — but as fruit and for reward, never as the root.',
    verses: [
      { r: 'ISA 64:6', n: 'Our righteous acts, God’s appraisal: filthy rags.' },
      { r: 'ROM 3:20', n: 'By works of the law NO flesh will be justified — the law diagnoses, it cannot cure.' },
      { r: 'ROM 4:4', n: 'Work earns a wage; a wage is owed. Salvation is never an obligation God owes.' },
      { r: 'ROM 4:5', n: 'God justifies the ungodly — the one who does not work but believes.' },
      { r: 'ROM 11:6', n: 'If by grace, then no longer by works — otherwise grace stops being grace.' },
      { r: 'GAL 2:21', n: 'If righteousness came through law, Christ died for nothing.' },
      { r: 'GAL 3:2', n: 'Paul’s one question: did you receive the Spirit by works, or by hearing with faith?' },
      { r: 'EPH 2:9', n: 'Not of works, so that no one can boast.' },
      { r: '2TI 1:9', n: 'Saved and called — not because of our works, but His purpose and grace.' },
      { r: 'TIT 3:5', n: 'Not by righteous deeds we had done — He saved us by His mercy.' },
      { r: 'EPH 2:10', n: 'The right order: created in Christ FOR good works — works flow from salvation, never into it.' }
    ] },

  { id: 'blood-lamb', cat: 'gift', icon: '🩸', title: 'The Blood of the Lamb',
    tagline: 'One scarlet thread from Eden to the throne.',
    intro: 'Follow the sacrifice: a covering in Eden, a ram on Moriah, blood on doorposts, a suffering Servant — until John points and says, "Behold, the Lamb of God."',
    verses: [
      { r: 'GEN 3:21', n: 'The first death in Scripture: God clothes the guilty with skins.' },
      { r: 'GEN 22:8', n: 'Abraham’s prophecy on Moriah: God Himself will provide the lamb.' },
      { r: 'EXO 12:13', n: 'Passover: when I see the blood, I will pass over you.' },
      { r: 'LEV 17:11', n: 'The principle stated: it is the blood that makes atonement for the soul.' },
      { r: 'ISA 53:7', n: 'Like a lamb led to slaughter — silent, willing.' },
      { r: 'JOH 1:29', n: 'John’s introduction: Behold, the Lamb of God who takes away the sin of the world!' },
      { r: 'MAR 10:45', n: 'The Son of Man came to give His life as a ransom for many.' },
      { r: 'HEB 9:22', n: 'Without the shedding of blood there is no forgiveness.' },
      { r: 'HEB 9:12', n: 'Not the blood of goats — His OWN blood, securing eternal redemption. Once.' },
      { r: '1PE 1:18', n: 'You were redeemed — not with silver or gold...' },
      { r: '1PE 1:19', n: '...but with the precious blood of Christ, a lamb without blemish.' },
      { r: 'REV 5:9', n: 'Heaven’s new song: You were slain, and with Your blood You purchased for God.' }
    ] },

  { id: 'whoever', cat: 'gift', icon: '🌍', title: '"Whoever": The Widest Word',
    tagline: 'No fine print. No excluded names.',
    intro: 'The gospel’s favorite pronoun is "whoever." God’s offer is as wide as the human race — which means it is exactly as wide as you.',
    verses: [
      { r: 'ISA 45:22', n: 'Turn to Me and be saved, all the ends of the earth.' },
      { r: 'JOL 2:32', n: 'Everyone who calls on the name of the LORD will be saved.' },
      { r: 'MAT 11:28', n: 'Come to Me, ALL you who are weary — rest is offered, not sold.' },
      { r: 'JOH 3:16', n: 'Whoever believes in Him shall not perish.' },
      { r: 'JOH 6:37', n: 'WHOEVER comes to Me I will never cast out.' },
      { r: 'JOH 6:40', n: 'The Father’s will: EVERYONE who looks to the Son and believes has eternal life.' },
      { r: 'ACT 2:21', n: 'Peter at Pentecost quotes Joel: everyone who calls will be saved.' },
      { r: 'ACT 10:43', n: 'All the prophets agree: everyone who believes receives forgiveness through His name.' },
      { r: 'ROM 10:13', n: 'Paul quotes Joel too — the promise refused to stay in one Testament.' },
      { r: '2PE 3:9', n: 'Not willing that ANY should perish, but that all should come to repentance.' },
      { r: 'REV 22:17', n: 'The Spirit and the bride say "Come" — and whoever wishes may take freely.' }
    ] },

  { id: 'everlasting-now', cat: 'gift', icon: '⏳', title: 'Everlasting Life, Present Tense',
    tagline: 'Not "will get" — HAS. Right now.',
    intro: 'Read the verb tenses. Jesus does not say the believer will someday receive eternal life at the finish line — He says the believer HAS it, here, today. And what is everlasting cannot end.',
    verses: [
      { r: 'JOH 3:36', n: 'Whoever believes in the Son HAS eternal life — present possession.' },
      { r: 'JOH 5:24', n: 'HAS eternal life... HAS passed from death to life. Both already done.' },
      { r: 'JOH 6:47', n: 'He who believes HAS everlasting life — Jesus’ shortest gospel sermon.' },
      { r: 'JOH 17:3', n: 'Defined: this IS eternal life — knowing the only true God and Jesus Christ.' },
      { r: 'JOH 10:10', n: 'Not bare survival: life, and life in abundance.' },
      { r: '1JO 5:11', n: 'God HAS GIVEN us eternal life — past tense gift, present tense owning.' },
      { r: '1JO 5:12', n: 'He who has the Son has life — possession language again.' },
      { r: '1JO 5:13', n: 'That you may know you HAVE eternal life — assurance hangs on this tense.' },
      { r: 'JOH 11:26', n: 'Whoever lives and believes in Me will never die. "Do you believe this?"' }
    ] },

  // ═══ WALKING WITH GOD ═══
  { id: 'discipleship', cat: 'walk', icon: '🎒', title: 'The Costly Call',
    tagline: 'Salvation is free. Following costs everything.',
    intro: 'Scripture keeps two truths side by side: eternal life is a free gift to believers, and discipleship is a costly road for followers. Confusing them ruins both. This thread walks the costly one — for those already safe in grace.',
    verses: [
      { r: 'LUK 9:23', n: 'The terms of following: deny self, take up a cross DAILY.' },
      { r: 'LUK 14:26', n: 'Loyalty to Christ must outrank family and even your own life.' },
      { r: 'LUK 14:27', n: 'Whoever does not carry his cross cannot be My DISCIPLE — the word is disciple, not believer.' },
      { r: 'LUK 14:28', n: 'Jesus tells would-be followers to sit down and count the cost first.' },
      { r: 'LUK 14:33', n: 'The full invoice: renounce all. Gifts are free; apprenticeships are not.' },
      { r: 'MAT 11:29', n: 'Yet the yoke is His: take it and LEARN from Me — discipleship means apprenticeship.' },
      { r: 'JOH 8:31', n: 'To those who HAD believed: abide in My word and you will be disciples indeed.' },
      { r: 'ROM 12:1', n: 'The logic of grace: in view of God’s mercies, offer yourselves as living sacrifices.' },
      { r: 'PHP 3:8', n: 'Paul’s ledger: everything is loss compared to knowing Christ.' },
      { r: '2TI 2:2', n: 'Disciples make disciples: entrust it to faithful men who will teach others.' }
    ] },

  { id: 'rewards', cat: 'walk', icon: '👑', title: 'Crowns at the Bema',
    tagline: 'Salvation is a gift; rewards are earned.',
    intro: 'Believers will stand at the Judgment Seat (Bema) of Christ — not to determine destiny, but to evaluate service. You cannot lose your salvation there, but you can lose your reward. Run to win.',
    verses: [
      { r: 'MAT 6:20', n: 'Store up treasures IN HEAVEN — Jesus assumes heaven’s bank takes deposits.' },
      { r: 'MAT 16:27', n: 'The Son of Man will repay each person according to what he has DONE.' },
      { r: '1CO 3:11', n: 'The foundation is Christ — that part is settled and free.' },
      { r: '1CO 3:13', n: 'But each one’s WORK will be tested by fire — quality inspection, not entrance exam.' },
      { r: '1CO 3:14', n: 'If the work survives: reward.' },
      { r: '1CO 3:15', n: 'If it burns: loss of reward — yet he himself SAVED, though as through fire.' },
      { r: '1CO 9:24', n: 'Run in such a way as to take the prize.' },
      { r: '1CO 9:25', n: 'They compete for a fading wreath; we, for an imperishable crown.' },
      { r: '2CO 5:10', n: 'We must ALL appear before the judgment seat of Christ — believers, evaluated.' },
      { r: 'COL 3:23', n: 'Work heartily, as for the Lord — even hidden work is on the books.' },
      { r: 'COL 3:24', n: 'From the Lord you will receive the inheritance as your REWARD.' },
      { r: '2TI 4:8', n: 'The crown of righteousness — for all who have longed for His appearing.' },
      { r: '2JO 1:8', n: 'Watch yourselves, that you may be rewarded FULLY — reward can be forfeited.' },
      { r: 'REV 22:12', n: 'Behold, I am coming soon — My reward is with Me.' }
    ] },

  { id: 'abide', cat: 'walk', icon: '🍇', title: 'Abiding in the Vine',
    tagline: 'Fruit comes from staying close, not trying hard.',
    intro: 'Union with Christ is permanent; fellowship with Christ is enjoyed by abiding. Branches don’t strain to make grapes — they stay attached.',
    verses: [
      { r: 'PSA 91:1', n: 'The Old Testament picture: dwelling in the shelter of the Most High.' },
      { r: 'JOH 15:1', n: 'I am the true vine — the source of everything a branch produces.' },
      { r: 'JOH 15:4', n: 'Abide in Me: the branch cannot bear fruit by itself.' },
      { r: 'JOH 15:5', n: 'Apart from Me you can do NOTHING — the most freeing verse in the Bible.' },
      { r: 'JOH 15:7', n: 'Abiding reshapes prayer: His words at home in you, ask what you will.' },
      { r: 'JOH 15:9', n: 'Abide in My LOVE — fellowship is the point, not productivity.' },
      { r: 'JOH 15:10', n: 'Obedience keeps you in the sunshine of His love — as Jesus obeyed the Father.' },
      { r: 'JOH 15:11', n: 'The goal: His joy in you, and your joy made FULL.' },
      { r: '1JO 2:6', n: 'The claim test: whoever says he abides ought to walk as Jesus walked.' },
      { r: '1JO 2:28', n: 'Abide now — so you’ll have confidence, not shame, at His appearing. (A reward issue, not a rescue issue.)' }
    ] },

  { id: 'spirit-walk', cat: 'walk', icon: '💨', title: 'Walking by the Spirit',
    tagline: 'The Christian life is supernatural or it is exhausting.',
    intro: 'God never asked you to imitate Christ in your own strength. He moved in. Fruit grows where the Spirit leads.',
    verses: [
      { r: 'EZK 36:27', n: 'The promise: I will put My Spirit WITHIN you.' },
      { r: 'JOH 14:16', n: 'Another Helper — to be with you FOREVER (note the duration).' },
      { r: 'JOH 14:26', n: 'The Spirit teaches and reminds — your resident tutor in the things of Christ.' },
      { r: 'ACT 1:8', n: 'Power to witness comes from the Spirit, not personality.' },
      { r: 'ROM 8:14', n: 'Those led by the Spirit of God — these are sons of God.' },
      { r: 'GAL 5:16', n: 'Walk by the Spirit and you will NOT fulfill the desires of the flesh.' },
      { r: 'GAL 5:22', n: 'Fruit, not works: love, joy, peace, patience, kindness, goodness, faithfulness...' },
      { r: 'GAL 5:23', n: '...gentleness, self-control. Against such things there is no law.' },
      { r: 'GAL 5:25', n: 'Since we LIVE by the Spirit, let us also WALK in step with the Spirit.' },
      { r: 'EPH 5:18', n: 'Be filled with the Spirit — a command in the present tense: keep on being filled.' }
    ] },

  { id: 'prayer', cat: 'walk', icon: '🙏', title: 'Bold at the Throne',
    tagline: 'You have an open door to the throne room. Use it.',
    intro: 'Prayer is not a performance for God’s approval — it is a child’s access to a Father who already said yes to you in Christ.',
    verses: [
      { r: 'PSA 145:18', n: 'The LORD is near to all who call on Him in truth.' },
      { r: 'JER 33:3', n: 'Call to Me and I will answer — and show you great, unsearchable things.' },
      { r: 'MAT 6:6', n: 'Pray to your Father in secret — He sees, and He rewards.' },
      { r: 'MAT 7:7', n: 'Ask, seek, knock — three present-tense invitations to keep coming.' },
      { r: 'JOH 16:24', n: 'Ask in My name — that your joy may be made full.' },
      { r: 'PHP 4:6', n: 'Be anxious for nothing; pray about everything — with thanksgiving.' },
      { r: '1TH 5:17', n: 'Pray without ceasing — a posture, not a marathon.' },
      { r: 'HEB 4:16', n: 'Approach the throne of grace with CONFIDENCE — mercy and grace await.' },
      { r: 'JAM 5:16', n: 'The prayer of a righteous man has great power.' },
      { r: '1JO 5:14', n: 'Our confidence: if we ask according to His will, He hears us.' },
      { r: '1JO 5:15', n: 'And if He hears, we have what we asked — prayer banks on His character.' }
    ] },

  { id: 'fellowship', cat: 'walk', icon: '🤝', title: 'Confession & Fellowship',
    tagline: 'Sin breaks fellowship with the Father — never sonship.',
    intro: 'First John 1 is family talk: written to believers about walking in the light. Confession restores the JOY and closeness of the relationship — the relationship itself was never in danger.',
    verses: [
      { r: 'PSA 32:5', n: 'David’s relief: I acknowledged my sin — and You forgave.' },
      { r: 'PSA 51:12', n: 'Note what David asks back: the JOY of Your salvation — not the salvation itself.' },
      { r: 'PRO 28:13', n: 'Concealing sin never prospers; confessing and forsaking finds mercy.' },
      { r: 'LUK 15:24', n: 'The prodigal was "my SON" the whole time — dead to fellowship, never disowned.' },
      { r: 'MAT 6:14', n: 'Family forgiveness: the Father’s daily forgiveness of His children mirrors ours of others.' },
      { r: '1JO 1:3', n: 'John’s aim: that you may have FELLOWSHIP with the Father and the Son.' },
      { r: '1JO 1:7', n: 'Walk in the light — and the blood keeps on cleansing.' },
      { r: '1JO 1:9', n: 'If we confess, He is faithful and just to forgive — the family bathtub, not the courtroom.' },
      { r: 'JAM 4:8', n: 'Draw near to God and He will draw near to you.' },
      { r: 'PSA 103:12', n: 'As far as east from west — how far He has removed our transgressions.' }
    ] },

  { id: 'growth', cat: 'walk', icon: '📈', title: 'From Milk to Meat',
    tagline: 'Every believer is born an infant. None should stay one.',
    intro: 'Scripture openly acknowledges that believers can stall — Corinth proves it. Growth is real, expected, and gradual: crave the milk, then chew the meat.',
    verses: [
      { r: '1PE 2:2', n: 'Like newborns, CRAVE the pure milk of the word — appetite comes first.' },
      { r: '1CO 3:1', n: 'Paul calls the Corinthians "brothers"... and "infants in Christ." Both can be true.' },
      { r: 'HEB 5:13', n: 'Milk-drinkers are unskilled in the word of righteousness.' },
      { r: 'HEB 5:14', n: 'Solid food is for the mature — senses TRAINED by practice.' },
      { r: 'COL 2:6', n: 'As you received Christ (by faith), so WALK in Him (by faith).' },
      { r: 'COL 2:7', n: 'Rooted, built up, established — and overflowing with thankfulness.' },
      { r: '2PE 1:5', n: 'Make every effort: add to your faith virtue, knowledge...' },
      { r: 'EPH 4:15', n: 'Speaking truth in love, GROW UP in every way into Christ the Head.' },
      { r: 'PHP 1:9', n: 'Paul’s prayer: love abounding more and more, with knowledge and discernment.' },
      { r: '2PE 3:18', n: 'The last verse Peter ever wrote: GROW in the grace and knowledge of our Lord.' }
    ] },

  { id: 'serve', cat: 'walk', icon: '🧺', title: 'The Towel and the Basin',
    tagline: 'Greatness in the kingdom stoops.',
    intro: 'The night before the cross, the Lord of glory washed feet. Service is not what we do to earn His favor — it is what His favor turns us into.',
    verses: [
      { r: 'MAR 10:45', n: 'The pattern: even the Son of Man came to serve, not be served.' },
      { r: 'JOH 13:14', n: 'If your Lord washed feet, no task is beneath you.' },
      { r: 'GAL 5:13', n: 'You were called to freedom — use it to serve one another in love.' },
      { r: 'GAL 6:2', n: 'Carry one another’s burdens — this fulfills the law of Christ.' },
      { r: 'GAL 6:10', n: 'As we have opportunity: do good to all, especially the household of faith.' },
      { r: 'PHP 2:3', n: 'In humility consider others more important than yourselves.' },
      { r: 'PHP 2:4', n: 'Look not only to your own interests, but also to the interests of others.' },
      { r: 'ROM 12:10', n: 'Be devoted to one another; outdo one another in showing honor.' },
      { r: '1PE 4:10', n: 'Each has received a gift — use it to serve, as good stewards of God’s grace.' },
      { r: 'HEB 6:10', n: 'God is not unjust: He will not forget your work and love. It is all on record.' }
    ] },

  { id: 'trials', cat: 'walk', icon: '⛈️', title: 'Gold Through Fire',
    tagline: 'Trials refine believers; they never un-adopt them.',
    intro: 'Suffering has a syllabus. God wastes none of it — He refines faith like gold and crowns endurance at the end.',
    verses: [
      { r: 'JOB 23:10', n: 'Job’s defiant hope: when He has tested me, I will come forth as gold.' },
      { r: 'PSA 34:19', n: 'Many are the afflictions of the righteous — but the LORD delivers.' },
      { r: 'ISA 43:2', n: 'Through waters, through rivers, through fire — WITH you in all three.' },
      { r: 'ROM 5:3', n: 'We rejoice in suffering, because suffering produces perseverance...' },
      { r: 'ROM 5:4', n: '...and perseverance, character; and character, hope.' },
      { r: 'ROM 8:28', n: 'God works ALL things together for good, for those who love Him.' },
      { r: '2CO 4:17', n: 'Light and momentary — producing an eternal weight of glory.' },
      { r: 'JAM 1:2', n: 'Consider it pure JOY — trials are testing grounds, not punishments.' },
      { r: 'JAM 1:3', n: 'The testing of your faith develops perseverance.' },
      { r: 'JAM 1:12', n: 'Blessed is the one who perseveres: the crown of life awaits — a reward for endurance.' },
      { r: '1PE 1:6', n: 'Grief now, for a little while, if necessary — Peter is honest about the timeline.' },
      { r: '1PE 1:7', n: 'So that your faith — more precious than gold — may result in praise at His revealing.' },
      { r: '1PE 5:10', n: 'After you have suffered a little while, He Himself will restore, confirm, strengthen you.' }
    ] },

  // ═══ JESUS ═══
  { id: 'deity', cat: 'jesus', icon: '👑', title: 'The Deity of Christ',
    tagline: 'Not a good teacher. God in the flesh.',
    intro: 'The New Testament does not whisper Christ’s deity — it opens with it, argues it, and worships accordingly. Read the claims and decide what they demand.',
    verses: [
      { r: 'ISA 9:6', n: 'The child born to us carries divine names: Mighty God, Everlasting Father.' },
      { r: 'MIC 5:2', n: 'Bethlehem’s ruler has origins "from the days of eternity."' },
      { r: 'JOH 1:1', n: 'In the beginning was the Word... and the Word WAS God.' },
      { r: 'JOH 8:58', n: 'Before Abraham was born, I AM — He takes the name from the burning bush.' },
      { r: 'JOH 10:30', n: 'I and the Father are one. His hearers reached for stones — they understood.' },
      { r: 'JOH 20:28', n: 'Thomas’s confession, uncorrected: "My Lord and my God!"' },
      { r: 'COL 1:16', n: 'All things were created THROUGH Him and FOR Him.' },
      { r: 'COL 2:9', n: 'In Him all the FULLNESS of deity dwells in bodily form.' },
      { r: 'TIT 2:13', n: 'Our great God and Savior, Jesus Christ — one article, one Person.' },
      { r: 'HEB 1:3', n: 'The exact expression of God’s nature, upholding all things by His word.' },
      { r: 'HEB 1:8', n: 'The Father addresses the Son: "Your throne, O GOD, endures forever."' },
      { r: 'REV 22:13', n: 'Alpha and Omega, First and Last — Jesus claims the titles of Yahweh.' }
    ] },

  { id: 'lamb-foretold', cat: 'jesus', icon: '🔭', title: 'The Messiah Foretold',
    tagline: 'Written centuries early. Fulfilled to the letter.',
    intro: 'A literal reading of the prophets yields a startling portrait — birthplace, lineage, betrayal, pierced hands — written long before Bethlehem. Fulfilled prophecy is God’s signature.',
    verses: [
      { r: 'GEN 3:15', n: 'The first gospel: the Seed of the woman will crush the serpent’s head.' },
      { r: 'GEN 49:10', n: 'The scepter stays with Judah — until He comes to whom it belongs.' },
      { r: 'DEU 18:15', n: 'A Prophet like Moses — listen to Him.' },
      { r: '2SA 7:12', n: 'David’s offspring will have a kingdom established by God Himself.' },
      { r: 'PSA 16:10', n: 'You will not abandon my soul to Sheol or let Your Holy One see decay.' },
      { r: 'PSA 22:18', n: 'They divide my garments and cast lots — written a millennium before the cross.' },
      { r: 'ISA 7:14', n: 'The virgin will conceive and bear a son: Immanuel, God with us.' },
      { r: 'ISA 53:5', n: 'Pierced for OUR transgressions, crushed for OUR iniquities.' },
      { r: 'MIC 5:2', n: 'Out of little Bethlehem: the ruler of Israel.' },
      { r: 'ZEC 9:9', n: 'Your King comes to you — righteous, victorious, riding on a donkey.' },
      { r: 'ZEC 12:10', n: 'They will look on Me, the One they have pierced.' },
      { r: 'MAL 3:1', n: 'A messenger prepares the way — then the Lord suddenly comes to His temple.' }
    ] },

  { id: 'cross', cat: 'jesus', icon: '✝️', title: 'It Is Finished',
    tagline: 'Tetelestai: paid in full.',
    intro: 'Jesus’ final word from the cross was a single Greek term merchants stamped on settled bills: tetelestai — paid in full. Nothing is left for you to add.',
    verses: [
      { r: 'ISA 53:6', n: 'The LORD laid on Him the iniquity of us all — our debt, His account.' },
      { r: 'MAR 10:45', n: 'A ransom for many — the price of release, paid by the Son.' },
      { r: 'JOH 19:30', n: '"It is finished." Not "it is started." The work is complete.' },
      { r: 'ROM 5:6', n: 'At just the right time, Christ died for the ungodly.' },
      { r: '1CO 1:18', n: 'The message of the cross: foolishness to the perishing, power to the saved.' },
      { r: '1CO 15:3', n: 'Of FIRST importance: Christ died for our sins according to the Scriptures.' },
      { r: 'GAL 3:13', n: 'He became a curse for us — redeeming us from the curse of the law.' },
      { r: 'COL 2:14', n: 'The debt record: canceled, taken away, NAILED to the cross.' },
      { r: 'HEB 10:12', n: 'One sacrifice for sins FOREVER — then He sat down. The work was done.' },
      { r: 'HEB 10:14', n: 'By one offering He has PERFECTED FOREVER those being sanctified.' },
      { r: '1PE 2:24', n: 'He Himself bore our sins in His body on the tree.' },
      { r: '1PE 3:18', n: 'Christ suffered for sins ONCE for all — the righteous for the unrighteous.' }
    ] },

  { id: 'risen', cat: 'jesus', icon: '🌄', title: 'Risen Indeed',
    tagline: 'The tomb is empty. Everything changes.',
    intro: 'Christianity stakes everything on a historical claim: on the third day, He rose. Paul says if it is false, faith is futile — and then stakes his life that it is true.',
    verses: [
      { r: 'JOB 19:25', n: 'The oldest hope on record: I know that my Redeemer LIVES.' },
      { r: 'PSA 16:10', n: 'The Holy One will not see decay — quoted at Pentecost as prophecy of resurrection.' },
      { r: 'MAT 28:6', n: 'He is not here — He has risen, JUST AS HE SAID.' },
      { r: 'LUK 24:39', n: 'Touch Me and see: flesh and bones — a real body, not a ghost.' },
      { r: 'ACT 2:24', n: 'God raised Him: it was impossible for death to keep its hold on Him.' },
      { r: 'ROM 4:25', n: 'Delivered over for our trespasses, RAISED for our justification.' },
      { r: 'ROM 6:9', n: 'Death no longer has dominion over Him — He cannot die again.' },
      { r: '1CO 15:17', n: 'Paul’s honesty: if Christ has not been raised, your faith is worthless.' },
      { r: '1CO 15:20', n: 'But Christ HAS been raised — the firstfruits of those who sleep.' },
      { r: '1CO 15:57', n: 'Thanks be to God who gives us the victory through our Lord Jesus Christ!' },
      { r: '1PE 1:3', n: 'His resurrection births our living hope.' },
      { r: 'REV 1:18', n: 'I was dead, and behold — alive forever and ever. And I hold the keys.' }
    ] },

  { id: 'high-priest', cat: 'jesus', icon: '🕯️', title: 'Our Great High Priest',
    tagline: 'He always lives to intercede for you.',
    intro: 'Right now, this minute, Jesus is praying for you. His priesthood never expires, so His salvation never lapses — He saves to the uttermost.',
    verses: [
      { r: 'PSA 110:4', n: 'The oath: You are a priest FOREVER in the order of Melchizedek.' },
      { r: 'HEB 2:17', n: 'Made like His brothers in every way — a merciful and faithful high priest.' },
      { r: 'HEB 4:14', n: 'We have a GREAT high priest who has passed through the heavens.' },
      { r: 'HEB 4:15', n: 'Tempted in every way as we are — yet without sin. He understands.' },
      { r: 'HEB 4:16', n: 'Therefore: approach the throne of grace with confidence.' },
      { r: 'HEB 7:24', n: 'Because He lives forever, His priesthood is PERMANENT.' },
      { r: 'HEB 7:25', n: 'So He saves to the uttermost — He ALWAYS lives to intercede for them.' },
      { r: 'HEB 9:24', n: 'He entered heaven itself, now to appear in God’s presence FOR US.' },
      { r: 'ROM 8:34', n: 'Who condemns? Christ died, was raised, and is INTERCEDING for us.' },
      { r: '1JO 2:1', n: 'When a believer sins: we have an Advocate with the Father — Jesus the Righteous.' },
      { r: 'JOH 17:20', n: 'He prayed for all who would believe through the apostles’ word — that includes you.' }
    ] },

  { id: 'i-am', cat: 'jesus', icon: '💬', title: 'The Seven "I AM"s',
    tagline: 'Seven metaphors. One staggering claim.',
    intro: 'In John’s Gospel Jesus completes the sentence God began at the burning bush. Each "I am" answers a different human hunger — and together they claim the divine name.',
    verses: [
      { r: 'EXO 3:14', n: 'The backdrop: God names Himself to Moses — "I AM WHO I AM."' },
      { r: 'JOH 6:35', n: 'I am the bread of life — for the hunger under all hungers.' },
      { r: 'JOH 8:12', n: 'I am the light of the world — whoever follows will never walk in darkness.' },
      { r: 'JOH 10:9', n: 'I am the door — whoever enters through Me will be saved.' },
      { r: 'JOH 10:11', n: 'I am the good shepherd — who lays down His life for the sheep.' },
      { r: 'JOH 11:25', n: 'I am the resurrection and the life — said outside a tomb He was about to empty.' },
      { r: 'JOH 14:6', n: 'I am the way, the truth, and the life — no one comes to the Father except through Me.' },
      { r: 'JOH 15:1', n: 'I am the true vine — the life source of every branch.' },
      { r: 'JOH 8:58', n: 'And the claim beneath them all: before Abraham was born, I AM.' }
    ] },

  { id: 'return', cat: 'jesus', icon: '🌟', title: 'The Blessed Hope',
    tagline: 'He promised to come back. Taken literally, that changes today.',
    intro: 'The same Jesus who ascended will return the same way — literally, bodily, perhaps at any moment. The early church greeted each other with "Maranatha": our Lord, come!',
    verses: [
      { r: 'JOH 14:3', n: 'If I go, I WILL COME AGAIN and receive you to Myself — a groom’s promise.' },
      { r: 'ACT 1:11', n: 'The angels’ geometry: this SAME Jesus will come in the SAME way you saw Him go.' },
      { r: '1CO 15:51', n: 'A mystery revealed: we will not all sleep, but we will all be changed...' },
      { r: '1CO 15:52', n: '...in a flash, in the twinkling of an eye, at the last trumpet.' },
      { r: 'PHP 3:20', n: 'Our citizenship is in heaven — and we eagerly await a Savior from there.' },
      { r: '1TH 4:16', n: 'The Lord Himself will descend with a shout — the dead in Christ rise first.' },
      { r: '1TH 4:17', n: 'Then we who remain will be CAUGHT UP together to meet the Lord in the air.' },
      { r: '1TH 4:18', n: 'Purpose of the doctrine: comfort one another with these words.' },
      { r: 'TIT 2:13', n: 'The blessed hope: the glorious appearing of our great God and Savior.' },
      { r: 'HEB 9:28', n: 'He will appear a second time — to those who eagerly await Him.' },
      { r: 'REV 22:20', n: 'The Bible’s last promise and last prayer: "Yes, I am coming soon." Amen — come, Lord Jesus!' }
    ] },

  // ═══ PROMISES TO STAND ON ═══
  { id: 'peace', cat: 'promises', icon: '🕊️', title: 'Peace Beyond Understanding',
    tagline: 'Peace WITH God is settled; the peace OF God is offered daily.',
    intro: 'Justification gives every believer permanent peace WITH God. On that foundation, God offers the felt peace OF God — a guard for anxious hearts.',
    verses: [
      { r: 'NUM 6:26', n: 'The ancient blessing: the LORD lift up His countenance and give you peace.' },
      { r: 'PSA 4:8', n: 'In peace I will lie down and sleep — You alone make me dwell in safety.' },
      { r: 'PSA 29:11', n: 'The LORD blesses His people with peace.' },
      { r: 'ISA 26:3', n: 'Perfect peace for the mind stayed on You.' },
      { r: 'JOH 14:27', n: 'MY peace I give you — not as the world gives.' },
      { r: 'JOH 16:33', n: 'In the world, trouble; in Me, peace. Take heart — I have overcome the world.' },
      { r: 'ROM 5:1', n: 'Justified by faith, we HAVE peace WITH God — a settled treaty, not a feeling.' },
      { r: 'PHP 4:7', n: 'The peace OF God, surpassing understanding, GUARDS hearts and minds.' },
      { r: 'COL 3:15', n: 'Let the peace of Christ rule — be the umpire — in your hearts.' },
      { r: '2TH 3:16', n: 'The Lord of peace give you peace at ALL times and in EVERY way.' }
    ] },

  { id: 'fear-not', cat: 'promises', icon: '🦁', title: 'Do Not Be Afraid',
    tagline: 'The Bible’s most repeated command.',
    intro: '"Fear not" appears in Scripture again and again — and it is almost always attached to a reason: I am with you. Courage is not the absence of fear; it is the presence of God.',
    verses: [
      { r: 'GEN 15:1', n: 'To Abram: fear not — I am your shield, your very great reward.' },
      { r: 'DEU 31:8', n: 'The LORD goes before you; He will never leave you. Do not be dismayed.' },
      { r: 'JOS 1:9', n: 'Be strong and courageous — for the LORD your God is with you wherever you go.' },
      { r: 'PSA 27:1', n: 'The LORD is my light and salvation — whom shall I fear?' },
      { r: 'PSA 56:3', n: 'The honest version: WHEN I am afraid, I will trust in You.' },
      { r: 'ISA 41:10', n: 'Fear not, for I am WITH you — I will strengthen you and uphold you.' },
      { r: 'ISA 41:13', n: 'I am the LORD who takes hold of your right hand and says: do not fear.' },
      { r: 'ISA 43:1', n: 'Fear not, for I have redeemed you; I have called you BY NAME — you are Mine.' },
      { r: 'MAT 10:31', n: 'You are worth more than many sparrows — and He watches every sparrow.' },
      { r: 'LUK 12:32', n: 'Fear not, little flock — the Father is PLEASED to GIVE you the kingdom.' },
      { r: '2TI 1:7', n: 'God gave us a spirit not of fear, but of power, love, and a sound mind.' },
      { r: 'HEB 13:6', n: 'So we say with confidence: the Lord is my helper; I will not be afraid.' }
    ] },

  { id: 'refuge', cat: 'promises', icon: '🏰', title: 'A Strong Tower',
    tagline: 'When everything shakes, run somewhere solid.',
    intro: 'Scripture piles up fortress language for God: rock, shield, refuge, stronghold, tower. The invitation in every metaphor is the same — run IN.',
    verses: [
      { r: 'DEU 33:27', n: 'The eternal God is your dwelling, and underneath are the everlasting arms.' },
      { r: 'PSA 18:2', n: 'David empties the armory: rock, fortress, deliverer, shield, stronghold.' },
      { r: 'PSA 46:1', n: 'God is our refuge and strength — a VERY PRESENT help in trouble.' },
      { r: 'PSA 61:2', n: 'From the end of the earth: lead me to the rock that is higher than I.' },
      { r: 'PSA 62:8', n: 'Pour out your heart before Him — God is a refuge for us.' },
      { r: 'PSA 91:2', n: 'I will say of the LORD: my refuge and my fortress, my God in whom I trust.' },
      { r: 'PSA 91:4', n: 'Under His wings you will find refuge — His faithfulness is a shield.' },
      { r: 'PRO 18:10', n: 'The name of the LORD is a strong tower; the righteous RUN to it and are safe.' },
      { r: 'NAM 1:7', n: 'Nahum’s hidden gem: the LORD is good, a stronghold in the day of distress — He KNOWS those who take refuge in Him.' }
    ] },

  { id: 'provision', cat: 'promises', icon: '🍞', title: 'Daily Bread',
    tagline: 'Manna came one day at a time. It still does.',
    intro: 'God’s provision is usually daily, rarely early, and never late. From wilderness manna to ravens with room service, He feeds those who look to Him.',
    verses: [
      { r: 'GEN 22:14', n: 'Abraham names the place: The LORD Will Provide (Jehovah-Jireh).' },
      { r: 'EXO 16:4', n: 'Manna rule: gather enough for THAT day — provision teaches daily trust.' },
      { r: '1KI 17:6', n: 'Ravens brought Elijah bread and meat — God’s couriers can be unconventional.' },
      { r: 'PSA 37:25', n: 'David’s lifetime observation: I have not seen the righteous forsaken.' },
      { r: 'MAT 6:11', n: 'Jesus teaches us to ask small: give us this day our DAILY bread.' },
      { r: 'MAT 6:26', n: 'Look at the birds — your heavenly Father feeds them. Are you not worth more?' },
      { r: 'MAT 6:33', n: 'Seek first the kingdom — and these things will be added to you.' },
      { r: '2CO 9:8', n: 'God is able to make ALL grace abound, so you have all sufficiency in all things.' },
      { r: 'PHP 4:19', n: 'My God will supply every need of yours according to His riches in glory.' }
    ] },

  { id: 'comfort', cat: 'promises', icon: '🫂', title: 'The God of All Comfort',
    tagline: 'He keeps your tears in a bottle.',
    intro: 'God does not waste sorrow and does not rush grief. He is near to the brokenhearted — near enough to count tears.',
    verses: [
      { r: 'PSA 30:5', n: 'Weeping may stay the night, but joy comes with the morning.' },
      { r: 'PSA 34:18', n: 'The LORD is NEAR to the brokenhearted.' },
      { r: 'PSA 56:8', n: 'You have kept my tears in Your bottle — grief is recorded, not ignored.' },
      { r: 'PSA 147:3', n: 'He heals the brokenhearted and binds up their wounds.' },
      { r: 'ISA 61:3', n: 'Beauty for ashes, oil of joy for mourning — the great exchange of comfort.' },
      { r: 'MAT 5:4', n: 'Blessed are those who mourn, for they WILL be comforted.' },
      { r: 'JOH 11:35', n: 'The shortest verse carries the biggest comfort: Jesus wept. He enters grief.' },
      { r: 'JOH 14:1', n: 'Let not your heart be troubled — believe in God; believe also in Me.' },
      { r: '2CO 1:3', n: 'The Father of mercies and God of ALL comfort.' },
      { r: '2CO 1:4', n: 'Comforted so we can comfort — sorrow gets recycled into ministry.' },
      { r: '1TH 4:13', n: 'We grieve — but not like those who have no hope.' },
      { r: 'REV 21:4', n: 'The last promise: He will wipe away every tear. Death shall be no more.' }
    ] },

  { id: 'hope-anchor', cat: 'promises', icon: '⚓', title: 'Hope That Anchors',
    tagline: 'Biblical hope is not wishing — it is waiting on certainty.',
    intro: 'In Scripture, hope is confident expectation anchored in God’s character. (And yes — we’ll read Jeremiah 29:11 in its real context. It gets better, not worse.)',
    verses: [
      { r: 'PSA 42:11', n: 'Preach to yourself: why so downcast, O my soul? HOPE in God.' },
      { r: 'PSA 62:5', n: 'My soul, wait in silence for God alone — my hope is from Him.' },
      { r: 'LAM 3:21', n: 'THIS I call to mind, and therefore I have hope — hope is a chosen memory.' },
      { r: 'JER 29:11', n: 'Spoken to exiles facing 70 years in Babylon: plans for welfare, a future, a hope. God gives long-haul hope, not shortcuts.' },
      { r: 'ROM 15:13', n: 'The God of hope fills you with joy and peace AS YOU BELIEVE — so hope overflows.' },
      { r: 'TIT 1:2', n: 'Hope of eternal life, promised before time began by the God who cannot lie.' },
      { r: 'HEB 6:19', n: 'This hope is an ANCHOR for the soul, firm and secure.' },
      { r: 'HEB 11:1', n: 'Faith is the assurance of things hoped for — hope has substance.' },
      { r: '1PE 3:15', n: 'Always be ready to explain the hope in you — hope this solid gets noticed.' }
    ] },

  { id: 'heaven', cat: 'promises', icon: '🏙️', title: 'The Father’s House',
    tagline: 'A prepared place for prepared people.',
    intro: 'Heaven is not a mood or a metaphor — it is a place Jesus is preparing, with your name on a room. The thief on the cross made it in with nothing but faith.',
    verses: [
      { r: 'JOH 14:2', n: 'In My Father’s house are many rooms... I go to PREPARE A PLACE for you.' },
      { r: 'LUK 23:43', n: 'The thief had no baptism, no works, no time — only faith. "TODAY you will be with Me in Paradise."' },
      { r: '2CO 5:8', n: 'Absent from the body, present with the Lord — no waiting room.' },
      { r: 'PHP 1:23', n: 'Paul’s dilemma: to depart and be with Christ is BETTER BY FAR.' },
      { r: 'HEB 11:16', n: 'They desired a better country — and God has prepared a CITY for them.' },
      { r: '1PE 1:4', n: 'An inheritance imperishable, undefiled, unfading — kept in heaven FOR YOU.' },
      { r: 'REV 21:1', n: 'A new heaven and a new earth — the story ends with renewed creation, not clouds.' },
      { r: 'REV 22:4', n: 'They will SEE HIS FACE — the sight every believer was made for.' },
      { r: 'REV 22:5', n: 'No night, no lamp, no sun needed — the Lord God will be their light. And they will reign forever.' },
      { r: 'PSA 16:11', n: 'In Your presence is fullness of joy; at Your right hand, pleasures forevermore.' }
    ] },

  { id: 'never-alone', cat: 'promises', icon: '🌙', title: 'Never Alone',
    tagline: 'The promise stitched into every era of Scripture.',
    intro: 'To Jacob, to Moses, to Joshua, to the disciples, to you: I am with you. It is the promise God repeats most, because it is the one we forget fastest.',
    verses: [
      { r: 'GEN 28:15', n: 'To Jacob, on the run with nothing: behold, I am WITH YOU and will keep you.' },
      { r: 'EXO 33:14', n: 'My Presence will go with you, and I will give you rest.' },
      { r: 'DEU 31:6', n: 'He will never leave you nor forsake you — said to a nation, kept to individuals.' },
      { r: 'JOS 1:5', n: 'As I was with Moses, so I will be with you.' },
      { r: 'PSA 23:4', n: 'Even in the valley of the shadow of death: You are WITH me.' },
      { r: 'PSA 139:7', n: 'Where can I flee from Your presence? Nowhere — thankfully.' },
      { r: 'ISA 43:2', n: 'Through waters and fire alike: I will be with you.' },
      { r: 'MAT 28:20', n: 'The Great Commission’s engine: I am with you ALWAYS, to the end of the age.' },
      { r: 'JOH 14:18', n: 'I will not leave you as orphans — I will come to you.' },
      { r: 'HEB 13:5', n: 'The Greek stacks five negatives: I will NEVER, no never, forsake you.' }
    ] },

  // ═══ WISDOM FOR LIFE ═══
  { id: 'tongue', cat: 'wisdom', icon: '👅', title: 'Taming the Tongue',
    tagline: 'The smallest muscle with the biggest blast radius.',
    intro: 'Scripture treats words as loaded weapons and healing medicine — sometimes in the same sentence. Wisdom begins with a guarded mouth.',
    verses: [
      { r: 'PSA 19:14', n: 'The prayer standard: may the words of my mouth be pleasing to You.' },
      { r: 'PSA 141:3', n: 'Set a guard, O LORD, over my mouth — David asked for a doorkeeper.' },
      { r: 'PRO 12:18', n: 'Reckless words pierce like a sword; a wise tongue brings healing.' },
      { r: 'PRO 15:1', n: 'A gentle answer turns away wrath — de-escalation is ancient wisdom.' },
      { r: 'PRO 16:24', n: 'Pleasant words are a honeycomb: sweet to the soul, healing to the bones.' },
      { r: 'PRO 18:21', n: 'Death and LIFE are in the power of the tongue.' },
      { r: 'PRO 21:23', n: 'Guard your mouth, keep yourself out of trouble — the simplest equation in Proverbs.' },
      { r: 'ECC 5:2', n: 'God is in heaven, you are on earth — so let your words be FEW.' },
      { r: 'EPH 4:29', n: 'Only what builds up, fits the moment, and gives GRACE to those who hear.' },
      { r: 'COL 4:6', n: 'Speech seasoned with salt — flavorful, preserving, never bland or rotten.' },
      { r: 'JAM 1:19', n: 'Quick to listen, slow to speak, slow to anger — in that order.' },
      { r: 'JAM 3:5', n: 'A tiny spark, a great forest fire — James’s famous warning label.' }
    ] },

  { id: 'money', cat: 'wisdom', icon: '💰', title: 'Money & Contentment',
    tagline: 'A terrible master, a useful servant.',
    intro: 'The Bible talks about money constantly — not because God needs yours, but because Mammon competes for your heart. Contentment is the exit ramp.',
    verses: [
      { r: 'PRO 3:9', n: 'Honor the LORD with your wealth and the FIRSTfruits — He gets the top, not the leftovers.' },
      { r: 'PRO 22:7', n: 'The borrower is servant to the lender — debt has a leash.' },
      { r: 'PRO 30:8', n: 'The wisest budget request ever prayed: neither poverty nor riches.' },
      { r: 'ECC 5:10', n: 'Whoever loves money never has enough — the appetite grows with the feeding.' },
      { r: 'MAT 6:24', n: 'You CANNOT serve both God and money — Jesus rules out dual citizenship.' },
      { r: 'LUK 12:15', n: 'Life does not consist in the abundance of possessions.' },
      { r: 'PHP 4:11', n: 'Contentment is LEARNED — Paul took the course in plenty and in want.' },
      { r: '1TI 6:6', n: 'Godliness WITH contentment is great gain.' },
      { r: '1TI 6:10', n: 'The love of money — not money itself — is a root of all kinds of evil.' },
      { r: '1TI 6:17', n: 'To the rich: hope in God, who richly provides everything for our ENJOYMENT.' },
      { r: 'HEB 13:5', n: 'Keep free from the love of money, content with what you have — because HE stays.' }
    ] },

  { id: 'humility', cat: 'wisdom', icon: '🌾', title: 'The Way Down Is Up',
    tagline: 'God resists the proud — and cannot resist the humble.',
    intro: 'Pride is the one sin God actively opposes from a distance; humility is the doorstep He loves to visit. In His kingdom, the way up is always down.',
    verses: [
      { r: 'PRO 11:2', n: 'When pride comes, disgrace follows; with humility comes wisdom.' },
      { r: 'PRO 16:18', n: 'Pride goes before destruction — the most quoted safety warning in Scripture.' },
      { r: 'PRO 22:4', n: 'Humility and the fear of the LORD bring wealth, honor, and life.' },
      { r: 'PRO 27:2', n: 'Let another praise you — and not your own mouth.' },
      { r: 'ISA 66:2', n: 'The one God esteems: humble, contrite in spirit, trembling at His word.' },
      { r: 'MIC 6:8', n: 'What the LORD requires: act justly, love mercy, walk HUMBLY with your God.' },
      { r: 'MAT 23:12', n: 'Jesus’ law of gravity: the self-exalted fall; the humble get lifted.' },
      { r: 'PHP 2:5', n: 'Have this mind among yourselves — which was also in Christ Jesus.' },
      { r: 'PHP 2:8', n: 'He humbled Himself — obedient to death, even death on a cross.' },
      { r: 'JAM 4:6', n: 'God OPPOSES the proud but GIVES GRACE to the humble.' },
      { r: 'JAM 4:10', n: 'Humble yourselves before the Lord, and He will exalt you.' },
      { r: '1PE 5:6', n: 'Humble yourselves under His mighty hand — He does the lifting, in HIS time.' }
    ] },

  { id: 'fear-of-lord', cat: 'wisdom', icon: '🌌', title: 'The Fear of the LORD',
    tagline: 'Where all real wisdom begins.',
    intro: 'Not cringing terror — reverent awe that takes God seriously. Scripture calls it the beginning of wisdom, a fountain of life, and strangely: a thing to be taught.',
    verses: [
      { r: 'JOB 28:28', n: 'God’s answer to "where is wisdom found?": the fear of the Lord — THAT is wisdom.' },
      { r: 'PSA 34:11', n: 'Come, children, listen — I will TEACH you the fear of the LORD. It can be learned.' },
      { r: 'PSA 111:10', n: 'The fear of the LORD is the beginning of wisdom.' },
      { r: 'PRO 1:7', n: 'The beginning of knowledge too — fools despise wisdom and instruction.' },
      { r: 'PRO 9:10', n: 'And knowledge of the Holy One is understanding.' },
      { r: 'PRO 14:26', n: 'In the fear of the LORD is STRONG CONFIDENCE — awe of God shrinks every other fear.' },
      { r: 'PRO 14:27', n: 'A fountain of life, turning a person from the snares of death.' },
      { r: 'PRO 19:23', n: 'It leads to life: rest content, untouched by trouble.' },
      { r: 'ECC 12:13', n: 'The conclusion of the matter: fear God and keep His commandments.' },
      { r: 'ISA 33:6', n: 'The fear of the LORD is Zion’s TREASURE.' }
    ] },

  { id: 'guidance', cat: 'wisdom', icon: '🧭', title: 'A Lamp for the Path',
    tagline: 'God guides — usually one step at a time.',
    intro: 'A lamp to the feet lights the next step, not the next decade. God promises direction to those who trust, ask, and keep walking.',
    verses: [
      { r: 'PSA 25:9', n: 'He guides the humble in what is right and TEACHES them His way.' },
      { r: 'PSA 32:8', n: 'I will instruct you and teach you in the way you should go — with My eye on you.' },
      { r: 'PSA 37:23', n: 'The steps of a man are ordered by the LORD.' },
      { r: 'PSA 119:105', n: 'Your word: a lamp to my feet, a light to my path — step-sized illumination.' },
      { r: 'PRO 3:5', n: 'Trust in the LORD with ALL your heart; lean not on your own understanding.' },
      { r: 'PRO 3:6', n: 'In all your ways acknowledge Him, and He will make your paths straight.' },
      { r: 'PRO 15:22', n: 'Plans fail without counsel — wisdom asks for input.' },
      { r: 'PRO 16:9', n: 'The heart plans the course; the LORD establishes the steps. Both are real.' },
      { r: 'ISA 30:21', n: 'A voice behind you: "This is the way; walk in it."' },
      { r: 'JAM 1:5', n: 'Short on wisdom? ASK — God gives generously, without finding fault.' }
    ] },

  { id: 'friendship', cat: 'wisdom', icon: '⚔️', title: 'Iron Sharpens Iron',
    tagline: 'Jonathan strengthened David’s hand in God.',
    intro: 'The Bible’s picture of friendship has edges: iron on iron, faithful wounds, a friend for adversity. Choose companions who point you God-ward.',
    verses: [
      { r: '1SA 18:1', n: 'Jonathan’s soul was knit to David’s — covenant friendship begins.' },
      { r: '1SA 23:16', n: 'The best one-verse job description of a friend: he strengthened his hand IN GOD.' },
      { r: 'PRO 13:20', n: 'Walk with the wise and become wise — company is contagious.' },
      { r: 'PRO 17:17', n: 'A friend loves at ALL times; a brother is born for adversity.' },
      { r: 'PRO 18:24', n: 'There is a friend who sticks closer than a brother.' },
      { r: 'PRO 27:6', n: 'Faithful are the WOUNDS of a friend — flattery is the enemy’s kiss.' },
      { r: 'PRO 27:9', n: 'The sweetness of a friend comes from his earnest counsel.' },
      { r: 'PRO 27:17', n: 'As iron sharpens iron, so one man sharpens another.' },
      { r: 'ECC 4:9', n: 'Two are better than one — a good return for their labor.' },
      { r: 'ECC 4:12', n: 'A cord of three strands is not quickly broken.' },
      { r: 'JOH 15:13', n: 'The ceiling of friendship: laying down one’s life. Jesus met it.' }
    ] },

  // ═══ THE BIG STORY ═══
  { id: 'covenants', cat: 'story', icon: '🌈', title: 'The Covenants',
    tagline: 'God’s promises are the skeleton of the whole Bible.',
    intro: 'Read literally, the Bible is structured by covenants — and the weight-bearing ones are UNCONDITIONAL: God alone walked between the pieces. History is those promises coming true on schedule.',
    verses: [
      { r: 'GEN 9:13', n: 'Noahic: the rainbow — a covenant with all the earth, still in force.' },
      { r: 'GEN 12:2', n: 'Abrahamic: a great nation, a great name, and blessing...' },
      { r: 'GEN 12:3', n: '...for ALL families of the earth through Abraham’s Seed.' },
      { r: 'GEN 15:17', n: 'God passed between the pieces ALONE — He signed both lines. Unconditional.' },
      { r: 'GEN 15:18', n: 'The land grant, with borders — a deed, not a metaphor.' },
      { r: '2SA 7:16', n: 'Davidic: your house, kingdom, and throne established FOREVER.' },
      { r: 'PSA 89:34', n: 'God’s policy: I will not violate My covenant or alter the word from My lips.' },
      { r: 'JER 31:31', n: 'The New Covenant announced — with the house of Israel and Judah.' },
      { r: 'JER 31:34', n: 'Its core clause: I will remember their sins NO MORE.' },
      { r: 'LUK 22:20', n: 'The cup: "the new covenant in My blood" — signed at the cross.' },
      { r: 'HEB 8:6', n: 'Jesus mediates a BETTER covenant, enacted on better promises.' }
    ] },

  { id: 'israel', cat: 'story', icon: '🇮🇱', title: 'Promises That Stand: Israel',
    tagline: 'Gifts and calling God never revokes.',
    intro: 'Read the promises to Israel plainly and they are national, territorial, and permanent. Paul asks the question directly — has God rejected His people? — and answers it himself: absolutely not.',
    verses: [
      { r: 'GEN 17:7', n: 'An EVERLASTING covenant with Abraham’s offspring through their generations.' },
      { r: 'GEN 17:8', n: 'The land of Canaan: an everlasting possession — God’s own word choice.' },
      { r: 'DEU 7:6', n: 'A people holy to the LORD, chosen as His treasured possession.' },
      { r: 'PSA 122:6', n: 'A standing invitation: pray for the peace of Jerusalem.' },
      { r: 'ISA 11:11', n: 'A SECOND regathering foretold — from all the nations.' },
      { r: 'JER 31:36', n: 'Only if the sun and moon quit will Israel cease to be a nation before God.' },
      { r: 'EZK 36:24', n: 'I will take you from the nations and bring you back to your own land.' },
      { r: 'AMO 9:14', n: 'Cities rebuilt, vineyards planted — restoration in concrete terms.' },
      { r: 'AMO 9:15', n: 'Planted, NEVER AGAIN to be uprooted from the land I have given them.' },
      { r: 'ROM 11:1', n: 'Paul’s question and answer: Did God reject His people? Certainly not!' },
      { r: 'ROM 11:26', n: 'And so all Israel will be saved — a future as literal as the past.' },
      { r: 'ROM 11:29', n: 'The principle under it all: God’s gifts and calling are IRREVOCABLE.' }
    ] },

  { id: 'church', cat: 'story', icon: '⛪', title: 'One Body, Many Members',
    tagline: 'Something new began at Pentecost.',
    intro: 'The Church is not a renamed Israel — it is a new creation: Jew and Gentile baptized by one Spirit into one body, with the risen Christ as Head.',
    verses: [
      { r: 'MAT 16:18', n: 'Future tense: "I WILL build My church" — still unbuilt when Jesus spoke.' },
      { r: 'ACT 2:41', n: 'Day one: three thousand souls added.' },
      { r: 'ACT 2:42', n: 'The four devotions: teaching, fellowship, breaking of bread, prayer.' },
      { r: '1CO 12:13', n: 'By ONE Spirit we were ALL baptized into ONE body — Jew or Greek.' },
      { r: '1CO 12:27', n: 'You are the body of Christ, and individually members of it.' },
      { r: 'EPH 1:22', n: 'Christ: head over everything FOR the church.' },
      { r: 'EPH 2:20', n: 'Built on the apostles and prophets, Christ Jesus Himself the cornerstone.' },
      { r: 'EPH 4:16', n: 'The whole body grows as EACH part does its work — no spectator members.' },
      { r: 'COL 1:18', n: 'He is the head of the body, the church — preeminent in everything.' },
      { r: 'HEB 10:24', n: 'Consider how to spur one another on toward love and good deeds.' },
      { r: 'HEB 10:25', n: 'Do not neglect meeting together — all the more as the Day approaches.' },
      { r: '1PE 2:5', n: 'Living stones, being built into a spiritual house.' }
    ] },

  { id: 'kingdom', cat: 'story', icon: '🦁', title: 'The Kingdom Yet to Come',
    tagline: 'Swords to plowshares — read it straight.',
    intro: 'Taken at face value, the prophets describe a real earthly reign: David’s throne occupied, nations at peace, creation tamed. Jesus taught us to keep praying for it — because it is still coming.',
    verses: [
      { r: 'ISA 2:4', n: 'Swords into plowshares; nations learn war NO MORE — unfulfilled, so still future.' },
      { r: 'ISA 11:6', n: 'The wolf lives with the lamb — creation’s ceasefire.' },
      { r: 'ISA 11:9', n: 'The earth FULL of the knowledge of the LORD as waters cover the sea.' },
      { r: 'DAN 2:44', n: 'A kingdom set up by the God of heaven that will NEVER be destroyed.' },
      { r: 'DAN 7:14', n: 'The Son of Man receives dominion, glory, and a kingdom — all peoples serve Him.' },
      { r: 'ZEC 14:9', n: 'The LORD will be KING over all the earth — one LORD, one name.' },
      { r: 'LUK 1:32', n: 'Gabriel’s terms to Mary: the throne of His father DAVID — a literal throne.' },
      { r: 'LUK 1:33', n: 'He will reign over the house of Jacob forever; His kingdom will never end.' },
      { r: 'MAT 6:10', n: '"Your kingdom come" — Jesus had us pray it because it had not yet arrived.' },
      { r: 'REV 11:15', n: 'The kingdom of the world BECOMES the kingdom of our Lord and of His Christ.' },
      { r: 'REV 20:6', n: 'They will reign with Him for a thousand years — stated six times in the chapter.' }
    ] },

  { id: 'garden-to-city', cat: 'story', icon: '🌳', title: 'From Garden to City',
    tagline: 'The Bible ends where it began — only better.',
    intro: 'Genesis opens in a garden with a tree of life; Revelation closes in a garden-city with the same tree, now lining a river. Everything between is God winning it back.',
    verses: [
      { r: 'GEN 1:31', n: 'The starting point: God saw ALL He had made — very good.' },
      { r: 'GEN 2:9', n: 'The tree of life in the middle of the garden — remember it.' },
      { r: 'GEN 3:24', n: 'Paradise lost: cherubim and a flaming sword bar the way to the tree.' },
      { r: 'ISA 51:3', n: 'The promise of reversal: her wilderness made like EDEN.' },
      { r: 'ROM 8:21', n: 'Creation itself will be liberated from its bondage to decay.' },
      { r: '2PE 3:13', n: 'We await new heavens and a new earth, where righteousness dwells.' },
      { r: 'REV 2:7', n: 'To the overcomer: the right to eat from the tree of life — it survived the Fall.' },
      { r: 'REV 21:2', n: 'The holy city, new Jerusalem, coming down out of heaven — a garden-city.' },
      { r: 'REV 21:5', n: 'From the throne: "Behold, I make ALL things new."' },
      { r: 'REV 22:1', n: 'A river of the water of life, clear as crystal, from the throne.' },
      { r: 'REV 22:2', n: 'And there it is again: the tree of life — its leaves for the healing of the nations.' }
    ] },

  { id: 'word', cat: 'story', icon: '📖', title: 'The Living Word',
    tagline: 'What the Bible says about itself.',
    intro: 'Scripture claims to be breathed out by God, flawless, eternal, and alive — sharper than any sword. This thread lets the Book testify in its own defense.',
    verses: [
      { r: 'DEU 8:3', n: 'Man lives on every word from the mouth of the LORD — food for the soul.' },
      { r: 'MAT 4:4', n: 'Jesus wields that very verse against the tempter: "It is written."' },
      { r: 'JOS 1:8', n: 'Meditate on it day and night — then you will prosper and succeed.' },
      { r: 'PSA 1:2', n: 'The blessed man’s delight and constant meditation: the law of the LORD.' },
      { r: 'PSA 19:7', n: 'The law of the LORD is PERFECT, reviving the soul.' },
      { r: 'PSA 119:11', n: 'Hidden in the heart — the word as sin’s vaccine.' },
      { r: 'PSA 119:160', n: 'The SUM of Your word is truth — all of it, added together.' },
      { r: 'ISA 40:8', n: 'Grass withers, flowers fall — the word of our God stands FOREVER.' },
      { r: 'ISA 55:11', n: 'It never returns empty; it accomplishes what He purposes.' },
      { r: 'JER 15:16', n: 'Jeremiah ATE the words — and they became his heart’s joy.' },
      { r: '2TI 3:16', n: 'ALL Scripture is God-breathed — profitable for teaching, correcting, training.' },
      { r: 'HEB 4:12', n: 'Living and active, sharper than any double-edged sword.' },
      { r: 'JAM 1:22', n: 'Be DOERS of the word, and not hearers only.' }
    ] }
  ]
};
