/* ============================================================================
   BIBLE ATLAS — a gazetteer of biblical places for the Atlas pin map.

   Each entry: { name (biblical), modern (today's location/reference), lat, lon,
   kind, note, refs }. Coordinates are the place's best-known site; some places
   (e.g. Tarshish, Sheba) sit beyond the detailed tile area and the UI shows the
   modern reference instead of a live pin. The tile coverage is lon 9–48, lat
   24–43; the UI flags anything outside that.

   This list grows toward covering nearly every locatable place in Scripture.
   ========================================================================== */
window.BIBLE_ATLAS = [
  // ── Jerusalem & Judah ──
  { name:'Jerusalem', modern:'Jerusalem, Israel', lat:31.78, lon:35.23, kind:'city', note:'The City of David and site of the temple; capital of Judah.', refs:['2 Samuel 5:7','Psalms 122:6'] },
  { name:'Mount Zion', modern:'Jerusalem (southern hill)', lat:31.77, lon:35.23, kind:'mountain', note:'The hill of the City of David, often a name for Jerusalem itself.', refs:['Psalms 48:2','Isaiah 2:3'] },
  { name:'Mount Moriah', modern:'Temple Mount, Jerusalem', lat:31.778, lon:35.235, kind:'mountain', note:'Where Abraham bound Isaac and Solomon built the temple.', refs:['Genesis 22:2','2 Chronicles 3:1'] },
  { name:'Mount of Olives', modern:'East of Jerusalem', lat:31.77, lon:35.25, kind:'mountain', note:'Ridge east of Jerusalem; Jesus taught, prayed, and ascended here.', refs:['Zechariah 14:4','Acts 1:12'] },
  { name:'Gethsemane', modern:'Mount of Olives, Jerusalem', lat:31.779, lon:35.24, kind:'site', note:'The garden where Jesus prayed before his arrest.', refs:['Matthew 26:36'] },
  { name:'Golgotha', modern:'Jerusalem (Holy Sepulchre)', lat:31.778, lon:35.23, kind:'site', note:'"The place of a skull," where Jesus was crucified.', refs:['John 19:17'] },
  { name:'Pool of Siloam', modern:'Jerusalem (City of David)', lat:31.77, lon:35.235, kind:'site', note:'Pool where Jesus sent the blind man to wash.', refs:['John 9:7'] },
  { name:'Kidron Valley', modern:'East of Jerusalem', lat:31.78, lon:35.24, kind:'valley', note:'Ravine between Jerusalem and the Mount of Olives.', refs:['2 Samuel 15:23','John 18:1'] },
  { name:'Valley of Hinnom', modern:'South of Jerusalem', lat:31.77, lon:35.225, kind:'valley', note:'Gehenna; a valley of idolatry that became an image of judgment.', refs:['Jeremiah 7:31'] },
  { name:'Bethlehem', modern:'Bethlehem, West Bank', lat:31.70, lon:35.20, kind:'city', note:'City of David and birthplace of Jesus.', refs:['Micah 5:2','Luke 2:4'] },
  { name:'Hebron', modern:'Hebron, West Bank', lat:31.53, lon:35.10, kind:'city', note:'Patriarchs buried at Machpelah; David first reigned here.', refs:['Genesis 23:19','2 Samuel 2:11'] },
  { name:'Machpelah', modern:'Hebron', lat:31.524, lon:35.111, kind:'site', note:'The cave Abraham bought as a burial place for Sarah.', refs:['Genesis 23:9'] },
  { name:'Mamre', modern:'Near Hebron', lat:31.55, lon:35.10, kind:'site', note:'The oaks where Abraham camped and met the three visitors.', refs:['Genesis 18:1'] },
  { name:'Beersheba', modern:'Beersheba, Israel', lat:31.25, lon:34.79, kind:'city', note:'Southern edge of the land; "from Dan to Beersheba."', refs:['Genesis 21:31','Judges 20:1'] },
  { name:'Tekoa', modern:'Tuqu, West Bank', lat:31.65, lon:35.21, kind:'city', note:'Home of the prophet Amos, in the Judean wilderness.', refs:['Amos 1:1'] },
  { name:'En-gedi', modern:'Ein Gedi, Dead Sea', lat:31.46, lon:35.39, kind:'site', note:'Oasis by the Dead Sea where David hid from Saul.', refs:['1 Samuel 24:1'] },
  { name:'Adullam', modern:'Shephelah, Israel', lat:31.65, lon:34.96, kind:'site', note:'The cave where David gathered his men.', refs:['1 Samuel 22:1'] },
  { name:'Lachish', modern:'Tel Lachish, Israel', lat:31.56, lon:34.85, kind:'city', note:'Fortified Judean city besieged by Assyria and Babylon.', refs:['2 Kings 18:14'] },
  { name:'Valley of Elah', modern:'Wadi es-Sunt', lat:31.69, lon:34.96, kind:'valley', note:'Where David faced Goliath.', refs:['1 Samuel 17:2'] },
  { name:'Mareshah', modern:'Tel Maresha', lat:31.59, lon:34.90, kind:'city', note:'Judean city where Asa met Zerah the Cushite.', refs:['2 Chronicles 14:9'] },
  { name:'Ziph', modern:'Tel Ziph', lat:31.45, lon:35.12, kind:'site', note:'Wilderness where David hid and the Ziphites betrayed him.', refs:['1 Samuel 23:14'] },
  { name:'Maon', modern:'Tell Main', lat:31.40, lon:35.13, kind:'site', note:'Wilderness of Nabal and Abigail.', refs:['1 Samuel 25:2'] },
  { name:'Bethel', modern:'Beitin, West Bank', lat:31.93, lon:35.22, kind:'city', note:'Jacob’s ladder; later a center of Jeroboam’s calf worship.', refs:['Genesis 28:19','1 Kings 12:29'] },
  { name:'Ai', modern:'Et-Tell area', lat:31.92, lon:35.26, kind:'city', note:'City taken after Achan’s sin.', refs:['Joshua 8:1'] },
  { name:'Gibeon', modern:'El-Jib, West Bank', lat:31.85, lon:35.18, kind:'city', note:'Where the sun stood still and Solomon sought wisdom.', refs:['Joshua 10:12','1 Kings 3:4'] },
  { name:'Gibeah', modern:'Tell el-Ful', lat:31.82, lon:35.23, kind:'city', note:'Saul’s hometown and capital.', refs:['1 Samuel 10:26'] },
  { name:'Ramah', modern:'Er-Ram, West Bank', lat:31.87, lon:35.20, kind:'city', note:'Home of Samuel; later associated with the exile’s weeping.', refs:['1 Samuel 7:17','Jeremiah 31:15'] },
  { name:'Mizpah', modern:'Tell en-Nasbeh', lat:31.83, lon:35.18, kind:'city', note:'Place of assembly; Samuel’s Ebenezer victory.', refs:['1 Samuel 7:5'] },
  { name:'Gilgal', modern:'Jordan valley near Jericho', lat:31.87, lon:35.50, kind:'site', note:'Israel’s first camp west of the Jordan.', refs:['Joshua 4:19'] },
  { name:'Jericho', modern:'Jericho, West Bank', lat:31.87, lon:35.44, kind:'city', note:'City of Palms; its walls fell before Israel.', refs:['Joshua 6:20','Luke 19:1'] },
  { name:'Bethany', modern:'Al-Eizariya, West Bank', lat:31.77, lon:35.26, kind:'village', note:'Home of Mary, Martha, and Lazarus near Jerusalem.', refs:['John 11:1'] },
  { name:'Ephraim (town)', modern:'Et-Taiyibeh', lat:31.95, lon:35.30, kind:'town', note:'Town near the wilderness where Jesus withdrew.', refs:['John 11:54'] },
  { name:'Emmaus', modern:'Judean hills (debated)', lat:31.84, lon:35.02, kind:'village', note:'Where the risen Jesus walked with two disciples.', refs:['Luke 24:13'] },
  { name:'Gezer', modern:'Tel Gezer', lat:31.86, lon:34.92, kind:'city', note:'Border city given to Solomon as a dowry.', refs:['1 Kings 9:16'] },
  { name:'Kiriath-jearim', modern:'Judean hills', lat:31.81, lon:35.10, kind:'town', note:'Where the ark rested for twenty years.', refs:['1 Samuel 7:1'] },
  // ── Coast & Philistia ──
  { name:'Joppa', modern:'Jaffa, Israel', lat:32.05, lon:34.75, kind:'city', note:'Port where Jonah fled and Peter saw his vision.', refs:['Jonah 1:3','Acts 9:36'] },
  { name:'Lydda', modern:'Lod, Israel', lat:31.95, lon:34.89, kind:'city', note:'Where Peter healed Aeneas.', refs:['Acts 9:32'] },
  { name:'Caesarea', modern:'Caesarea, Israel', lat:32.50, lon:34.89, kind:'city', note:'Roman provincial capital on the coast.', refs:['Acts 10:1','Acts 23:23'] },
  { name:'Gaza', modern:'Gaza', lat:31.50, lon:34.47, kind:'city', note:'Philistine city; Samson carried off its gates.', refs:['Judges 16:1'] },
  { name:'Ashkelon', modern:'Ashkelon, Israel', lat:31.67, lon:34.57, kind:'city', note:'One of the five Philistine cities.', refs:['Judges 14:19'] },
  { name:'Ashdod', modern:'Ashdod, Israel', lat:31.80, lon:34.65, kind:'city', note:'Philistine city; the ark and Dagon. Later Azotus.', refs:['1 Samuel 5:1','Acts 8:40'] },
  { name:'Ekron', modern:'Tel Miqne', lat:31.78, lon:34.85, kind:'city', note:'Northernmost Philistine city.', refs:['1 Samuel 5:10'] },
  { name:'Gath', modern:'Tell es-Safi', lat:31.70, lon:34.85, kind:'city', note:'Home of Goliath; David fled here.', refs:['1 Samuel 21:10'] },
  { name:'Beth-shemesh', modern:'Tel Beit Shemesh', lat:31.75, lon:34.98, kind:'city', note:'Where the ark returned from Philistine country.', refs:['1 Samuel 6:12'] },
  { name:'Timnah', modern:'Tel Batash', lat:31.79, lon:34.91, kind:'town', note:'Philistine town of Samson’s wife.', refs:['Judges 14:1'] },
  { name:'Zorah', modern:'Tzora, Israel', lat:31.77, lon:34.98, kind:'town', note:'Samson’s hometown.', refs:['Judges 13:2'] },
  { name:'Ziklag', modern:'Western Negev', lat:31.30, lon:34.62, kind:'town', note:'Town given to David by the Philistines.', refs:['1 Samuel 27:6'] },
  { name:'Gerar', modern:'Tel Haror', lat:31.40, lon:34.58, kind:'city', note:'Philistine region where Abraham and Isaac sojourned.', refs:['Genesis 20:1','Genesis 26:1'] },
  // ── Galilee & the north ──
  { name:'Nazareth', modern:'Nazareth, Israel', lat:32.70, lon:35.30, kind:'town', note:'Where Jesus grew up.', refs:['Luke 1:26','Luke 4:16'] },
  { name:'Cana', modern:'Khirbet Qana, Galilee', lat:32.81, lon:35.34, kind:'village', note:'Where Jesus turned water into wine.', refs:['John 2:1'] },
  { name:'Capernaum', modern:'Capernaum, Sea of Galilee', lat:32.88, lon:35.575, kind:'town', note:'Jesus’ base in Galilee.', refs:['Matthew 4:13'] },
  { name:'Bethsaida', modern:'Et-Tell, N. of the lake', lat:32.91, lon:35.63, kind:'town', note:'Home of Peter, Andrew, and Philip.', refs:['John 1:44'] },
  { name:'Chorazin', modern:'Korazim, Galilee', lat:32.91, lon:35.56, kind:'town', note:'Town rebuked by Jesus for unbelief.', refs:['Matthew 11:21'] },
  { name:'Nain', modern:'Nein, Israel', lat:32.64, lon:35.35, kind:'village', note:'Where Jesus raised a widow’s son.', refs:['Luke 7:11'] },
  { name:'Tiberias', modern:'Tiberias, Israel', lat:32.79, lon:35.53, kind:'city', note:'City on the Sea of Galilee, which bears its name.', refs:['John 6:23'] },
  { name:'Gennesaret', modern:'Ginosar plain', lat:32.83, lon:35.52, kind:'region', note:'Fertile plain on the northwest shore of Galilee.', refs:['Matthew 14:34'] },
  { name:'Gergesa (Gerasenes)', modern:'Kursi, east shore', lat:32.83, lon:35.65, kind:'site', note:'Where Jesus freed a demon-possessed man.', refs:['Mark 5:1'] },
  { name:'Caesarea Philippi', modern:'Banias, Golan', lat:33.25, lon:35.69, kind:'city', note:'Where Peter confessed Jesus as the Christ.', refs:['Matthew 16:13'] },
  { name:'Nazareth’s Mount Tabor', modern:'Mount Tabor, Israel', lat:32.69, lon:35.39, kind:'mountain', note:'Deborah’s muster; a traditional Transfiguration site.', refs:['Judges 4:6'] },
  { name:'Mount Carmel', modern:'Mount Carmel, Israel', lat:32.73, lon:35.05, kind:'mountain', note:'Where Elijah faced the prophets of Baal.', refs:['1 Kings 18:20'] },
  { name:'Jezreel', modern:'Tel Yizre’el', lat:32.56, lon:35.33, kind:'city', note:'Royal city of Ahab; Jehu’s purge.', refs:['1 Kings 21:1'] },
  { name:'Megiddo', modern:'Tel Megiddo', lat:32.58, lon:35.18, kind:'city', note:'Strategic pass; Josiah died here. Armageddon.', refs:['2 Kings 23:29','Revelation 16:16'] },
  { name:'Mount Gilboa', modern:'Mount Gilboa, Israel', lat:32.46, lon:35.42, kind:'mountain', note:'Where Saul and Jonathan fell.', refs:['1 Samuel 31:1'] },
  { name:'Beth-shan', modern:'Beit She’an', lat:32.50, lon:35.50, kind:'city', note:'Where Saul’s body was hung on the wall.', refs:['1 Samuel 31:10'] },
  { name:'Shunem', modern:'Sulam, Israel', lat:32.60, lon:35.34, kind:'town', note:'Home of the woman who hosted Elisha.', refs:['2 Kings 4:8'] },
  { name:'Endor', modern:'Ein Dor area', lat:32.64, lon:35.40, kind:'town', note:'Where Saul consulted a medium.', refs:['1 Samuel 28:7'] },
  { name:'Dothan', modern:'Tel Dotan', lat:32.41, lon:35.22, kind:'town', note:'Joseph sold here; Elisha’s chariots of fire.', refs:['Genesis 37:17','2 Kings 6:13'] },
  { name:'Shechem', modern:'Nablus, West Bank', lat:32.21, lon:35.28, kind:'city', note:'Covenant city between Ebal and Gerizim.', refs:['Genesis 12:6','Joshua 24:1'] },
  { name:'Mount Gerizim', modern:'Near Nablus', lat:32.20, lon:35.27, kind:'mountain', note:'Mount of blessing; Samaritan worship.', refs:['Deuteronomy 11:29','John 4:20'] },
  { name:'Mount Ebal', modern:'Near Nablus', lat:32.23, lon:35.27, kind:'mountain', note:'Mount of cursing where Joshua built an altar.', refs:['Joshua 8:30'] },
  { name:'Sychar', modern:'Near Nablus', lat:32.21, lon:35.28, kind:'village', note:'Samaritan town at Jacob’s well.', refs:['John 4:5'] },
  { name:'Samaria', modern:'Sebastia, West Bank', lat:32.28, lon:35.19, kind:'city', note:'Capital of the northern kingdom.', refs:['1 Kings 16:24'] },
  { name:'Shiloh', modern:'Khirbet Seilun', lat:32.06, lon:35.29, kind:'town', note:'Home of the tabernacle before the temple.', refs:['Joshua 18:1','1 Samuel 1:3'] },
  { name:'Thebez', modern:'Tubas, West Bank', lat:32.32, lon:35.37, kind:'town', note:'Where a millstone killed Abimelech.', refs:['Judges 9:50'] },
  { name:'Tirzah', modern:'Tell el-Far’ah N.', lat:32.28, lon:35.30, kind:'city', note:'Early capital of the northern kingdom.', refs:['1 Kings 14:17'] },
  { name:'Dan', modern:'Tel Dan, Israel', lat:33.25, lon:35.65, kind:'city', note:'Northern limit of the land; Jeroboam’s calf.', refs:['Judges 18:29','1 Kings 12:29'] },
  { name:'Hazor', modern:'Tel Hazor', lat:33.02, lon:35.57, kind:'city', note:'Great northern city Joshua burned.', refs:['Joshua 11:10'] },
  { name:'Kedesh', modern:'Tel Kedesh, Galilee', lat:33.11, lon:35.53, kind:'city', note:'City of refuge; Barak’s home.', refs:['Joshua 20:7','Judges 4:6'] },
  { name:'Abel-beth-maacah', modern:'Tel Abel, N. Israel', lat:33.26, lon:35.58, kind:'city', note:'Far-northern city where a wise woman ended a siege.', refs:['2 Samuel 20:14'] },
  { name:'Mount Hermon', modern:'Hermon range', lat:33.42, lon:35.86, kind:'mountain', note:'Snow-capped peak at the land’s northern edge.', refs:['Psalms 133:3'] },
  // ── Transjordan ──
  { name:'Mahanaim', modern:'Gilead, Jordan', lat:32.20, lon:35.72, kind:'town', note:'Where angels met Jacob; David’s refuge from Absalom.', refs:['Genesis 32:2','2 Samuel 17:24'] },
  { name:'Penuel (Peniel)', modern:'Jabbok river, Jordan', lat:32.10, lon:35.62, kind:'site', note:'Where Jacob wrestled with God.', refs:['Genesis 32:30'] },
  { name:'Succoth (east)', modern:'Jordan valley, Jordan', lat:32.20, lon:35.57, kind:'town', note:'Where Jacob built shelters after Peniel.', refs:['Genesis 33:17'] },
  { name:'Jabesh-gilead', modern:'Gilead, Jordan', lat:32.45, lon:35.65, kind:'town', note:'Rescued by Saul; recovered his body.', refs:['1 Samuel 11:1'] },
  { name:'Ramoth-gilead', modern:'Gilead, Jordan', lat:32.60, lon:35.85, kind:'city', note:'Contested city; Ahab died and Jehu was anointed here.', refs:['1 Kings 22:3','2 Kings 9:1'] },
  { name:'Heshbon', modern:'Hisban, Jordan', lat:31.80, lon:35.81, kind:'city', note:'Capital of King Sihon of the Amorites.', refs:['Numbers 21:26'] },
  { name:'Mount Nebo', modern:'Mount Nebo, Jordan', lat:31.77, lon:35.73, kind:'mountain', note:'Where Moses saw the Promised Land and died.', refs:['Deuteronomy 34:1'] },
  { name:'Rabbah', modern:'Amman, Jordan', lat:31.95, lon:35.93, kind:'city', note:'Capital of the Ammonites.', refs:['2 Samuel 12:26'] },
  { name:'Edrei', modern:'Daraa, Syria', lat:32.79, lon:36.27, kind:'city', note:'Where Israel defeated Og of Bashan.', refs:['Numbers 21:33'] },
  { name:'Kir-hareseth', modern:'Kerak, Jordan', lat:31.07, lon:35.75, kind:'city', note:'Moabite stronghold besieged by three kings.', refs:['2 Kings 3:25'] },
  { name:'Aroer', modern:'Arnon gorge, Jordan', lat:31.46, lon:35.83, kind:'town', note:'Town on the rim of the Arnon, southern border.', refs:['Deuteronomy 2:36'] },
  { name:'Machaerus', modern:'Mukawir, Jordan', lat:31.57, lon:35.62, kind:'fortress', note:'Herod’s fortress where John the Baptist was beheaded.', refs:['Mark 6:27'] },
  { name:'Mount Pisgah', modern:'Near Mount Nebo', lat:31.77, lon:35.72, kind:'mountain', note:'The ridge of Nebo overlooking the Jordan.', refs:['Numbers 21:20'] },
  // ── Wilderness & the south ──
  { name:'Kadesh-barnea', modern:'Wilderness of Zin', lat:30.65, lon:34.50, kind:'site', note:'Where Israel sent the twelve spies and rebelled.', refs:['Numbers 13:26'] },
  { name:'Mount Sinai (Horeb)', modern:'Sinai Peninsula', lat:28.54, lon:33.97, kind:'mountain', note:'Where God gave the Law to Moses.', refs:['Exodus 19:20'] },
  { name:'Rephidim', modern:'Sinai wilderness', lat:28.72, lon:33.60, kind:'site', note:'Water from the rock; battle with Amalek.', refs:['Exodus 17:1'] },
  { name:'Elim', modern:'Sinai coast', lat:29.20, lon:33.00, kind:'site', note:'Oasis of twelve springs and seventy palms.', refs:['Exodus 15:27'] },
  { name:'Marah', modern:'Sinai coast', lat:29.60, lon:33.10, kind:'site', note:'Where bitter water was made sweet.', refs:['Exodus 15:23'] },
  { name:'Hazeroth', modern:'Sinai wilderness', lat:29.40, lon:34.60, kind:'site', note:'Camp where Miriam was struck with leprosy.', refs:['Numbers 11:35'] },
  { name:'Ezion-geber', modern:'Eilat / Aqaba', lat:29.55, lon:34.95, kind:'port', note:'Red Sea port for Solomon’s fleet.', refs:['1 Kings 9:26'] },
  { name:'Mount Hor', modern:'Edom border', lat:30.30, lon:35.40, kind:'mountain', note:'Where Aaron died.', refs:['Numbers 20:28'] },
  { name:'Sela (Petra)', modern:'Petra, Jordan', lat:30.33, lon:35.44, kind:'city', note:'Rock-fortress of Edom.', refs:['2 Kings 14:7'] },
  { name:'Zoar', modern:'S. Dead Sea, Jordan', lat:31.05, lon:35.50, kind:'town', note:'The little town Lot fled to from Sodom.', refs:['Genesis 19:22'] },
  { name:'Sodom', modern:'Southern Dead Sea plain', lat:31.05, lon:35.40, kind:'city', note:'City of the plain destroyed by fire.', refs:['Genesis 19:24'] },
  { name:'Gomorrah', modern:'Southern Dead Sea plain', lat:31.04, lon:35.42, kind:'city', note:'City destroyed with Sodom.', refs:['Genesis 19:24'] },
  { name:'Arad', modern:'Tel Arad, Negev', lat:31.28, lon:35.13, kind:'city', note:'Canaanite city of the Negev.', refs:['Numbers 21:1'] },
  // ── Rivers, seas & valleys ──
  { name:'Jordan River', modern:'Jordan Valley', lat:32.20, lon:35.57, kind:'river', note:'The river of crossing, baptism, and many miracles.', refs:['Joshua 3:17','Matthew 3:13'] },
  { name:'Sea of Galilee', modern:'Lake Kinneret', lat:32.82, lon:35.59, kind:'lake', note:'Freshwater lake of much of Jesus’ ministry.', refs:['Matthew 4:18'] },
  { name:'Dead Sea (Salt Sea)', modern:'Dead Sea', lat:31.30, lon:35.47, kind:'lake', note:'The salt sea at the lowest point on earth.', refs:['Genesis 14:3'] },
  { name:'Jabbok River', modern:'Zarqa River, Jordan', lat:32.10, lon:35.62, kind:'river', note:'Where Jacob wrestled with God.', refs:['Genesis 32:22'] },
  { name:'Arnon River', modern:'Wadi Mujib, Jordan', lat:31.46, lon:35.58, kind:'river', note:'Border between Moab and the Amorites.', refs:['Numbers 21:13'] },
  { name:'Kishon River', modern:'Jezreel valley', lat:32.59, lon:35.22, kind:'river', note:'Swept away Sisera’s army; Elijah’s judgment.', refs:['Judges 5:21'] },
  { name:'Brook Cherith', modern:'East of the Jordan', lat:32.05, lon:35.50, kind:'river', note:'Where ravens fed Elijah.', refs:['1 Kings 17:3'] },
  { name:'Brook Besor', modern:'Nahal Besor, Negev', lat:31.22, lon:34.45, kind:'river', note:'Where David’s exhausted men stayed behind.', refs:['1 Samuel 30:9'] },
  { name:'Mediterranean Sea', modern:'The Great Sea', lat:33.50, lon:33.00, kind:'sea', note:'The "Great Sea" that bordered the land to the west.', refs:['Numbers 34:6'] },
  { name:'Red Sea', modern:'Red Sea / Gulf of Suez', lat:28.50, lon:33.30, kind:'sea', note:'The sea Israel crossed out of Egypt.', refs:['Exodus 14:21'] },
  // ── Phoenicia & Syria ──
  { name:'Tyre', modern:'Tyre, Lebanon', lat:33.27, lon:35.20, kind:'city', note:'Phoenician port; supplied cedar for the temple.', refs:['1 Kings 5:1','Matthew 15:21'] },
  { name:'Sidon', modern:'Saida, Lebanon', lat:33.56, lon:35.37, kind:'city', note:'Ancient Phoenician city north of Tyre.', refs:['Matthew 15:21'] },
  { name:'Zarephath', modern:'Sarafand, Lebanon', lat:33.45, lon:35.30, kind:'town', note:'Where Elijah and a widow were sustained.', refs:['1 Kings 17:9'] },
  { name:'Damascus', modern:'Damascus, Syria', lat:33.51, lon:36.29, kind:'city', note:'Capital of Aram; Saul’s conversion was on its road.', refs:['Acts 9:3'] },
  { name:'Antioch (Syria)', modern:'Antakya, Turkey', lat:36.20, lon:36.16, kind:'city', note:'Where believers were first called Christians.', refs:['Acts 11:26'] },
  { name:'Seleucia', modern:'Samandağ, Turkey', lat:36.12, lon:35.93, kind:'port', note:'Port of Antioch where Paul set sail.', refs:['Acts 13:4'] },
  { name:'Aleppo (Helbon?)', modern:'Aleppo, Syria', lat:36.20, lon:37.16, kind:'city', note:'Ancient Syrian city near the trade routes.', refs:['Ezekiel 27:18'] },
  { name:'Riblah', modern:'Riblah, Syria', lat:34.45, lon:36.55, kind:'town', note:'Where Nebuchadnezzar judged captured kings.', refs:['2 Kings 25:6'] },
  { name:'Hamath', modern:'Hama, Syria', lat:35.13, lon:36.75, kind:'city', note:'Northern boundary marker of the land.', refs:['Numbers 34:8'] },
  // ── Egypt ──
  { name:'Egypt', modern:'Egypt', lat:27.00, lon:31.00, kind:'nation', note:'Land of bondage and of refuge.', refs:['Genesis 12:10','Exodus 1:8'] },
  { name:'Goshen', modern:'Eastern Nile Delta', lat:30.80, lon:31.85, kind:'region', note:'Where Israel settled in Egypt.', refs:['Genesis 47:6'] },
  { name:'Rameses', modern:'Eastern Nile Delta', lat:30.80, lon:31.90, kind:'city', note:'Store-city Israel built; the Exodus began here.', refs:['Exodus 1:11','Exodus 12:37'] },
  { name:'Pithom', modern:'Eastern Nile Delta', lat:30.55, lon:32.10, kind:'city', note:'Store-city built by Israelite labor.', refs:['Exodus 1:11'] },
  { name:'Tahpanhes', modern:'Tell Defenneh, Egypt', lat:30.85, lon:32.18, kind:'city', note:'Where Judah’s remnant fled with Jeremiah.', refs:['Jeremiah 43:7'] },
  { name:'Memphis (Noph)', modern:'Mit Rahina, Egypt', lat:29.84, lon:31.25, kind:'city', note:'Ancient capital of Lower Egypt.', refs:['Hosea 9:6','Jeremiah 46:14'] },
  { name:'Thebes (No-Amon)', modern:'Luxor, Egypt', lat:25.70, lon:32.64, kind:'city', note:'Great city of Upper Egypt, judged by the prophets.', refs:['Nahum 3:8'] },
  { name:'On (Heliopolis)', modern:'Cairo (Heliopolis)', lat:30.13, lon:31.30, kind:'city', note:'City of the priest whose daughter Joseph married.', refs:['Genesis 41:45'] },
  { name:'Nile River', modern:'Nile, Egypt', lat:27.00, lon:31.20, kind:'river', note:'The river of Egypt; turned to blood in the plagues.', refs:['Exodus 7:20'] },
  { name:'Pi-hahiroth', modern:'NE Egypt (debated)', lat:30.05, lon:32.55, kind:'site', note:'Where Israel camped before the sea crossing.', refs:['Exodus 14:2'] },
  // ── Mesopotamia & the East ──
  { name:'Ur of the Chaldeans', modern:'Tell el-Muqayyar, Iraq', lat:30.96, lon:46.10, kind:'city', note:'Abraham’s original home.', refs:['Genesis 11:31'] },
  { name:'Haran', modern:'Harran, Turkey', lat:36.86, lon:39.03, kind:'city', note:'Where Abraham’s family settled, and Jacob found Laban.', refs:['Genesis 11:31','Genesis 29:4'] },
  { name:'Babylon', modern:'Hillah, Iraq', lat:32.54, lon:44.42, kind:'city', note:'Capital of the empire that exiled Judah.', refs:['Daniel 1:1','2 Kings 25:1'] },
  { name:'Nineveh', modern:'Mosul, Iraq', lat:36.36, lon:43.15, kind:'city', note:'Capital of Assyria; Jonah preached here.', refs:['Jonah 3:3','Nahum 1:1'] },
  { name:'Calah (Nimrud)', modern:'Nimrud, Iraq', lat:36.10, lon:43.33, kind:'city', note:'One of the great cities founded by Nimrod.', refs:['Genesis 10:11'] },
  { name:'Babel / Shinar', modern:'Southern Iraq', lat:32.54, lon:44.42, kind:'region', note:'The plain where the tower was built.', refs:['Genesis 11:2'] },
  { name:'Euphrates River', modern:'Euphrates', lat:35.00, lon:40.50, kind:'river', note:'The great river of Mesopotamia, eastern boundary.', refs:['Genesis 15:18'] },
  { name:'Tigris River (Hiddekel)', modern:'Tigris', lat:34.40, lon:43.50, kind:'river', note:'River of Eden and of Daniel’s vision.', refs:['Genesis 2:14','Daniel 10:4'] },
  { name:'Gozan (Habor)', modern:'NE Syria', lat:36.80, lon:40.00, kind:'region', note:'Where the northern tribes were exiled.', refs:['2 Kings 17:6'] },
  { name:'Carchemish', modern:'Jerablus, Syria', lat:36.83, lon:38.01, kind:'city', note:'Site of the great battle by the Euphrates.', refs:['Jeremiah 46:2'] },
  { name:'Pethor', modern:'Upper Euphrates', lat:36.50, lon:38.00, kind:'town', note:'Home of Balaam, near the river.', refs:['Numbers 22:5'] },
  { name:'Susa (Shushan)', modern:'Shush, Iran', lat:32.19, lon:48.26, kind:'city', note:'Persian capital; home of Esther and Nehemiah.', refs:['Esther 1:2','Nehemiah 1:1'] },
  { name:'Ararat', modern:'E. Turkey / Armenia', lat:39.70, lon:44.30, kind:'mountain', note:'Where the ark came to rest.', refs:['Genesis 8:4'] },
  // ── Asia Minor (Paul & Revelation) ──
  { name:'Tarsus', modern:'Tarsus, Turkey', lat:36.92, lon:34.90, kind:'city', note:'Paul’s home city in Cilicia.', refs:['Acts 9:11'] },
  { name:'Antioch in Pisidia', modern:'Yalvaç, Turkey', lat:38.31, lon:31.19, kind:'city', note:'Where Paul preached on his first journey.', refs:['Acts 13:14'] },
  { name:'Iconium', modern:'Konya, Turkey', lat:37.87, lon:32.49, kind:'city', note:'Visited by Paul and Barnabas.', refs:['Acts 14:1'] },
  { name:'Lystra', modern:'Hatunsaray, Turkey', lat:37.58, lon:32.45, kind:'city', note:'Where Paul was stoned; Timothy’s home.', refs:['Acts 14:8'] },
  { name:'Derbe', modern:'Kerti Hüyük, Turkey', lat:37.35, lon:33.27, kind:'city', note:'Easternmost city of the first journey.', refs:['Acts 14:20'] },
  { name:'Perga', modern:'Perge, Turkey', lat:36.96, lon:30.85, kind:'city', note:'Where John Mark left Paul.', refs:['Acts 13:13'] },
  { name:'Attalia', modern:'Antalya, Turkey', lat:36.88, lon:30.70, kind:'port', note:'Port where Paul sailed back to Antioch.', refs:['Acts 14:25'] },
  { name:'Troas', modern:'Dalyan, Turkey', lat:39.75, lon:26.16, kind:'city', note:'Where Paul saw the vision of Macedonia.', refs:['Acts 16:8'] },
  { name:'Assos', modern:'Behramkale, Turkey', lat:39.49, lon:26.34, kind:'port', note:'Where Paul rejoined the ship on foot.', refs:['Acts 20:13'] },
  { name:'Miletus', modern:'Balat, Turkey', lat:37.53, lon:27.28, kind:'city', note:'Where Paul gave the Ephesian elders his farewell.', refs:['Acts 20:17'] },
  { name:'Ephesus', modern:'Selçuk, Turkey', lat:37.94, lon:27.34, kind:'city', note:'Major city where Paul ministered; a church of Revelation.', refs:['Acts 19:1','Revelation 2:1'] },
  { name:'Smyrna', modern:'Izmir, Turkey', lat:38.42, lon:27.14, kind:'city', note:'Persecuted church urged to be faithful unto death.', refs:['Revelation 2:8'] },
  { name:'Pergamum', modern:'Bergama, Turkey', lat:39.13, lon:27.18, kind:'city', note:'Church "where Satan’s throne is."', refs:['Revelation 2:12'] },
  { name:'Thyatira', modern:'Akhisar, Turkey', lat:38.92, lon:27.84, kind:'city', note:'Church of Lydia’s trade, warned about Jezebel.', refs:['Revelation 2:18'] },
  { name:'Sardis', modern:'Sart, Turkey', lat:38.49, lon:28.04, kind:'city', note:'Church with a name for being alive, yet dead.', refs:['Revelation 3:1'] },
  { name:'Philadelphia', modern:'Alaşehir, Turkey', lat:38.35, lon:28.52, kind:'city', note:'Church with an open door set before it.', refs:['Revelation 3:7'] },
  { name:'Laodicea', modern:'Denizli, Turkey', lat:37.84, lon:29.11, kind:'city', note:'The lukewarm church.', refs:['Revelation 3:14'] },
  { name:'Colossae', modern:'Honaz, Turkey', lat:37.79, lon:29.26, kind:'city', note:'Church that received Paul’s letter to the Colossians.', refs:['Colossians 1:2'] },
  { name:'Hierapolis', modern:'Pamukkale, Turkey', lat:37.92, lon:29.13, kind:'city', note:'City near Colossae mentioned with Laodicea.', refs:['Colossians 4:13'] },
  { name:'Myra', modern:'Demre, Turkey', lat:36.25, lon:29.98, kind:'city', note:'Where Paul changed ships toward Rome.', refs:['Acts 27:5'] },
  { name:'Patara', modern:'Gelemiş, Turkey', lat:36.27, lon:29.31, kind:'port', note:'Where Paul found a ship for Phoenicia.', refs:['Acts 21:1'] },
  { name:'Cnidus', modern:'Datça, Turkey', lat:36.69, lon:27.37, kind:'port', note:'Cape passed on the voyage to Rome.', refs:['Acts 27:7'] },
  // ── Greece, the islands & Rome ──
  { name:'Philippi', modern:'Filippoi, Greece', lat:41.01, lon:24.29, kind:'city', note:'First church in Europe; Lydia and the jailer.', refs:['Acts 16:12'] },
  { name:'Neapolis', modern:'Kavala, Greece', lat:40.94, lon:24.41, kind:'port', note:'Port where Paul first set foot in Europe.', refs:['Acts 16:11'] },
  { name:'Thessalonica', modern:'Thessaloniki, Greece', lat:40.64, lon:22.94, kind:'city', note:'Church that received two of Paul’s letters.', refs:['Acts 17:1'] },
  { name:'Berea', modern:'Veria, Greece', lat:40.52, lon:22.20, kind:'city', note:'Whose people searched the Scriptures daily.', refs:['Acts 17:11'] },
  { name:'Athens', modern:'Athens, Greece', lat:37.98, lon:23.73, kind:'city', note:'Where Paul preached at the Areopagus.', refs:['Acts 17:22'] },
  { name:'Corinth', modern:'Corinth, Greece', lat:37.94, lon:22.93, kind:'city', note:'Where Paul stayed eighteen months.', refs:['Acts 18:1'] },
  { name:'Cenchreae', modern:'Kechries, Greece', lat:37.88, lon:22.99, kind:'port', note:'Corinth’s eastern port; Phoebe’s church.', refs:['Romans 16:1'] },
  { name:'Samothrace', modern:'Samothraki, Greece', lat:40.48, lon:25.53, kind:'island', note:'Island where Paul’s ship anchored.', refs:['Acts 16:11'] },
  { name:'Cyprus', modern:'Cyprus', lat:35.05, lon:33.20, kind:'island', note:'Barnabas’s homeland; first missionary stop.', refs:['Acts 13:4'] },
  { name:'Salamis', modern:'Cyprus (east)', lat:35.18, lon:33.90, kind:'city', note:'Where Paul began preaching on Cyprus.', refs:['Acts 13:5'] },
  { name:'Paphos', modern:'Cyprus (west)', lat:34.75, lon:32.41, kind:'city', note:'Where the proconsul believed.', refs:['Acts 13:6'] },
  { name:'Crete', modern:'Crete, Greece', lat:35.20, lon:24.90, kind:'island', note:'Island where Titus was left; Paul’s ship sheltered.', refs:['Acts 27:7','Titus 1:5'] },
  { name:'Fair Havens', modern:'Crete (south coast)', lat:34.90, lon:24.80, kind:'port', note:'Harbor where Paul warned against sailing on.', refs:['Acts 27:8'] },
  { name:'Rhodes', modern:'Rhodes, Greece', lat:36.43, lon:28.22, kind:'island', note:'Island stop on Paul’s voyage to Jerusalem.', refs:['Acts 21:1'] },
  { name:'Cos', modern:'Kos, Greece', lat:36.89, lon:27.29, kind:'island', note:'Island stop near Miletus.', refs:['Acts 21:1'] },
  { name:'Malta (Melita)', modern:'Malta', lat:35.90, lon:14.40, kind:'island', note:'Where Paul was shipwrecked and bitten by a viper.', refs:['Acts 28:1'] },
  { name:'Syracuse', modern:'Siracusa, Italy', lat:37.07, lon:15.29, kind:'city', note:'Sicilian port on the way to Rome.', refs:['Acts 28:12'] },
  { name:'Rhegium', modern:'Reggio Calabria', lat:38.11, lon:15.65, kind:'city', note:'Italian port rounded en route to Rome.', refs:['Acts 28:13'] },
  { name:'Puteoli', modern:'Pozzuoli, Italy', lat:40.82, lon:14.12, kind:'port', note:'Where Paul landed in Italy.', refs:['Acts 28:13'] },
  { name:'Rome', modern:'Rome, Italy', lat:41.90, lon:12.50, kind:'city', note:'Capital of the empire; Paul’s final destination in Acts.', refs:['Acts 28:16','Romans 1:7'] },
  // ── Lands & nations ──
  { name:'Canaan', modern:'Israel / Levant', lat:31.80, lon:35.20, kind:'region', note:'The Promised Land given to Israel.', refs:['Genesis 12:5'] },
  { name:'Galilee', modern:'Northern Israel', lat:32.90, lon:35.40, kind:'region', note:'Northern region of much of Jesus’ ministry.', refs:['Matthew 4:23'] },
  { name:'Samaria (region)', modern:'Central West Bank', lat:32.30, lon:35.25, kind:'region', note:'The central hill country between Galilee and Judea.', refs:['John 4:4'] },
  { name:'Judea', modern:'Southern West Bank', lat:31.60, lon:35.10, kind:'region', note:'The southern region around Jerusalem.', refs:['Matthew 2:1'] },
  { name:'Decapolis', modern:'NE Jordan / Golan', lat:32.50, lon:35.90, kind:'region', note:'League of ten Greek cities east of Galilee.', refs:['Mark 5:20'] },
  { name:'Perea', modern:'West-central Jordan', lat:31.90, lon:35.65, kind:'region', note:'"Beyond the Jordan," where Jesus often taught.', refs:['John 10:40'] },
  { name:'Edom', modern:'Southern Jordan', lat:30.60, lon:35.40, kind:'region', note:'The land of Esau’s descendants.', refs:['Genesis 36:8'] },
  { name:'Moab', modern:'West-central Jordan', lat:31.50, lon:35.70, kind:'region', note:'Land east of the Dead Sea; Ruth’s homeland.', refs:['Ruth 1:1'] },
  { name:'Ammon', modern:'Amman region, Jordan', lat:31.95, lon:35.90, kind:'region', note:'Land of the Ammonites, around Rabbah.', refs:['Judges 11:4'] },
  { name:'Gilead', modern:'Northern Jordan', lat:32.20, lon:35.75, kind:'region', note:'Highland east of the Jordan, known for its balm.', refs:['Jeremiah 8:22'] },
  { name:'Bashan', modern:'Golan / S. Syria', lat:32.80, lon:36.00, kind:'region', note:'Fertile northern plateau famed for its cattle.', refs:['Psalms 22:12'] },
  { name:'Midian', modern:'NW Arabia', lat:28.40, lon:35.30, kind:'region', note:'Where Moses fled and married Zipporah.', refs:['Exodus 2:15'] },
  { name:'Philistia', modern:'SW coastal plain', lat:31.60, lon:34.60, kind:'region', note:'Coastal land of the five Philistine cities.', refs:['Exodus 13:17'] },
  { name:'Assyria', modern:'Northern Iraq', lat:36.30, lon:43.10, kind:'nation', note:'Empire that exiled the northern kingdom.', refs:['2 Kings 17:6'] },
  { name:'Aram (Syria)', modern:'Syria', lat:33.90, lon:36.50, kind:'nation', note:'Kingdom centered on Damascus.', refs:['2 Kings 5:1'] },
  { name:'Macedonia', modern:'Northern Greece', lat:40.80, lon:22.50, kind:'region', note:'Region of Philippi, Thessalonica, and Berea.', refs:['Acts 16:9'] },
  { name:'Achaia', modern:'Southern Greece', lat:38.00, lon:22.90, kind:'region', note:'Roman province of Athens and Corinth.', refs:['Acts 18:12'] },
  { name:'Galatia', modern:'Central Turkey', lat:39.50, lon:32.80, kind:'region', note:'Region of churches that received Paul’s letter.', refs:['Galatians 1:2'] },
  { name:'Cilicia', modern:'Southern Turkey', lat:37.00, lon:35.30, kind:'region', note:'Paul’s home province around Tarsus.', refs:['Acts 15:41'] },
  { name:'Cappadocia', modern:'Central Turkey', lat:38.70, lon:34.80, kind:'region', note:'Region whose pilgrims heard the gospel at Pentecost.', refs:['Acts 2:9','1 Peter 1:1'] },
  { name:'Pontus', modern:'N. Turkey (Black Sea)', lat:40.90, lon:36.50, kind:'region', note:'Aquila’s home region on the Black Sea.', refs:['Acts 18:2','1 Peter 1:1'] },
  { name:'Bithynia', modern:'NW Turkey', lat:40.40, lon:30.50, kind:'region', note:'Region the Spirit kept Paul from entering.', refs:['Acts 16:7'] },
  { name:'Pamphylia', modern:'S. coast of Turkey', lat:36.90, lon:30.80, kind:'region', note:'Coastal region around Perga.', refs:['Acts 13:13'] },
  { name:'Lycia', modern:'SW Turkey', lat:36.40, lon:29.60, kind:'region', note:'Coastal region of Myra and Patara.', refs:['Acts 27:5'] },
  { name:'Phrygia', modern:'W-central Turkey', lat:38.80, lon:30.50, kind:'region', note:'Inland region Paul passed through.', refs:['Acts 16:6'] },
  { name:'Mysia', modern:'NW Turkey', lat:39.60, lon:28.00, kind:'region', note:'Region around Troas.', refs:['Acts 16:7'] },
  { name:'Lebanon', modern:'Lebanon mountains', lat:33.80, lon:35.85, kind:'region', note:'Cedar-clad range supplying timber for the temple.', refs:['1 Kings 5:6'] },
  // ── Distant lands of the table of nations (beyond the mapped region) ──
  { name:'Tarshish', modern:'Far western Mediterranean (Spain?)', lat:37.20, lon:-6.00, kind:'region', note:'Distant western port Jonah fled toward.', refs:['Jonah 1:3','1 Kings 10:22'] },
  { name:'Sheba', modern:'Southern Arabia (Yemen)', lat:15.40, lon:44.20, kind:'region', note:'Land of the queen who visited Solomon.', refs:['1 Kings 10:1'] },
  { name:'Ophir', modern:'Arabia / E. Africa (debated)', lat:21.00, lon:40.00, kind:'region', note:'Source of Solomon’s gold.', refs:['1 Kings 9:28'] },
  { name:'Cush (Ethiopia)', modern:'Sudan / Ethiopia', lat:18.00, lon:33.00, kind:'nation', note:'Land south of Egypt; home of the Ethiopian official.', refs:['Acts 8:27','Isaiah 18:1'] },
  { name:'Javan (Greece)', modern:'Greece / Ionia', lat:38.50, lon:23.00, kind:'nation', note:'The Greeks in the table of nations.', refs:['Genesis 10:2','Daniel 8:21'] },
  { name:'Caphtor', modern:'Crete', lat:35.20, lon:24.90, kind:'region', note:'Original homeland of the Philistines.', refs:['Amos 9:7'] },
  { name:'Media', modern:'NW Iran', lat:35.70, lon:48.50, kind:'nation', note:'Allied with Persia against Babylon.', refs:['Daniel 5:28'] },
  { name:'Persia', modern:'Iran', lat:32.00, lon:53.00, kind:'nation', note:'Empire that let the exiles return.', refs:['Ezra 1:1'] },
  { name:'Uz', modern:'Edom / N. Arabia (debated)', lat:30.50, lon:36.50, kind:'region', note:'The land of Job.', refs:['Job 1:1'] }
];
if (typeof module !== 'undefined' && module.exports) module.exports = window.BIBLE_ATLAS;
