import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import {
  initializeFirestore,
  persistentLocalCache,
  doc,
  setDoc,
  getDoc,
  addDoc,
  collectionGroup,
  deleteDoc,
  collection,
  query,
  orderBy,
  where,
  limit,
  getDocs,
  onSnapshot,
  serverTimestamp,
  updateDoc,
  writeBatch,
  arrayUnion,
  arrayRemove,
  increment,
  deleteField
} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import {
  getAuth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  signOut,
  deleteUser,
  onAuthStateChanged,
  EmailAuthProvider,
  reauthenticateWithCredential,
  verifyBeforeUpdateEmail,
  sendPasswordResetEmail
} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import {
  getMessaging,
  getToken,
  onMessage
} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging.js";
import {
  getStorage,
  ref as storageRef,
  uploadBytes,
  getDownloadURL,
  deleteObject
} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-storage.js";
import {
  getFunctions,
  httpsCallable
} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-functions.js";

const firebaseConfig = {
  apiKey: "AIzaSyDVWKRCtjg7ppR-D8ZNs-TfSwPlWdXXQ5Q",
  authDomain: "greek-vocab-leaderboard.firebaseapp.com",
  projectId: "greek-vocab-leaderboard",
  storageBucket: "greek-vocab-leaderboard.firebasestorage.app",
  messagingSenderId: "473409624300",
  appId: "1:473409624300:web:8288c792af4f3c32586dc9"
};

const fbApp = initializeApp(firebaseConfig);
const db = initializeFirestore(fbApp, { localCache: persistentLocalCache() });
const auth = getAuth(fbApp);
const storage = getStorage(fbApp);
const functionsApp = getFunctions(fbApp);
let messaging = null;
try { messaging = getMessaging(fbApp); } catch (e) { console.warn("FCM unavailable:", e); }

const EMAIL_DOMAIN = "@greek-vocab.app";
const DAY_MS = 24 * 60 * 60 * 1000;
const COMMUNITY_POST_TTL_MS = 7 * DAY_MS;
const MERCY_POST_TTL_MS = 21 * DAY_MS;

// ── Auth ──────────────────────────────────────────────────────────────────────

function toEmail(username) {
  return `${username.toLowerCase().trim()}${EMAIL_DOMAIN}`;
}

const REAL_EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// Accounts created before email linking use an auto-generated <username>@greek-vocab.app
// address. Those users have no recoverable email; a "real" connected email never uses our domain.
function isAutoGeneratedEmail(email) {
  return !email || email.toLowerCase().endsWith(EMAIL_DOMAIN);
}

// Snapshot of the signed-in user's email situation, used by the UI to decide
// whether to prompt for email connection and how to label account-recovery options.
function getAuthEmailInfo() {
  const user = auth.currentUser;
  if (!user) return { signedIn: false, email: null, isAutoGenerated: false, emailVerified: false };
  return {
    signedIn: true,
    email: user.email,
    emailVerified: !!user.emailVerified,
    isAutoGenerated: isAutoGeneratedEmail(user.email)
  };
}

async function checkUsernameTaken(username) {
  try {
    const snap = await getDoc(doc(db, "usernames", username.toLowerCase().trim()));
    return snap.exists();
  } catch { return false; }
}

async function checkDisplayNameTaken(displayName) {
  try {
    const snap = await getDoc(doc(db, "displayNames", displayName.toLowerCase().trim()));
    return snap.exists();
  } catch { return false; }
}

async function createAccount(username, password, displayName, migrationData = {}) {
  const cred = await createUserWithEmailAndPassword(auth, toEmail(username), password);
  const uid = cred.user.uid;
  const joinDate = migrationData.joinDate || new Date().toISOString();
  const usernameKey = username.toLowerCase().trim();
  const displayNameKey = displayName.toLowerCase().trim();

  try {
    await Promise.all([
      setDoc(doc(db, "usernames", usernameKey), { uid }),
      setDoc(doc(db, "displayNames", displayNameKey), { uid, displayName })
    ]);

    const userData = {
      username,
      displayName,
      joinDate,
      xp: migrationData.xp || 0,
      color: migrationData.color || "#d4a93a",
      greekExperience: migrationData.greekExperience || "new",
      avatar: migrationData.avatar || "school",
      streak: migrationData.streak || 0,
      lastStudyDate: migrationData.lastStudyDate || null,
      totalStudySeconds: migrationData.totalStudySeconds || 0,
      completedLessons: migrationData.completedLessons || {},
      completedAdvancedLessons: migrationData.completedAdvancedLessons || {},
      knownWords: migrationData.knownWords || [],
      translationProgress: migrationData.translationProgress || {},
      achievements: migrationData.achievements || [],
      practiceToolsUnlocked: migrationData.practiceToolsUnlocked || false,
      lessonMode: migrationData.lessonMode || "basic",
      vocabChapterXP: migrationData.vocabChapterXP || {},
      lbXpJoined: migrationData.lbXpJoined || false,
      lbConsJoined: migrationData.lbConsJoined || false,
      lbScholarJoined: migrationData.lbScholarJoined || false,
      lbScholarBest: migrationData.lbScholarBest || 0,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp()
    };

    await setDoc(doc(db, "users", uid), userData);
    return { uid, joinDate, displayName, username };
  } catch (e) {
    await Promise.all([
      deleteDoc(doc(db, "usernames", usernameKey)).catch(() => {}),
      deleteDoc(doc(db, "displayNames", displayNameKey)).catch(() => {}),
      deleteUser(cred.user).catch(() => {})
    ]);
    throw e;
  }
}

// `identifier` may be a username (legacy/auto-generated accounts) or a real email
// address (accounts that have connected one — their Firebase login email is the real address).
async function login(identifier, password) {
  const id = (identifier || "").trim();
  const email = id.includes("@") ? id.toLowerCase() : toEmail(id);
  const cred = await signInWithEmailAndPassword(auth, email, password);
  return cred.user;
}

async function logout() {
  await signOut(auth);
}

// Connect a real email to an account that currently uses an auto-generated one.
// Re-authenticates with the current password, then sends a verification link to the
// new address; the Firebase auth email only changes once the user clicks that link.
async function connectEmail(newEmail, currentPassword) {
  const user = auth.currentUser;
  if (!user) throw new Error("You must be signed in to connect an email.");

  const email = (newEmail || "").trim().toLowerCase();
  if (!REAL_EMAIL_RE.test(email)) throw new Error("Please enter a valid email address.");
  if (email.endsWith(EMAIL_DOMAIN)) throw new Error("Please use your own real email address.");
  if (!currentPassword) throw new Error("Please enter your current password to confirm it's you.");

  const credential = EmailAuthProvider.credential(user.email, currentPassword);
  await reauthenticateWithCredential(user, credential);
  await verifyBeforeUpdateEmail(user, email);

  try { localStorage.setItem("pendingConnectEmail", email); } catch {}
  return email;
}

// Send a Firebase password-reset email. Only delivers to accounts whose login email is
// the given address (i.e. users who have connected a real email).
async function sendPasswordReset(email) {
  const addr = (email || "").trim().toLowerCase();
  if (!REAL_EMAIL_RE.test(addr)) throw new Error("Please enter a valid email address.");
  if (addr.endsWith(EMAIL_DOMAIN)) throw new Error("Please enter the real email connected to your account.");
  await sendPasswordResetEmail(auth, addr);
}

async function deleteAccount(password) {
  const user = auth.currentUser;
  if (!user) return;
  const uid = user.uid;

  const username = localStorage.getItem("authUsername") || "";
  const email = user.email || toEmail(username);
  const credential = EmailAuthProvider.credential(email, password);
  await reauthenticateWithCredential(user, credential);

  let userData = null;
  try {
    const snap = await getDoc(doc(db, "users", uid));
    if (snap.exists()) {
      userData = snap.data();
      const { username: u, displayName } = userData;
      await Promise.all([
        deleteDoc(doc(db, "usernames", (u || "").toLowerCase().trim())).catch(() => {}),
        deleteDoc(doc(db, "displayNames", (displayName || "").toLowerCase().trim())).catch(() => {})
      ]);
    }
  } catch {}

  await cleanupAccountSocialData(uid, userData);

  await Promise.all([
    deleteDoc(doc(db, "users", uid)).catch(() => {}),
    deleteDoc(doc(db, "xp_board", uid)).catch(() => {}),
    deleteDoc(doc(db, "scholar_board", uid)).catch(() => {}),
    deleteDoc(doc(db, "consistency_board", uid)).catch(() => {}),
    deleteObject(storageRef(storage, `avatars/${uid}.jpg`)).catch(() => {})
  ]);

  await deleteUser(user);
}

async function cleanupAccountSocialData(uid, userData = null) {
  try {
    const friendUids = userData?.friends || [];
    await Promise.all(friendUids.map(friendUid =>
      updateDoc(doc(db, "users", friendUid), {
        friends: arrayRemove(uid),
        friendRequestsIn: arrayRemove(uid),
        friendRequestsOut: arrayRemove(uid),
        updatedAt: serverTimestamp()
      }).catch(() => {})
    ));
  } catch (e) { console.warn("cleanupAccountSocialData friends:", e); }

  try {
    const audiencePosts = await getDocs(query(collection(db, "communityPosts"), where("audienceUids", "array-contains", uid), limit(100)));
    await Promise.all(audiencePosts.docs.map(d => {
      if (d.data().authorUid === uid) {
        return updateDoc(d.ref, { isActive: false, deletedAt: serverTimestamp() }).catch(() => {});
      }
      return updateDoc(d.ref, {
        [`reactions.${uid}`]: deleteField(),
        [`prayers.${uid}`]: deleteField()
      }).catch(() => {});
    }));
  } catch (e) { console.warn("cleanupAccountSocialData post activity:", e); }

  try {
    const mercyPosts = await getDocs(query(collection(db, "merciesPosts"), where("audienceUids", "array-contains", uid), limit(100)));
    await Promise.all(mercyPosts.docs.map(d => {
      if (d.data().authorUid === uid) {
        if (d.data().imagePath) deleteObject(storageRef(storage, d.data().imagePath)).catch(() => {});
        return updateDoc(d.ref, { isActive: false, deletedAt: serverTimestamp() }).catch(() => {});
      }
      return updateDoc(d.ref, { [`reactions.${uid}`]: deleteField() }).catch(() => {});
    }));
  } catch (e) { console.warn("cleanupAccountSocialData mercies:", e); }

  try {
    const authoredComments = await getDocs(query(collectionGroup(db, "comments"), where("authorUid", "==", uid), limit(100)));
    await Promise.all(authoredComments.docs.map(d => {
      const postRef = d.ref.parent.parent;
      return Promise.all([
        deleteDoc(d.ref).catch(() => {}),
        postRef ? updateDoc(postRef, { commentCount: increment(-1) }).catch(() => {}) : Promise.resolve()
      ]);
    }));
  } catch (e) { console.warn("cleanupAccountSocialData comments:", e); }

  try {
    const studies = await getDocs(query(collection(db, "studies"), where("collaboratorUids", "array-contains", uid), limit(100)));
    await Promise.all(studies.docs.map(async d => {
      const study = d.data();
      if (study.creatorUid !== uid) {
        return updateDoc(d.ref, {
          collaboratorUids: arrayRemove(uid),
          pendingCollaboratorUids: arrayRemove(uid)
        }).catch(() => {});
      }

      for (const sub of ["notes", "entries", "savedVerses", "wordLog", "trails"]) {
        const subSnap = await getDocs(collection(db, "studies", d.id, sub)).catch(() => null);
        if (subSnap) await Promise.all(subSnap.docs.map(child => deleteDoc(child.ref).catch(() => {})));
      }
      return deleteDoc(d.ref).catch(() => {});
    }));
  } catch (e) { console.warn("cleanupAccountSocialData studies:", e); }

  try {
    const messages = await getDocs(collection(db, "encouragements", uid, "messages"));
    await Promise.all(messages.docs.map(d => deleteDoc(d.ref).catch(() => {})));
  } catch (e) { console.warn("cleanupAccountSocialData messages:", e); }
}

function onAuthChange(callback) {
  onAuthStateChanged(auth, callback);
}

function getCurrentUser() {
  return auth.currentUser;
}

async function loadUserData(uid) {
  try {
    const snap = await getDoc(doc(db, "users", uid));
    return snap.exists() ? snap.data() : null;
  } catch { return null; }
}

function listenUserDoc(uid, callback) {
  return onSnapshot(doc(db, "users", uid), snap => {
    if (snap.exists()) callback(snap.data());
  });
}

// ── Rhema verse marks (user highlights + notes) ───────────────────────────────
// One doc per marked verse under users/{uid}/rhemaMarks, keyed by a sanitized
// "Book chapter:verse" reference. Stores highlight colour and/or a note.
function _rhemaMarkId(ref) {
  return String(ref).replace(/[^A-Za-z0-9]+/g, "_");
}

function listenRhemaMarks(uid, callback) {
  return onSnapshot(collection(db, "users", uid, "rhemaMarks"), snap => {
    const map = {};
    snap.docs.forEach(d => { const x = d.data(); if (x && x.ref) map[d.id] = x; });
    callback(map);
  }, err => console.warn("listenRhemaMarks:", err));
}

async function saveRhemaMark(uid, ref, scope, data) {
  if (!uid || !ref) return;
  const id = _rhemaMarkId((scope || "home") + "__" + ref);
  await setDoc(
    doc(db, "users", uid, "rhemaMarks", id),
    { ref, scope: scope || "home", ...data, updatedAt: serverTimestamp() },
    { merge: true }
  );
}

async function deleteRhemaMark(uid, ref, scope) {
  if (!uid || !ref) return;
  await deleteDoc(doc(db, "users", uid, "rhemaMarks", _rhemaMarkId((scope || "home") + "__" + ref)));
}

// Saved verse comparisons ("trails"): users/{uid}/rhemaTrails/{trailId}.
function listenRhemaTrails(uid, callback) {
  return onSnapshot(
    query(collection(db, "users", uid, "rhemaTrails"), orderBy("createdAt", "desc")),
    snap => callback(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => console.warn("listenRhemaTrails:", err)
  );
}

async function saveRhemaTrail(uid, trail) {
  if (!uid) return null;
  const id = trail.id || _rhemaMarkId(`${Date.now()}_${Math.random().toString(36).slice(2, 8)}`);
  await setDoc(
    doc(db, "users", uid, "rhemaTrails", id),
    { ...trail, id, createdAt: trail.createdAt || Date.now(), updatedAt: serverTimestamp() },
    { merge: true }
  );
  return id;
}

async function deleteRhemaTrail(uid, id) {
  if (!uid || !id) return;
  await deleteDoc(doc(db, "users", uid, "rhemaTrails", id));
}

async function syncUserData(uid, data) {
  try {
    await setDoc(doc(db, "users", uid), { ...data, updatedAt: serverTimestamp() }, { merge: true });
  } catch (e) { console.warn("syncUserData:", e); }
}

async function clearPendingMercyFriendEncouragement(uid) {
  if (!uid) return;
  try {
    await updateDoc(doc(db, "users", uid), {
      pendingMercyFriendEncouragement: null,
      updatedAt: serverTimestamp()
    });
  } catch (e) { console.warn("clearPendingMercyFriendEncouragement:", e); }
}

// ── Leaderboard ───────────────────────────────────────────────────────────────

function getUserId() {
  return auth.currentUser?.uid || localStorage.getItem("lbUserId") || (() => {
    const id = crypto.randomUUID();
    localStorage.setItem("lbUserId", id);
    return id;
  })();
}

function getAvatar() {
  if (localStorage.getItem("profilePicType") === "photo") {
    return localStorage.getItem("profilePicRemoteURL") || "school";
  }
  return localStorage.getItem("profilePicValue") || "school";
}

async function getUsersByUid(uids = []) {
  const unique = [...new Set((uids || []).filter(Boolean))];
  const entries = await Promise.all(unique.map(async uid => {
    const snap = await getDoc(doc(db, "users", uid)).catch(() => null);
    return [uid, snap?.exists() ? snap.data() : null];
  }));
  return new Map(entries.filter(([, data]) => data));
}

async function uploadAvatarPhoto(uid, dataUrl) {
  const res = await fetch(dataUrl);
  const blob = await res.blob();
  const avatarStorageRef = storageRef(storage, `avatars/${uid}.jpg`);
  await uploadBytes(avatarStorageRef, blob, { contentType: "image/jpeg" });
  return await getDownloadURL(avatarStorageRef);
}

function getMeta() {
  return {
    joinDate: localStorage.getItem("appJoinDate") || null,
    studySeconds: Number(localStorage.getItem("totalStudySeconds")) || 0,
    testsCompleted: parseInt(localStorage.getItem("testsCompleted") || "0")
  };
}

function getLbDisplayName() {
  return localStorage.getItem("authDisplayName") || localStorage.getItem("authUsername") || "Anonymous";
}

async function checkNameTaken(boardName, name) {
  try {
    const q = query(collection(db, boardName), where("name", "==", name), limit(1));
    const snap = await getDocs(q);
    return snap.docs.some(d => d.id !== getUserId());
  } catch { return false; }
}

async function syncXP(xp) {
  if (localStorage.getItem("lbXpJoined") !== "true") return;
  try {
    await setDoc(doc(db, "xp_board", getUserId()), {
      name: getLbDisplayName(), xp, avatar: getAvatar(), ...getMeta(), updatedAt: serverTimestamp()
    }, { merge: true });
  } catch (e) { console.warn("LB syncXP:", e); }
}

async function syncStreak(streak) {
  if (localStorage.getItem("lbConsJoined") !== "true") return;
  try {
    await setDoc(doc(db, "consistency_board", getUserId()), {
      name: getLbDisplayName(), streak, avatar: getAvatar(), ...getMeta(), updatedAt: serverTimestamp()
    }, { merge: true });
  } catch (e) { console.warn("LB syncStreak:", e); }
}

async function submitScholarScore(score) {
  if (localStorage.getItem("lbScholarJoined") !== "true") return;
  const best = parseInt(localStorage.getItem("lbScholarBest") || "0");
  if (score <= best) return;
  localStorage.setItem("lbScholarBest", String(score));
  try {
    await setDoc(doc(db, "scholar_board", getUserId()), {
      name: getLbDisplayName(), bestScore: score, avatar: getAvatar(), ...getMeta(), updatedAt: serverTimestamp()
    }, { merge: true });
  } catch (e) { console.warn("LB submitScholar:", e); }
}

async function joinXPBoard(xp) {
  localStorage.setItem("lbXpJoined", "true");
  await setDoc(doc(db, "xp_board", getUserId()), {
    name: getLbDisplayName(), xp, avatar: getAvatar(), ...getMeta(), updatedAt: serverTimestamp()
  });
}

function joinScholarBoard() {
  localStorage.setItem("lbScholarJoined", "true");
}

async function joinConsistencyBoard(streak) {
  localStorage.setItem("lbConsJoined", "true");
  await setDoc(doc(db, "consistency_board", getUserId()), {
    name: getLbDisplayName(), streak, avatar: getAvatar(), ...getMeta(), updatedAt: serverTimestamp()
  });
}

async function refreshLeaderboardName(name) {
  if (!name || name === 'Anonymous') return;
  const uid = getUserId();
  if (!uid) return;
  try {
    const boards = [
      { key: 'xp_board', joined: 'lbXpJoined' },
      { key: 'consistency_board', joined: 'lbConsJoined' },
      { key: 'scholar_board', joined: 'lbScholarJoined' }
    ];
    for (const { key, joined } of boards) {
      if (localStorage.getItem(joined) === 'true') {
        await setDoc(doc(db, key, uid), { name }, { merge: true });
      }
    }
  } catch (e) { console.warn('refreshLeaderboardName:', e); }
}

async function syncAvatar() {
  const avatar = getAvatar();
  const boards = [
    { key: "xp_board", joined: "lbXpJoined" },
    { key: "scholar_board", joined: "lbScholarJoined" },
    { key: "consistency_board", joined: "lbConsJoined" }
  ];
  for (const { key, joined } of boards) {
    if (localStorage.getItem(joined) === "true") {
      try {
        await setDoc(doc(db, key, getUserId()), { avatar }, { merge: true });
      } catch {}
    }
  }
}

async function getBoard(boardName, field, topN = 100) {
  const q = query(collection(db, boardName), orderBy(field, "desc"), limit(topN));
  const snap = await getDocs(q);
  return snap.docs.map(d => ({ id: d.id, ...d.data() }));
}

function listenBoard(boardName, field, callback, topN = 100) {
  const q = query(collection(db, boardName), orderBy(field, "desc"), limit(topN));
  return onSnapshot(
    q,
    snap => callback(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => { console.warn("listenBoard:", boardName, err); callback(null, err); }
  );
}

async function deleteUserData() {
  const uid = getUserId();
  await Promise.all([
    deleteDoc(doc(db, "xp_board", uid)).catch(() => {}),
    deleteDoc(doc(db, "scholar_board", uid)).catch(() => {}),
    deleteDoc(doc(db, "consistency_board", uid)).catch(() => {})
  ]);
}

async function deleteEntriesForId(uid) {
  await Promise.all([
    deleteDoc(doc(db, "xp_board", uid)).catch(() => {}),
    deleteDoc(doc(db, "scholar_board", uid)).catch(() => {}),
    deleteDoc(doc(db, "consistency_board", uid)).catch(() => {})
  ]);
}

async function getUserRanks() {
  const uid = getUserId();
  const boards = [
    { key: "xp_board", field: "xp" },
    { key: "scholar_board", field: "bestScore" }
  ];
  const ranks = {};
  for (const { key, field } of boards) {
    try {
      const q = query(collection(db, key), orderBy(field, "desc"), limit(200));
      const snap = await getDocs(q);
      const idx = snap.docs.findIndex(d => d.id === uid);
      ranks[key] = idx >= 0 ? idx + 1 : null;
    } catch {
      ranks[key] = null;
    }
  }
  return ranks;
}

// ── Friends ───────────────────────────────────────────────────────────────────

async function frGetAllUsers(currentUid) {
  try {
    const q = query(collection(db, "users"), orderBy("xp", "desc"), limit(60));
    const snap = await getDocs(q);
    return snap.docs
      .filter(d => d.id !== currentUid)
      .map(d => ({ uid: d.id, ...d.data() }));
  } catch { return []; }
}

async function frSearchUsers(searchQuery, currentUid) {
  try {
    const end = searchQuery + "";
    const q = query(
      collection(db, "users"),
      where("displayName", ">=", searchQuery),
      where("displayName", "<=", end),
      limit(30)
    );
    const snap = await getDocs(q);
    return snap.docs
      .filter(d => d.id !== currentUid)
      .map(d => ({ uid: d.id, ...d.data() }));
  } catch { return []; }
}

async function frGetUser(uid) {
  try {
    const snap = await getDoc(doc(db, "users", uid));
    return snap.exists() ? { uid: snap.id, ...snap.data() } : null;
  } catch { return null; }
}

async function frSendRequest(fromUid, toUid, fromName) {
  try {
    await Promise.all([
      updateDoc(doc(db, "users", fromUid), { friendRequestsOut: arrayUnion(toUid),   updatedAt: serverTimestamp() }),
      updateDoc(doc(db, "users", toUid),   { friendRequestsIn:  arrayUnion(fromUid), updatedAt: serverTimestamp() })
    ]);
    if (fromName) fcmSendPushNotification(toUid, "friendRequest", fromName, fromUid);
    return true;
  } catch { return false; }
}

async function frCancelRequest(fromUid, toUid) {
  try {
    await Promise.all([
      updateDoc(doc(db, "users", fromUid), { friendRequestsOut: arrayRemove(toUid),   updatedAt: serverTimestamp() }),
      updateDoc(doc(db, "users", toUid),   { friendRequestsIn:  arrayRemove(fromUid), updatedAt: serverTimestamp() })
    ]);
    return true;
  } catch { return false; }
}

async function frAcceptRequest(uid, fromUid, myName) {
  try {
    await Promise.all([
      updateDoc(doc(db, "users", uid),     { friendRequestsIn:  arrayRemove(fromUid), friends: arrayUnion(fromUid), updatedAt: serverTimestamp() }),
      updateDoc(doc(db, "users", fromUid), { friendRequestsOut: arrayRemove(uid),     friends: arrayUnion(uid),     updatedAt: serverTimestamp() })
    ]);
    await shareRecentCommunityPostsWithFriend(uid, fromUid).catch(() => {});
    if (myName) fcmSendPushNotification(fromUid, "friendAccepted", myName, uid);
    return true;
  } catch { return false; }
}

async function shareRecentCommunityPostsWithFriend(uid, friendUid) {
  const now = Date.now();
  const shareMine = query(collection(db, "communityPosts"), where("authorUid", "==", uid), limit(30));
  const snap = await getDocs(shareMine);
  await Promise.all(snap.docs
    .filter(d => d.data().isActive !== false)
    .filter(d => !d.data().expiresAtMs || d.data().expiresAtMs > now)
    .map(d => updateDoc(d.ref, { audienceUids: arrayUnion(friendUid) }).catch(() => {})));
}

async function frDeclineRequest(uid, fromUid) {
  try {
    await Promise.all([
      updateDoc(doc(db, "users", uid),     { friendRequestsIn:  arrayRemove(fromUid), updatedAt: serverTimestamp() }),
      updateDoc(doc(db, "users", fromUid), { friendRequestsOut: arrayRemove(uid),     updatedAt: serverTimestamp() })
    ]);
    return true;
  } catch { return false; }
}

async function frRemoveFriend(uid, friendUid) {
  try {
    await Promise.all([
      updateDoc(doc(db, "users", uid),       { friends: arrayRemove(friendUid), updatedAt: serverTimestamp() }),
      updateDoc(doc(db, "users", friendUid), { friends: arrayRemove(uid),       updatedAt: serverTimestamp() })
    ]);
    return true;
  } catch { return false; }
}

window.Friends = {
  getAllUsers:     frGetAllUsers,
  searchUsers:    frSearchUsers,
  getUser:        frGetUser,
  sendRequest:    frSendRequest,
  cancelRequest:  frCancelRequest,
  acceptRequest:  frAcceptRequest,
  declineRequest: frDeclineRequest,
  removeFriend:   frRemoveFriend
};

// ── FCM ───────────────────────────────────────────────────────────────────────

const FCM_VAPID_KEY = "BDOeDKo0NmW6-kMwJB9noey7YK1u3raQ5NUvfFhv9kguPXDZfJirp5-ilbwwMCm9_0_hQ_EkiQktFe4f2pLl5VU";

// Delete a notification message after the user acts on it so it never re-surfaces
async function deleteEncouragementMsg(uid, msgId) {
  if (!uid || !msgId) return;
  try {
    await deleteDoc(doc(db, "encouragements", uid, "messages", msgId));
  } catch (e) { console.warn("deleteEncouragementMsg:", e); }
}

// Generic push notification writer — triggers the Cloud Function onEncouragementCreated.
// Pass dedupeKey to use a fixed document ID (setDoc) so a second write for the same
// event is an update (onUpdate), not a create (onCreate), and the Cloud Function won't
// fire a second time. Leave dedupeKey null for one-off messages that use addDoc.
async function fcmSendPushNotification(toUid, type, fromName, fromUid, extra = {}, dedupeKey = null) {
  try {
    const data = { type, fromName, fromUid, processed: false, createdAt: serverTimestamp(), ...extra };
    if (dedupeKey) {
      await setDoc(doc(db, "encouragements", toUid, "messages", dedupeKey), data);
    } else {
      await addDoc(collection(db, "encouragements", toUid, "messages"), data);
    }
    return true;
  } catch (e) {
    console.warn("fcmSendPushNotification:", e);
    return false;
  }
}

// ── Personal Studies (top-level collection, supports collaboration) ───────────

async function studyCreate(uid, displayName, { name, description, color, icon, shareSession }) {
  try {
    const ref = await addDoc(collection(db, "studies"), {
      name, description: description || '', color, icon,
      creatorUid: uid, creatorName: displayName,
      collaboratorUids: [uid], pendingCollaboratorUids: [],
      shareSession: !!shareSession,
      createdAt: serverTimestamp(), isActive: true,
      rhemaPositions: {}, lastSessionDates: {}
    });
    return {
      id: ref.id, name, description: description || '', color, icon,
      shareSession: !!shareSession,
      creatorUid: uid, creatorName: displayName,
      collaboratorUids: [uid], pendingCollaboratorUids: [],
      isActive: true, rhemaPositions: {}, lastSessionDates: {},
      createdAt: { seconds: Math.floor(Date.now() / 1000) }
    };
  } catch (e) {
    console.warn("studyCreate error:", e?.code, e?.message);
    return null;
  }
}

function studyListen(studyId, callback) {
  return onSnapshot(doc(db, "studies", studyId),
    snap => callback(snap.exists() ? { id: snap.id, ...snap.data() } : null),
    err => console.warn("studyListen:", err)
  );
}

async function studyInviteCollab(studyId, studyName, inviteeUid, myDisplayName) {
  try {
    await updateDoc(doc(db, "studies", studyId), { pendingCollaboratorUids: arrayUnion(inviteeUid) });
    await fcmSendPushNotification(inviteeUid, "studyInvite", myDisplayName, auth.currentUser?.uid, { studyId, studyName });
    return true;
  } catch (e) { console.warn("studyInviteCollab:", e); return false; }
}

async function studySelfApproveInvite(studyId, uid) {
  try {
    await updateDoc(doc(db, "studies", studyId), {
      collaboratorUids: arrayUnion(uid),
      pendingCollaboratorUids: arrayRemove(uid)
    });
    return true;
  } catch (e) { console.warn("studySelfApproveInvite:", e); return false; }
}

async function studyGet(studyId) {
  try {
    const snap = await getDoc(doc(db, "studies", studyId));
    return snap.exists() ? { id: snap.id, ...snap.data() } : null;
  } catch (e) { console.warn("studyGet:", e); return null; }
}

async function studyGetMine(uid) {
  try {
    // Single where clause — composite index not needed; filter isActive client-side
    const q = query(collection(db, "studies"), where("collaboratorUids", "array-contains", uid));
    const snap = await getDocs(q);
    return snap.docs.map(d => ({ id: d.id, ...d.data() }))
      .filter(s => s.isActive !== false)
      .sort((a, b) => (a.createdAt?.seconds || 0) - (b.createdAt?.seconds || 0));
  } catch (e) { console.warn("studyGetMine:", e); return []; }
}

async function studyGetFriends(friendUids) {
  if (!friendUids?.length) return [];
  try {
    const results = [];
    const seen = new Set();
    for (let i = 0; i < friendUids.length; i += 10) {
      const batch = friendUids.slice(i, i + 10);
      // Single where clause — filter isActive client-side to avoid composite index requirement
      const q = query(collection(db, "studies"), where("collaboratorUids", "array-contains-any", batch));
      const snap = await getDocs(q);
      snap.docs.forEach(d => { if (!seen.has(d.id)) { seen.add(d.id); results.push({ id: d.id, ...d.data() }); } });
    }
    return results.filter(s => s.isActive !== false).sort((a, b) => a.name.localeCompare(b.name));
  } catch (e) { console.warn("studyGetFriends:", e); return []; }
}

async function studyOpenSession(uid, studyId, { displayName, friendsList }) {
  const today = new Date().toLocaleDateString("en-CA");
  try {
    const ref = doc(db, "studies", studyId);
    const snap = await getDoc(ref);
    if (!snap.exists()) return;
    const data = snap.data();
    const alreadyDone = (data.lastSessionDates || {})[uid] === today;
    if (!alreadyDone) {
      await updateDoc(ref, { [`lastSessionDates.${uid}`]: today });
      if (data.shareSession && friendsList?.length) {
        const notifyUids = friendsList.filter(fuid => !data.collaboratorUids.includes(fuid));
        for (const fuid of notifyUids) {
          fcmSendPushNotification(fuid, "studySession", displayName, uid, { studyName: data.name });
        }
      }
    }
    return { alreadyDone };
  } catch (e) { console.warn("studyOpenSession:", e); }
}

async function studySaveRhemaPos(studyId, uid, book, chapter, verse, extra = {}) {
  try {
    await updateDoc(doc(db, "studies", studyId), {
      [`rhemaPositions.${uid}`]: { book, chapter, verse, ...extra }
    });
  } catch (e) { console.warn("studySaveRhemaPos:", e); }
}

// Notes
function studyListenNotes(studyId, callback) {
  const q = query(collection(db, "studies", studyId, "notes"), orderBy("createdAt", "asc"));
  return onSnapshot(q, snap => callback(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => { console.warn("studyListenNotes:", err); callback([]); });
}
async function studyAddNote(studyId, uid, displayName, content) {
  try {
    await addDoc(collection(db, "studies", studyId, "notes"), {
      content, authorUid: uid, authorName: displayName, createdAt: serverTimestamp()
    });
    return true;
  } catch (e) { console.warn("studyAddNote:", e); return false; }
}
async function studyDeleteNote(studyId, noteId) {
  try { await deleteDoc(doc(db, "studies", studyId, "notes", noteId)); return true; }
  catch (e) { console.warn("studyDeleteNote:", e); return false; }
}

// Study Workspace Entries (observations / interpretations / applications / questions)
function studyListenEntries(studyId, callback) {
  const q = query(collection(db, "studies", studyId, "entries"), orderBy("createdAt", "asc"));
  return onSnapshot(q, snap => callback(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => { console.warn("studyListenEntries:", err); callback([]); });
}
async function studyAddEntry(studyId, uid, displayName, { type, content, verseRef, verseSnippet }) {
  try {
    await addDoc(collection(db, "studies", studyId, "entries"), {
      type, content,
      verseRef: verseRef || null,
      verseSnippet: verseSnippet || '',
      authorUid: uid, authorName: displayName,
      createdAt: serverTimestamp()
    });
    return true;
  } catch (e) { console.warn("studyAddEntry:", e); return false; }
}
async function studyDeleteEntry(studyId, entryId) {
  try { await deleteDoc(doc(db, "studies", studyId, "entries", entryId)); return true; }
  catch (e) { console.warn("studyDeleteEntry:", e); return false; }
}

// Saved Verses
function studyListenVerses(studyId, callback) {
  const q = query(collection(db, "studies", studyId, "savedVerses"), orderBy("savedAt", "asc"));
  return onSnapshot(q, snap => callback(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => { console.warn("studyListenVerses:", err); callback([]); });
}
async function studySaveVerse(studyId, uid, displayName, { book, chapter, verse, bookName }) {
  try {
    await addDoc(collection(db, "studies", studyId, "savedVerses"), {
      book, chapter, verse, bookName, savedByUid: uid, savedByName: displayName, savedAt: serverTimestamp()
    });
    return true;
  } catch (e) { console.warn("studySaveVerse:", e); return false; }
}
async function studyDeleteVerse(studyId, verseId) {
  try { await deleteDoc(doc(db, "studies", studyId, "savedVerses", verseId)); return true; }
  catch (e) { console.warn("studyDeleteVerse:", e); return false; }
}

// Structured Verses
function studyListenStructures(studyId, callback) {
  const q = query(collection(db, "studies", studyId, "structures"), orderBy("updatedAtMs", "desc"));
  return onSnapshot(q, snap => callback(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => { console.warn("studyListenStructures:", err); callback([]); });
}
async function studySaveStructure(studyId, uid, displayName, structure, structureId = null) {
  try {
    const ref = structureId
      ? doc(db, "studies", studyId, "structures", structureId)
      : doc(collection(db, "studies", studyId, "structures"));
    const now = Date.now();
    await setDoc(ref, {
      ...structure,
      id: ref.id,
      savedByUid: uid,
      savedByName: displayName,
      updatedAtMs: now,
      updatedAt: serverTimestamp(),
      savedAt: structureId ? (structure.savedAt || serverTimestamp()) : serverTimestamp()
    }, { merge: true });
    return ref.id;
  } catch (e) { console.warn("studySaveStructure:", e); return null; }
}
async function studyDeleteStructure(studyId, structureId) {
  try { await deleteDoc(doc(db, "studies", studyId, "structures", structureId)); return true; }
  catch (e) { console.warn("studyDeleteStructure:", e); return false; }
}

// Saved Scripture Trails
function studyListenTrails(studyId, callback) {
  const q = query(collection(db, "studies", studyId, "trails"), orderBy("savedAt", "desc"));
  return onSnapshot(q, snap => callback(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => { console.warn("studyListenTrails:", err); callback([]); });
}
async function studySaveTrail(studyId, uid, displayName, trail) {
  try {
    await addDoc(collection(db, "studies", studyId, "trails"), {
      ...trail,
      savedByUid: uid,
      savedByName: displayName,
      savedAt: serverTimestamp()
    });
    return true;
  } catch (e) { console.warn("studySaveTrail:", e); return false; }
}
async function studyDeleteTrail(studyId, trailId) {
  try { await deleteDoc(doc(db, "studies", studyId, "trails", trailId)); return true; }
  catch (e) { console.warn("studyDeleteTrail:", e); return false; }
}

// Word Log (deduped by Strong's number per study)
function studyListenWordLog(studyId, callback) {
  const q = query(collection(db, "studies", studyId, "wordLog"), orderBy("loggedAt", "asc"));
  return onSnapshot(q, snap => callback(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => { console.warn("studyListenWordLog:", err); callback([]); });
}
async function studyLogWord(studyId, uid, displayName, { lemma, strongs, definition, surface, translit }) {
  try {
    await setDoc(doc(db, "studies", studyId, "wordLog", String(strongs)), {
      lemma, strongs: String(strongs), definition: definition || '', surface, translit: translit || '',
      loggedByUid: uid, loggedByName: displayName, loggedAt: serverTimestamp()
    }, { merge: true });
    return true;
  } catch (e) { console.warn("studyLogWord:", e); return false; }
}
async function studyDeleteWordLog(studyId, wordId) {
  try { await deleteDoc(doc(db, "studies", studyId, "wordLog", wordId)); return true; }
  catch (e) { console.warn("studyDeleteWordLog:", e); return false; }
}

// Collaboration
async function studyRequestCollab(studyId, uid, displayName) {
  try {
    const ref = doc(db, "studies", studyId);
    const snap = await getDoc(ref);
    if (!snap.exists()) return false;
    await updateDoc(ref, { pendingCollaboratorUids: arrayUnion(uid) });
    fcmSendPushNotification(snap.data().creatorUid, "studyCollabRequest", displayName, uid, { studyId, studyName: snap.data().name });
    return true;
  } catch (e) { console.warn("studyRequestCollab:", e); return false; }
}
async function studyApproveCollab(studyId, requesterUid, requesterName) {
  try {
    const ref = doc(db, "studies", studyId);
    await updateDoc(ref, {
      collaboratorUids: arrayUnion(requesterUid),
      pendingCollaboratorUids: arrayRemove(requesterUid)
    });
    const snap = await getDoc(ref);
    const myName = localStorage.getItem("authDisplayName") || "Someone";
    fcmSendPushNotification(requesterUid, "studyCollabApproved", myName, window.Auth?.getCurrentUser()?.uid, { studyId, studyName: snap.data()?.name });
    return true;
  } catch (e) { console.warn("studyApproveCollab:", e); return false; }
}
async function studyDenyCollab(studyId, requesterUid) {
  try {
    await updateDoc(doc(db, "studies", studyId), { pendingCollaboratorUids: arrayRemove(requesterUid) });
    return true;
  } catch (e) { console.warn("studyDenyCollab:", e); return false; }
}

async function studyLeaveCollab(studyId, uid) {
  try {
    const ref = doc(db, "studies", studyId);
    const snap = await getDoc(ref);
    if (!snap.exists()) return false;
    const data = snap.data();
    if (data.creatorUid === uid) return false;
    if (!data.collaboratorUids?.includes(uid)) return false;
    await updateDoc(ref, {
      collaboratorUids: arrayRemove(uid),
      pendingCollaboratorUids: arrayRemove(uid)
    });
    return true;
  } catch (e) { console.warn("studyLeaveCollab:", e); return false; }
}

// Copy a study as your own personal copy (no approval needed)
async function studyCopy(sourceStudyId, uid, displayName) {
  try {
    const snap = await getDoc(doc(db, "studies", sourceStudyId));
    if (!snap.exists()) return null;
    const s = snap.data();
    const ref = await addDoc(collection(db, "studies"), {
      name: s.name, color: s.color, icon: s.icon,
      creatorUid: uid, creatorName: displayName,
      collaboratorUids: [uid], pendingCollaboratorUids: [],
      shareSession: s.shareSession ?? false,
      createdAt: serverTimestamp(), isActive: true,
      rhemaPositions: {}, lastSessionDates: {}, copiedFromId: sourceStudyId
    });
    return {
      id: ref.id, name: s.name, color: s.color, icon: s.icon,
      shareSession: s.shareSession ?? false,
      creatorUid: uid, creatorName: displayName,
      collaboratorUids: [uid], pendingCollaboratorUids: [],
      isActive: true, rhemaPositions: {}, lastSessionDates: {},
      createdAt: { seconds: Math.floor(Date.now() / 1000) }
    };
  } catch (e) { console.warn("studyCopy:", e); return null; }
}

async function studyDeletePermanent(studyId, uid) {
  try {
    const studyRef = doc(db, "studies", studyId);
    const snap = await getDoc(studyRef);
    if (!snap.exists() || snap.data().creatorUid !== uid) return false;
    // Delete all subcollection documents first
    for (const sub of ['notes', 'entries', 'savedVerses', 'wordLog', 'trails', 'structures']) {
      const subSnap = await getDocs(collection(db, "studies", studyId, sub));
      for (const d of subSnap.docs) await deleteDoc(d.ref);
    }
    await deleteDoc(studyRef);
    return true;
  } catch (e) { console.warn("studyDeletePermanent:", e); return false; }
}

// Community Posts
function listenCommunityPosts(uid, friendUids = [], callback) {
  const q = query(collection(db, "communityPosts"), where("audienceUids", "array-contains", uid), limit(80));
  return onSnapshot(q, async snap => {
    const now = Date.now();
    const friendSet = new Set(friendUids || []);
    const posts = snap.docs
      .map(d => ({ id: d.id, ...d.data() }))
      .filter(p => p.isActive !== false)
      .filter(p => !p.expiresAtMs || p.expiresAtMs > now)
      .filter(p => p.authorUid === uid || friendSet.has(p.authorUid))
      .sort((a, b) => (b.createdAtMs || b.createdAt?.seconds * 1000 || 0) - (a.createdAtMs || a.createdAt?.seconds * 1000 || 0));
    const uids = [];
    posts.forEach(post => {
      uids.push(post.authorUid);
      Object.keys(post.reactions || {}).forEach(reactUid => uids.push(reactUid));
      Object.keys(post.prayers || {}).forEach(prayerUid => uids.push(prayerUid));
    });
    const users = await getUsersByUid(uids);
    callback(posts.map(post => {
      const author = users.get(post.authorUid);
      const reactions = {};
      Object.entries(post.reactions || {}).forEach(([reactUid, value]) => {
        const reactor = users.get(reactUid);
        const emoji = typeof value === "string" ? value : value?.emoji;
        reactions[reactUid] = {
          ...(typeof value === "object" && value ? value : {}),
          emoji,
          name: reactor?.displayName || reactor?.username || value?.name || "Friend",
          avatar: reactor?.avatar || value?.avatar || "person"
        };
      });
      return {
        ...post,
        authorName: author?.displayName || author?.username || post.authorName,
        authorAvatar: author?.avatar || post.authorAvatar,
        reactions
      };
    }));
  }, err => {
    console.warn("listenCommunityPosts:", err);
    callback([]);
  });
}

async function addCommunityPost(uid, displayName, avatar, friendUids = [], post = {}) {
  try {
    const now = Date.now();
    const audienceUids = [...new Set([uid, ...(friendUids || [])])];
    const ref = await addDoc(collection(db, "communityPosts"), {
      authorUid: uid,
      authorName: displayName || "Someone",
      authorAvatar: avatar || "person",
      kind: post.kind || "insight",
      body: String(post.body || "").trim(),
      question: String(post.question || "").trim(),
      linkUrl: String(post.linkUrl || "").trim(),
      verse: post.verse || null,
      alertFriends: !!post.alertFriends,
      audienceUids,
      reactions: {},
      commentCount: 0,
      createdAt: serverTimestamp(),
      createdAtMs: now,
      expiresAtMs: now + COMMUNITY_POST_TTL_MS,
      isActive: true
    });
    if (post.alertFriends) {
      for (const fuid of friendUids || []) {
        fcmSendPushNotification(fuid, "communityPost", displayName || "Someone", uid, {
          postId: ref.id,
          postKind: post.kind || "insight"
        });
      }
    }
    return { id: ref.id, createdAtMs: now, expiresAtMs: now + COMMUNITY_POST_TTL_MS };
  } catch (e) {
    console.warn("addCommunityPost:", e);
    return null;
  }
}

async function reactCommunityPost(postId, uid, emoji) {
  try {
    const ref = doc(db, "communityPosts", postId);
    const snap = await getDoc(ref);
    if (!snap.exists()) return false;
    const data = snap.data();
    const current = data.reactions?.[uid];
    const currentEmoji = typeof current === "string" ? current : current?.emoji;
    const fromName = localStorage.getItem("authDisplayName") || localStorage.getItem("authUsername") || "Someone";
    const fromAvatar = getAvatar();
    await updateDoc(ref, {
      [`reactions.${uid}`]: currentEmoji === emoji
        ? deleteField()
        : { emoji, name: fromName, avatar: fromAvatar, reactedAtMs: Date.now() }
    });
    if (currentEmoji !== emoji && data.authorUid && data.authorUid !== uid) {
      fcmSendPushNotification(data.authorUid, "postReaction", fromName, uid, {
        postId,
        emoji,
        postTitle: communityPostTitle(data)
      });
    }
    return true;
  } catch (e) {
    console.warn("reactCommunityPost:", e);
    return false;
  }
}

function communityPostTitle(post = {}) {
  const raw = post.question || post.verse?.ref || post.body || "your post";
  const text = String(raw).replace(/\s+/g, " ").trim();
  return text.length > 46 ? text.slice(0, 43) + "..." : text || "your post";
}

function listenPostComments(postId, callback) {
  const q = query(collection(db, "communityPosts", postId, "comments"), orderBy("createdAtMs", "asc"), limit(80));
  return onSnapshot(q, snap => callback(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => { console.warn("listenPostComments:", err); callback([]); });
}

async function addPostComment(postId, uid, text) {
  try {
    const clean = String(text || "").trim();
    if (!clean) return false;
    const postRef = doc(db, "communityPosts", postId);
    const postSnap = await getDoc(postRef);
    if (!postSnap.exists()) return false;
    const post = postSnap.data();
    const fromName = localStorage.getItem("authDisplayName") || localStorage.getItem("authUsername") || "Someone";
    const fromAvatar = getAvatar();
    await addDoc(collection(db, "communityPosts", postId, "comments"), {
      body: clean,
      authorUid: uid,
      authorName: fromName,
      authorAvatar: fromAvatar,
      createdAt: serverTimestamp(),
      createdAtMs: Date.now()
    });
    await updateDoc(postRef, { commentCount: increment(1) });
    if (post.authorUid && post.authorUid !== uid) {
      fcmSendPushNotification(post.authorUid, "postComment", fromName, uid, {
        postId,
        postTitle: communityPostTitle(post)
      });
    }
    return true;
  } catch (e) {
    console.warn("addPostComment:", e);
    return false;
  }
}

async function prayForPost(postId, uid) {
  try {
    const postRef = doc(db, "communityPosts", postId);
    const postSnap = await getDoc(postRef);
    if (!postSnap.exists()) return false;
    const post = postSnap.data();
    const fromName = localStorage.getItem("authDisplayName") || localStorage.getItem("authUsername") || "Someone";
    const fromAvatar = getAvatar();
    await updateDoc(postRef, {
      [`prayers.${uid}`]: { name: fromName, avatar: fromAvatar, prayedAtMs: Date.now() }
    });
    if (post.authorUid && post.authorUid !== uid) {
      fcmSendPushNotification(post.authorUid, "postPrayer", fromName, uid, {
        postId,
        postTitle: communityPostTitle(post)
      });
    }
    return true;
  } catch (e) {
    console.warn("prayForPost:", e);
    return false;
  }
}

async function deleteCommunityPost(postId, uid) {
  try {
    const ref = doc(db, "communityPosts", postId);
    const snap = await getDoc(ref);
    if (!snap.exists() || snap.data().authorUid !== uid) return false;
    await updateDoc(ref, { isActive: false, deletedAt: serverTimestamp() });
    return true;
  } catch (e) {
    console.warn("deleteCommunityPost:", e);
    return false;
  }
}

// Listen for incoming encouragement messages (for in-app notifications)
function listenEncouragements(uid, callback) {
  // No orderBy — avoids needing a composite index; sort client-side
  const q = query(collection(db, "encouragements", uid, "messages"), limit(40));
  return onSnapshot(q, snap => {
    const msgs = snap.docs.map(d => ({ id: d.id, ...d.data() }));
    msgs.sort((a, b) => (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0));
    callback(msgs);
  }, err => console.warn("listenEncouragements:", err));
}

async function getEncouragementMessages(uid) {
  try {
    const q = query(collection(db, "encouragements", uid, "messages"), limit(40));
    const snap = await getDocs(q);
    const msgs = snap.docs.map(d => ({ id: d.id, ...d.data() }));
    msgs.sort((a, b) => (b.createdAt?.seconds || 0) - (a.createdAt?.seconds || 0));
    return msgs;
  } catch (e) {
    console.warn("getEncouragementMessages:", e);
    return [];
  }
}

// Habits
function habitIdFromName(name) {
  const slug = String(name || "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 54);
  return slug || `habit-${Date.now()}`;
}

function listenHabits(uid, callback) {
  const habitsData = {};
  const entriesData = {};
  const entryUnsubs = {};
  let habitOrder = [];

  function emit() {
    callback(habitOrder.map(id => ({ ...habitsData[id], entries: entriesData[id] || {} })));
  }

  const habitsUnsub = onSnapshot(
    query(collection(db, "users", uid, "habits"), orderBy("createdAtMs", "asc")),
    snap => {
      const newIds = snap.docs.map(d => d.id);
      snap.docs.forEach(d => { habitsData[d.id] = { id: d.id, ...d.data() }; });
      habitOrder = newIds;

      Object.keys(entryUnsubs).forEach(id => {
        if (!newIds.includes(id)) {
          entryUnsubs[id]();
          delete entryUnsubs[id];
          delete habitsData[id];
          delete entriesData[id];
        }
      });

      newIds.forEach(id => {
        if (entryUnsubs[id]) return;
        entryUnsubs[id] = onSnapshot(
          collection(db, "users", uid, "habits", id, "entries"),
          entrySnap => {
            const entries = {};
            entrySnap.docs.forEach(e => { entries[e.id] = { id: e.id, ...e.data() }; });
            entriesData[id] = entries;
            emit();
          },
          err => console.warn("listenEntries:", id, err)
        );
      });

      emit();
    },
    err => console.warn("listenHabits:", err)
  );

  return () => {
    habitsUnsub();
    Object.values(entryUnsubs).forEach(u => u());
  };
}

async function habitOwnerName(uid) {
  const user = await frGetUser(uid).catch(() => null);
  return user?.displayName || user?.username || "Someone";
}

async function notifyHabitPartners(uid, friendUids = [], type, habitId, habitName, date) {
  const fromName = await habitOwnerName(uid);
  await Promise.all([...new Set(friendUids || [])]
    .filter(friendUid => friendUid && friendUid !== uid)
    .map(friendUid => {
      // Deterministic doc ID ensures only one Cloud Function onCreate fires per
      // (habit, date, recipient) regardless of how many times the entry is written.
      const dedupeKey = `habit_${habitId}_${date}_${friendUid}`;
      return fcmSendPushNotification(friendUid, type, fromName, uid, { habitId, habitName }, dedupeKey);
    }));
}

function habitEncouragementId(toUid, habitId, dateKey) {
  return [dateKey, toUid, habitId].map(part => String(part || "").replace(/[^a-zA-Z0-9_-]/g, "-")).join("_");
}

async function sendHabitEncouragementOnce(fromUid, toUid, habitId, habitName, dateKey) {
  try {
    if (!fromUid || !toUid || fromUid === toUid || !habitId || !dateKey) {
      return { ok: false, reason: "invalid" };
    }
    const sentRef = doc(db, "users", fromUid, "habitEncouragements", habitEncouragementId(toUid, habitId, dateKey));
    const existing = await getDoc(sentRef);
    if (existing.exists()) return { ok: false, reason: "alreadySent" };

    const fromName = await habitOwnerName(fromUid);
    const cleanHabitName = String(habitName || "habit").trim() || "habit";
    const sent = await fcmSendPushNotification(toUid, "habitEncouragement", fromName, fromUid, {
      habitId,
      habitName: cleanHabitName,
      dateKey
    });
    if (!sent) return { ok: false, reason: "notificationFailed" };

    await setDoc(sentRef, {
      toUid,
      habitId,
      habitName: cleanHabitName,
      dateKey,
      createdAt: serverTimestamp(),
      createdAtMs: Date.now()
    });
    return { ok: true };
  } catch (e) {
    console.warn("sendHabitEncouragementOnce:", e);
    return { ok: false, reason: "error" };
  }
}

async function createHabit(uid, { name, description = "", scheduleType = "daily", accountabilityUids = [], icon = "menu_book", color = "" } = {}) {
  try {
    const habitId = habitIdFromName(name);
    const partners = [...new Set(accountabilityUids || [])].filter(friendUid => friendUid && friendUid !== uid);
    await setDoc(doc(db, "users", uid, "habits", habitId), {
      ownerUid: uid,
      name: String(name || "").trim(),
      description: String(description || "").trim(),
      icon: String(icon || "menu_book"),
      color: String(color || ""),
      schedule: { type: scheduleType || "daily" },
      shareUids: [],
      accountabilityUids: partners,
      awardedMilestones: [],
      source: "disciple-builder",
      createdAt: serverTimestamp(),
      createdAtMs: Date.now(),
      updatedAt: serverTimestamp()
    }, { merge: true });
    await notifyHabitPartners(uid, partners, "habitAccountabilityAdded", habitId, String(name || "").trim());
    return habitId;
  } catch (e) {
    console.warn("createHabit:", e);
    return null;
  }
}

async function updateHabit(uid, habitId, { name, description = "", scheduleType = "daily", accountabilityUids = [], icon = "menu_book", color = "" } = {}) {
  try {
    const habitRef = doc(db, "users", uid, "habits", habitId);
    const before = await getDoc(habitRef);
    if (!before.exists()) return false;
    const previousPartners = new Set(before.data().accountabilityUids || before.data().shareUids || []);
    const partners = [...new Set(accountabilityUids || [])].filter(friendUid => friendUid && friendUid !== uid);
    await setDoc(habitRef, {
      name: String(name || "").trim(),
      description: String(description || "").trim(),
      icon: String(icon || "menu_book"),
      color: String(color || ""),
      schedule: { type: scheduleType || before.data().schedule?.type || "daily" },
      accountabilityUids: partners,
      updatedAt: serverTimestamp(),
      updatedAtMs: Date.now()
    }, { merge: true });
    const added = partners.filter(friendUid => !previousPartners.has(friendUid));
    if (added.length) await notifyHabitPartners(uid, added, "habitAccountabilityAdded", habitId, String(name || before.data().name || "habit").trim());
    return true;
  } catch (e) {
    console.warn("updateHabit:", e);
    return false;
  }
}

async function deleteHabit(uid, habitId) {
  try {
    const entries = await getDocs(collection(db, "users", uid, "habits", habitId, "entries"));
    let batch = writeBatch(db);
    let writes = 0;
    for (const entryDoc of entries.docs) {
      batch.delete(entryDoc.ref);
      writes++;
      if (writes >= 420) {
        await batch.commit();
        batch = writeBatch(db);
        writes = 0;
      }
    }
    batch.delete(doc(db, "users", uid, "habits", habitId));
    await batch.commit();
    return true;
  } catch (e) {
    console.warn("deleteHabit:", e);
    return false;
  }
}

async function awardHabitMilestone(uid, habitId, milestone) {
  try {
    await updateDoc(doc(db, "users", uid, "habits", habitId), {
      awardedMilestones: arrayUnion(String(milestone)),
      updatedAt: serverTimestamp(),
      updatedAtMs: Date.now()
    });
    return true;
  } catch (e) {
    console.warn("awardHabitMilestone:", e);
    return false;
  }
}

async function setHabitEntry(uid, habitId, { date, status, comment = "", source = "disciple-builder", notify = false } = {}) {
  try {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(String(date || ""))) return false;
    await setDoc(doc(db, "users", uid, "habits", habitId, "entries", date), {
      date,
      status: status || "open",
      comment: String(comment || ""),
      source,
      updatedAt: serverTimestamp(),
      updatedAtMs: Date.now()
    }, { merge: true });
    await setDoc(doc(db, "users", uid, "habits", habitId), {
      updatedAt: serverTimestamp(),
      updatedAtMs: Date.now()
    }, { merge: true });
    if (notify && (status === "success" || status === "skipped")) {
      const habitSnap = await getDoc(doc(db, "users", uid, "habits", habitId));
      const habit = habitSnap.exists() ? habitSnap.data() : {};
      const partners = habit.accountabilityUids || habit.shareUids || [];
      const type = status === "success" ? "habitCompleted" : "habitSkipped";
      await notifyHabitPartners(uid, partners, type, habitId, habit.name || "habit", date);
    }
    return true;
  } catch (e) {
    console.warn("setHabitEntry:", e);
    return false;
  }
}

// Bulk-write per-day entries (used by Reading Plan to seed each day's reference
// into the habit note calendar). entries: [{ date, comment, status }].
async function setHabitEntriesBulk(uid, habitId, entries = []) {
  try {
    let batch = writeBatch(db);
    let writes = 0;
    for (const e of entries) {
      if (!/^\d{4}-\d{2}-\d{2}$/.test(String(e.date || ""))) continue;
      batch.set(doc(db, "users", uid, "habits", habitId, "entries", e.date), {
        date: e.date,
        status: e.status || "open",
        comment: String(e.comment || ""),
        source: "reading-plan",
        updatedAt: serverTimestamp(),
        updatedAtMs: Date.now()
      }, { merge: true });
      writes++;
      if (writes >= 400) { await batch.commit(); batch = writeBatch(db); writes = 0; }
    }
    if (writes > 0) await batch.commit();
    await setDoc(doc(db, "users", uid, "habits", habitId), {
      updatedAt: serverTimestamp(), updatedAtMs: Date.now()
    }, { merge: true });
    return true;
  } catch (e) {
    console.warn("setHabitEntriesBulk:", e);
    return false;
  }
}

async function importHabitShare(uid, rows = []) {
  try {
    const byHabit = {};
    rows.forEach(row => {
      const name = String(row.habit || "").trim();
      if (!name || !row.date) return;
      if (!byHabit[name]) byHabit[name] = [];
      byHabit[name].push(row);
    });
    const habitNames = Object.keys(byHabit);
    let batch = writeBatch(db);
    let writes = 0;
    let totalEntries = 0;
    const commitIfNeeded = async (force = false) => {
      if (writes && (force || writes >= 420)) {
        await batch.commit();
        batch = writeBatch(db);
        writes = 0;
      }
    };

    for (const name of habitNames) {
      const habitId = habitIdFromName(name);
      const habitRef = doc(db, "users", uid, "habits", habitId);
      const firstDateMs = byHabit[name].reduce((min, row) => Math.min(min, Date.parse(`${row.date}T00:00:00`) || Date.now()), Date.now());
      const existingHabit = await getDoc(habitRef).catch(() => null);

      const habitPayload = {
        ownerUid: uid,
        name,
        source: "habitshare-import",
        importedAt: serverTimestamp(),
        createdAtMs: existingHabit?.exists() ? (existingHabit.data().createdAtMs || firstDateMs) : firstDateMs,
        updatedAt: serverTimestamp()
      };
      if (!existingHabit?.exists()) {
        habitPayload.description = "";
        habitPayload.schedule = { type: "daily" };
        habitPayload.accountabilityUids = [];
        habitPayload.awardedMilestones = [];
      }
      batch.set(habitRef, habitPayload, { merge: true });
      writes++;
      await commitIfNeeded();

      for (const row of byHabit[name]) {
        const entryRef = doc(db, "users", uid, "habits", habitId, "entries", row.date);
        batch.set(entryRef, {
          date: row.date,
          status: row.status || "open",
          comment: String(row.comment || ""),
          source: "habitshare-import",
          sourceRow: row.sourceRow || null,
          importedAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
          updatedAtMs: Date.now()
        }, { merge: true });
        writes++;
        totalEntries++;
        await commitIfNeeded();
      }
    }

    await commitIfNeeded(true);
    return { habits: habitNames.length, entries: totalEntries };
  } catch (e) {
    console.warn("importHabitShare:", e);
    return null;
  }
}

async function getFriendHabits(friendUid) {
  try {
    const habitsSnap = await getDocs(
      query(collection(db, "users", friendUid, "habits"), orderBy("createdAtMs", "asc"))
    );
    if (habitsSnap.empty) return [];
    const habits = habitsSnap.docs.map(d => ({ id: d.id, ...d.data(), entries: {} }));
    await Promise.all(habits.map(async (habit, i) => {
      try {
        const entriesSnap = await getDocs(collection(db, "users", friendUid, "habits", habit.id, "entries"));
        entriesSnap.docs.forEach(e => { habits[i].entries[e.id] = e.data(); });
      } catch {}
    }));
    return habits;
  } catch (e) {
    console.warn("getFriendHabits:", friendUid, e);
    return [];
  }
}

window.Habits = {
  listen: listenHabits,
  create: createHabit,
  setEntry: setHabitEntry,
  setEntriesBulk: setHabitEntriesBulk,
  update: updateHabit,
  delete: deleteHabit,
  awardMilestone: awardHabitMilestone,
  encourage: sendHabitEncouragementOnce,
  importHabitShare,
  getFriendHabits,
  sendHabitEncouragement: sendHabitEncouragementOnce
};

window.Studies = {
  create: studyCreate, get: studyGet, getMine: studyGetMine, getFriends: studyGetFriends,
  openSession: studyOpenSession, saveRhemaPos: studySaveRhemaPos,
  listenStudy: studyListen,
  listenNotes: studyListenNotes, addNote: studyAddNote, deleteNote: studyDeleteNote,
  listenEntries: studyListenEntries, addEntry: studyAddEntry, deleteEntry: studyDeleteEntry,
  listenVerses: studyListenVerses, saveVerse: studySaveVerse, deleteVerse: studyDeleteVerse,
  listenStructures: studyListenStructures, saveStructure: studySaveStructure, deleteStructure: studyDeleteStructure,
  listenTrails: studyListenTrails, saveTrail: studySaveTrail, deleteTrail: studyDeleteTrail,
  listenWordLog: studyListenWordLog, logWord: studyLogWord, deleteWordLog: studyDeleteWordLog,
  requestCollab: studyRequestCollab, approveCollab: studyApproveCollab, denyCollab: studyDenyCollab, leaveCollab: studyLeaveCollab,
  inviteCollab: studyInviteCollab, selfApproveInvite: studySelfApproveInvite,
  copy: studyCopy, delete: studyDeletePermanent, listenEncouragements, getEncouragementMessages,
  deleteMsg: deleteEncouragementMsg,
  getMemberNames: studyGetMemberNames
};

window.CommunityPosts = {
  listen: listenCommunityPosts,
  add: addCommunityPost,
  react: reactCommunityPost,
  listenComments: listenPostComments,
  addComment: addPostComment,
  pray: prayForPost,
  delete: deleteCommunityPost
};

function listenMerciesPosts(uid, friendUids = [], callback) {
  const q = query(
    collection(db, "merciesPosts"),
    where("audienceUids", "array-contains", uid),
    orderBy("createdAtMs", "desc"),
    limit(120)
  );
  return onSnapshot(q, async snap => {
    const now = Date.now();
    const friendSet = new Set(friendUids || []);
    const posts = snap.docs
      .map(d => ({ id: d.id, ...d.data() }))
      .filter(p => p.isActive !== false)
      .filter(p => !p.expiresAtMs || p.expiresAtMs > now)
      .filter(p => p.authorUid === uid || friendSet.has(p.authorUid))
      .sort((a, b) => (b.createdAtMs || b.createdAt?.seconds * 1000 || 0) - (a.createdAtMs || a.createdAt?.seconds * 1000 || 0));
    const uids = [];
    posts.forEach(post => {
      uids.push(post.authorUid, post.taggedFriendUid);
      (post.taggedFriendUids || []).forEach(tagUid => uids.push(tagUid));
      Object.keys(post.reactions || {}).forEach(reactUid => uids.push(reactUid));
    });
    const users = await getUsersByUid(uids);
    callback(posts.map(post => {
      const author = users.get(post.authorUid);
      const reactions = {};
      Object.entries(post.reactions || {}).forEach(([reactUid, value]) => {
        const reactor = users.get(reactUid);
        const label = typeof value === "string" ? value : value?.label;
        reactions[reactUid] = {
          ...(typeof value === "object" && value ? value : {}),
          label,
          name: reactor?.displayName || reactor?.username || value?.name || "Friend",
          avatar: reactor?.avatar || value?.avatar || "person"
        };
      });
      return {
        ...post,
        authorName: author?.displayName || author?.username || post.authorName,
        authorAvatar: author?.avatar || post.authorAvatar,
        taggedFriendName: users.get(post.taggedFriendUid)?.displayName || post.taggedFriendName || null,
        taggedFriendNames: (post.taggedFriendUids || []).map(tagUid => users.get(tagUid)?.displayName || users.get(tagUid)?.username).filter(Boolean).concat(post.taggedFriendNames || []).filter((name, i, arr) => name && arr.indexOf(name) === i),
        reactions
      };
    }));
  }, err => {
    console.warn("listenMerciesPosts:", err);
    callback([]);
  });
}

async function addMercyPost(uid, displayName, avatar, friendUids = [], imageBlob, post = {}) {
  try {
    if (imageBlob && !(imageBlob instanceof Blob) && typeof imageBlob === "object") {
      post = imageBlob;
      imageBlob = post.imageBlob || post.optimizedImageBlob || post.blob || null;
    }
    const now = Date.now();
    const ref = doc(collection(db, "merciesPosts"));
    let imagePath = null;
    let imageUrl = null;
    if (imageBlob) {
      const ext = imageBlob.type?.includes("webp") ? "webp" : "jpg";
      imagePath = `mercies/${uid}/${ref.id}.${ext}`;
      const imageRef = storageRef(storage, imagePath);
      await uploadBytes(imageRef, imageBlob, { contentType: imageBlob.type || "image/jpeg" });
      imageUrl = await getDownloadURL(imageRef);
    }
    const audienceUids = [...new Set([uid, ...(friendUids || [])])];
    await setDoc(ref, {
      authorUid: uid,
      authorName: displayName || "Someone",
      authorAvatar: avatar || "person",
      body: String(post.body || "").trim(),
      promptText: post.promptText || "",
      promptCategory: post.promptCategory || "Daily Praise",
      promptMode: post.promptMode || "guided",
      imageUrl,
      imagePath,
      photoMode: post.photoMode || (imageUrl ? "full" : null),
      imageAspectRatio: Number(post.imageAspectRatio || 0) || null,
      scripture: post.scripture || null,
      scriptureCard: post.scriptureCard || null,
      taggedFriendUid: post.taggedFriendUid || null,
      taggedFriendName: post.taggedFriendName || null,
      taggedFriendUids: post.taggedFriendUids || (post.taggedFriendUid ? [post.taggedFriendUid] : []),
      taggedFriendNames: post.taggedFriendNames || (post.taggedFriendName ? [post.taggedFriendName] : []),
      friendEncouragement: !!post.friendEncouragement,
      audienceUids,
      reactions: {},
      commentCount: 0,
      journalSavedBy: [],
      createdAt: serverTimestamp(),
      createdAtMs: now,
      expiresAtMs: now + MERCY_POST_TTL_MS,
      isActive: true
    });
    const streakDays = await advanceMercyStreak(uid, now);
    [...new Set([post.taggedFriendUid, ...(post.taggedFriendUids || [])].filter(Boolean))]
      .filter(tagUid => tagUid !== uid)
      .forEach(tagUid => {
        fcmSendPushNotification(tagUid, "mercyPostedTagged", displayName || "Someone", uid, {
          mercyPostId: ref.id
        });
      });
    return { id: ref.id, imageUrl, imagePath, createdAtMs: now, expiresAtMs: now + MERCY_POST_TTL_MS, streakDays };
  } catch (e) {
    console.warn("addMercyPost:", e);
    return null;
  }
}

function mercyDateKey(ms = Date.now()) {
  const d = new Date(ms);
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

async function advanceMercyStreak(uid, now = Date.now()) {
  try {
    const userRef = doc(db, "users", uid);
    const snap = await getDoc(userRef);
    const data = snap.exists() ? snap.data() : {};
    const today = mercyDateKey(now);
    if (data.mercyLastPostDate === today) return data.mercyStreakDays || 1;
    const _yd = new Date(now); _yd.setDate(_yd.getDate() - 1);
    const yesterday = mercyDateKey(_yd.getTime());
    const nextStreak = data.mercyLastPostDate === yesterday ? (data.mercyStreakDays || 0) + 1 : 1;
    await setDoc(userRef, {
      mercyLastPostDate: today,
      mercyStreakDays: nextStreak,
      mercyPostDays: arrayUnion(today),
      updatedAt: serverTimestamp()
    }, { merge: true });
    return nextStreak;
  } catch (e) {
    console.warn("advanceMercyStreak:", e);
    return null;
  }
}

async function reactMercyPost(postId, uid, label) {
  try {
    const ref = doc(db, "merciesPosts", postId);
    const snap = await getDoc(ref);
    if (!snap.exists()) return false;
    const data = snap.data();
    const current = data.reactions?.[uid];
    const currentLabel = typeof current === "string" ? current : current?.label;
    await updateDoc(ref, {
      [`reactions.${uid}`]: currentLabel === label
        ? deleteField()
        : { label, name: getLbDisplayName(), avatar: getAvatar(), reactedAtMs: Date.now() }
    });
    return true;
  } catch (e) {
    console.warn("reactMercyPost:", e);
    return false;
  }
}

function mercyPostTitle(post = {}) {
  const raw = post.scripture?.ref || post.promptCategory || post.body || "your Praise";
  const text = String(raw).replace(/\s+/g, " ").trim();
  return text.length > 46 ? text.slice(0, 43) + "..." : text || "your Praise";
}

function listenMercyComments(postId, callback) {
  const q = query(collection(db, "merciesPosts", postId, "comments"), orderBy("createdAtMs", "asc"), limit(80));
  return onSnapshot(q, snap => callback(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => { console.warn("listenMercyComments:", err); callback([]); });
}

async function addMercyComment(postId, uid, text) {
  try {
    const clean = String(text || "").trim();
    if (!clean) return false;
    const postRef = doc(db, "merciesPosts", postId);
    const postSnap = await getDoc(postRef);
    if (!postSnap.exists()) return false;
    const post = postSnap.data();
    const fromName = localStorage.getItem("authDisplayName") || localStorage.getItem("authUsername") || "Someone";
    const fromAvatar = getAvatar();
    await addDoc(collection(db, "merciesPosts", postId, "comments"), {
      body: clean,
      authorUid: uid,
      authorName: fromName,
      authorAvatar: fromAvatar,
      createdAt: serverTimestamp(),
      createdAtMs: Date.now()
    });
    await updateDoc(postRef, { commentCount: increment(1) });
    if (post.authorUid && post.authorUid !== uid) {
      fcmSendPushNotification(post.authorUid, "mercyComment", fromName, uid, {
        mercyPostId: postId,
        postTitle: mercyPostTitle(post)
      });
    }
    return true;
  } catch (e) {
    console.warn("addMercyComment:", e);
    return false;
  }
}

async function deleteMercyPost(postId, uid) {
  try {
    const ref = doc(db, "merciesPosts", postId);
    const snap = await getDoc(ref);
    if (!snap.exists()) return false;
    const data = snap.data();
    if (data.authorUid !== uid) return false;
    await updateDoc(ref, { isActive: false, deletedAt: serverTimestamp() });
    if (data.imagePath && !(data.journalSavedBy || []).length) {
      deleteObject(storageRef(storage, data.imagePath)).catch(() => {});
    }
    return true;
  } catch (e) {
    console.warn("deleteMercyPost:", e);
    return false;
  }
}

function mercyJournalPayload(uid, post = {}) {
  const createdAtMs = post.createdAtMs || Date.now();
  return {
    remotePostId: post.id || post.remotePostId || null,
    authorUid: uid,
    date: post.date || new Date(createdAtMs).toLocaleDateString(),
    createdAtMs,
    savedAt: serverTimestamp(),
    savedAtMs: Date.now(),
    promptText: post.promptText || "",
    promptCategory: post.promptCategory || "Praise",
    body: post.body || "",
    imageUrl: post.imageUrl || null,
    imagePath: post.imagePath || null,
    scripture: post.scripture || null,
    scriptureCard: post.scriptureCard || null,
    taggedFriendUid: post.taggedFriendUid || null,
    taggedFriendName: post.taggedFriendName || null,
    taggedFriendUids: post.taggedFriendUids || [],
    taggedFriendNames: post.taggedFriendNames || [],
    friendEncouragement: !!post.friendEncouragement,
    isDeleted: false
  };
}

async function saveMercyJournalEntry(uid, post = {}) {
  if (!uid) return false;
  try {
    const entryId = post.id || post.remotePostId || crypto.randomUUID();
    const payload = mercyJournalPayload(uid, post);
    await setDoc(doc(db, "users", uid, "merciesJournal", entryId), payload, { merge: true });
    if (payload.remotePostId) {
      updateDoc(doc(db, "merciesPosts", payload.remotePostId), {
        journalSavedBy: arrayUnion(uid)
      }).catch(() => {});
    }
    return entryId;
  } catch (e) {
    console.warn("saveMercyJournalEntry:", e);
    return false;
  }
}

function listenMercyJournal(uid, callback) {
  if (!uid) return () => {};
  const q = query(
    collection(db, "users", uid, "merciesJournal"),
    orderBy("createdAtMs", "desc"),
    limit(120)
  );
  return onSnapshot(q, snap => {
    const entries = snap.docs
      .map(d => ({ id: d.id, localId: d.id, ...d.data() }))
      .filter(entry => entry.isDeleted !== true);
    callback(entries);
  }, err => {
    console.warn("listenMercyJournal:", err);
    callback([]);
  });
}

async function deleteMercyJournalEntry(uid, entryId) {
  if (!uid || !entryId) return false;
  try {
    const entryRef = doc(db, "users", uid, "merciesJournal", entryId);
    const entrySnap = await getDoc(entryRef);
    if (!entrySnap.exists()) return false;
    const entry = entrySnap.data();
    await deleteDoc(entryRef);
    if (entry.remotePostId) {
      const postRef = doc(db, "merciesPosts", entry.remotePostId);
      const postSnap = await getDoc(postRef).catch(() => null);
      if (postSnap?.exists()) {
        const post = postSnap.data();
        await updateDoc(postRef, { journalSavedBy: arrayRemove(uid) }).catch(() => {});
        const remaining = (post.journalSavedBy || []).filter(savedUid => savedUid !== uid);
        const expired = post.expiresAtMs && post.expiresAtMs <= Date.now();
        if ((post.isActive === false || expired) && !remaining.length && post.imagePath) {
          deleteObject(storageRef(storage, post.imagePath)).catch(() => {});
        }
      } else if (entry.imagePath) {
        deleteObject(storageRef(storage, entry.imagePath)).catch(() => {});
      }
    }
    return true;
  } catch (e) {
    console.warn("deleteMercyJournalEntry:", e);
    return false;
  }
}

async function saveMerciesSettings(uid, settings = {}) {
  if (!uid) return false;
  try {
    await setDoc(doc(db, "users", uid), {
      merciesSettings: {
        dailyEnabled: !!settings.dailyEnabled,
        dailyTime: settings.dailyTime || "20:00",
        friendEnabled: !!settings.friendEnabled,
        friendTime: settings.friendTime || "18:00",
        autoSave: !!settings.autoSave,
        updatedAtMs: Date.now()
      },
      mercyReminder: {
        enabled: !!settings.dailyEnabled,
        time: settings.dailyTime || "20:00",
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC"
      },
      mercyFriendReminder: {
        enabled: !!settings.friendEnabled,
        time: settings.friendTime || "18:00",
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC"
      }
    }, { merge: true });
    return true;
  } catch (e) {
    console.warn("saveMerciesSettings:", e);
    return false;
  }
}

window.Mercies = {
  listen: listenMerciesPosts,
  add: addMercyPost,
  react: reactMercyPost,
  listenComments: listenMercyComments,
  addComment: addMercyComment,
  delete: deleteMercyPost,
  saveJournal: saveMercyJournalEntry,
  listenJournal: listenMercyJournal,
  deleteJournal: deleteMercyJournalEntry,
  saveSettings: saveMerciesSettings,
  clearPendingFriendEncouragement: clearPendingMercyFriendEncouragement
};

async function studyGetMemberNames(uids) {
  if (!uids?.length) return [];
  try {
    const snaps = await Promise.all(uids.map(uid => getDoc(doc(db, 'users', uid)).catch(() => null)));
    return snaps.map((snap, i) => ({
      uid: uids[i],
      name: snap?.exists() ? (snap.data().displayName || snap.data().username || 'Member') : 'Member'
    }));
  } catch (e) { console.warn('getMemberNames:', e); return uids.map(uid => ({ uid, name: 'Member' })); }
}

async function fcmRegisterToken(uid) {
  if (!messaging) throw new Error("Firebase messaging not available on this browser.");
  const reg = await navigator.serviceWorker.ready;
  const token = await getToken(messaging, {
    vapidKey: FCM_VAPID_KEY,
    serviceWorkerRegistration: reg
  });
  if (token) {
    const syncedToken = localStorage.getItem("fcmToken");
    const syncedUid = localStorage.getItem("fcmTokenUid");
    const syncedAt = Number(localStorage.getItem("fcmTokenSyncedAt") || 0);
    if (syncedToken === token && syncedUid === uid && Date.now() - syncedAt < 24 * 60 * 60 * 1000) {
      return token;
    }
    await setDoc(doc(db, "users", uid), { fcmTokens: arrayUnion(token) }, { merge: true });
    localStorage.setItem("fcmToken", token);
    localStorage.setItem("fcmTokenUid", uid);
    localStorage.setItem("fcmTokenSyncedAt", String(Date.now()));
  }
  return token || null;
}

async function fcmRemoveToken(uid, token) {
  try {
    await setDoc(doc(db, "users", uid), { fcmTokens: arrayRemove(token) }, { merge: true });
    localStorage.removeItem("fcmToken");
    localStorage.removeItem("fcmTokenUid");
    localStorage.removeItem("fcmTokenSyncedAt");
  } catch (e) {
    console.warn("fcmRemoveToken:", e);
  }
}

function getReminderLocalParts(date, timeZone) {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone,
    weekday: "short",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false
  }).formatToParts(date);
  const pick = type => parts.find(p => p.type === type)?.value;
  const hour = Number(pick("hour"));
  return {
    year: Number(pick("year")),
    month: Number(pick("month")),
    day: Number(pick("day")),
    weekday: pick("weekday"),
    hour: hour === 24 ? 0 : hour,
    minute: Number(pick("minute"))
  };
}

function reminderLocalToUtc({ year, month, day, hour, minute }, timeZone) {
  const utcGuess = Date.UTC(year, month - 1, day, hour, minute);
  const localAtGuess = getReminderLocalParts(new Date(utcGuess), timeZone);
  const localAsUtc = Date.UTC(
    localAtGuess.year,
    localAtGuess.month - 1,
    localAtGuess.day,
    localAtGuess.hour,
    localAtGuess.minute
  );
  return new Date(utcGuess - (localAsUtc - utcGuess));
}

function reminderFrequencyAllowsDay(frequency, weekday) {
  const isWeekday = ["Mon", "Tue", "Wed", "Thu", "Fri"].includes(weekday);
  const isWeekend = ["Sat", "Sun"].includes(weekday);
  if (frequency === "weekdays") return isWeekday;
  if (frequency === "weekends") return isWeekend;
  return true;
}

function calculateReminderNextSendAt({ time, frequency, timezone }, afterDate = new Date()) {
  const [hour, minute] = String(time || "").split(":").map(Number);
  if (!Number.isInteger(hour) || !Number.isInteger(minute)) return null;
  const timeZone = timezone || "UTC";
  const base = getReminderLocalParts(afterDate, timeZone);
  for (let offset = 0; offset <= 8; offset++) {
    const localDay = new Date(Date.UTC(base.year, base.month - 1, base.day + offset));
    const candidate = reminderLocalToUtc({
      year: localDay.getUTCFullYear(),
      month: localDay.getUTCMonth() + 1,
      day: localDay.getUTCDate(),
      hour,
      minute
    }, timeZone);
    const local = getReminderLocalParts(candidate, timeZone);
    if (!reminderFrequencyAllowsDay(frequency || "daily", local.weekday)) continue;
    if (candidate > afterDate) return candidate;
  }
  return null;
}

async function fcmSaveReminder(uid, { time, frequency, timezone }) {
  try {
    const nextSendAt = calculateReminderNextSendAt({ time, frequency, timezone });
    await setDoc(doc(db, "users", uid), {
      reminder: { enabled: true, time, frequency, timezone, lastSent: null, nextSendAt },
      updatedAt: serverTimestamp()
    }, { merge: true });
    return true;
  } catch (e) {
    console.warn("fcmSaveReminder:", e);
    return false;
  }
}

async function fcmDisableReminder(uid) {
  try {
    await setDoc(doc(db, "users", uid), {
      reminder: { enabled: false },
      updatedAt: serverTimestamp()
    }, { merge: true });
    return true;
  } catch (e) {
    console.warn("fcmDisableReminder:", e);
    return false;
  }
}

async function fcmSendEncouragement(fromUid, fromName, toUid) {
  return fcmSendPushNotification(toUid, "encouragement", fromName, fromUid);
}

async function fcmSendHabitEncouragement(fromUid, fromName, toUid, habitId, habitName) {
  return fcmSendPushNotification(toUid, "habitEncouragement", fromName, fromUid, { habitId, habitName });
}

function fcmListenForeground(callback) {
  if (messaging) onMessage(messaging, callback);
}

window.FCM = {
  registerToken:     fcmRegisterToken,
  removeToken:       fcmRemoveToken,
  saveReminder:      fcmSaveReminder,
  disableReminder:   fcmDisableReminder,
  sendEncouragement: fcmSendEncouragement,
  listenForeground:  fcmListenForeground
};

// ── Habit Reminder Slots ─────────────────────────────────────────────────────

async function saveHabitReminderSlots(uid, habitId, habitName, { enabled, frequency, times, timezone, kind }) {
  try {
    const batch = writeBatch(db);
    for (let i = 0; i < 10; i++) {
      batch.delete(doc(db, "users", uid, "habitReminderSlots", `${habitId}_${i}`));
    }
    if (enabled && times && times.length) {
      const tz = timezone || "UTC";
      for (let i = 0; i < Math.min(times.length, 6); i++) {
        const time = times[i];
        if (!time) continue;
        const nextSendAt = calculateReminderNextSendAt({ time, frequency: frequency || "daily", timezone: tz });
        batch.set(doc(db, "users", uid, "habitReminderSlots", `${habitId}_${i}`), {
          uid,
          habitId,
          habitName,
          slotIndex: i,
          time,
          frequency: frequency || "daily",
          timezone: tz,
          enabled: true,
          ...(kind ? { kind } : {}),
          nextSendAt,
          lastSent: null,
          updatedAt: serverTimestamp()
        });
      }
    }
    await batch.commit();
    return true;
  } catch (e) {
    console.warn("saveHabitReminderSlots:", e);
    return false;
  }
}

async function clearHabitReminderSlots(uid, habitId) {
  try {
    const batch = writeBatch(db);
    for (let i = 0; i < 10; i++) {
      batch.delete(doc(db, "users", uid, "habitReminderSlots", `${habitId}_${i}`));
    }
    await batch.commit();
    return true;
  } catch (e) {
    console.warn("clearHabitReminderSlots:", e);
    return false;
  }
}

async function loadHabitReminderSlots(uid) {
  try {
    const snap = await getDocs(collection(db, "users", uid, "habitReminderSlots"));
    const result = {};
    snap.docs.forEach(d => {
      const data = d.data();
      if (!result[data.habitId]) {
        result[data.habitId] = { enabled: true, frequency: data.frequency || "daily", times: [] };
      }
      result[data.habitId].times[data.slotIndex] = data.time;
      result[data.habitId].frequency = data.frequency || "daily";
    });
    Object.keys(result).forEach(id => {
      result[id].times = result[id].times.filter(Boolean);
      if (!result[id].times.length) result[id].times = ["08:00"];
    });
    return result;
  } catch (e) {
    console.warn("loadHabitReminderSlots:", e);
    return {};
  }
}

window.HabitReminders = {
  save:  saveHabitReminderSlots,
  clear: clearHabitReminderSlots,
  load:  loadHabitReminderSlots
};

async function saveRhemaPosition(uid, pos) {
  try {
    await setDoc(doc(db, "users", uid), { rhemaLastPos: pos }, { merge: true });
  } catch (e) { console.warn("saveRhemaPosition:", e); }
}

window.LB = {
  getUserId,
  checkNameTaken,
  syncXP,
  syncStreak,
  syncAvatar,
  submitScholarScore,
  joinXPBoard,
  joinScholarBoard,
  joinConsistencyBoard,
  getBoard,
  listenBoard,
  deleteUserData,
  deleteEntriesForId,
  getUserRanks,
  saveRhemaPosition,
  isXpJoined: () => localStorage.getItem("lbXpJoined") === "true",
  isScholarJoined: () => localStorage.getItem("lbScholarJoined") === "true",
  isConsJoined: () => localStorage.getItem("lbConsJoined") === "true",
  refreshLeaderboardName
};

window.Auth = {
  createAccount,
  login,
  logout,
  deleteAccount,
  connectEmail,
  sendPasswordReset,
  getAuthEmailInfo,
  onAuthChange,
  getCurrentUser,
  loadUserData,
  syncUserData,
  checkUsernameTaken,
  checkDisplayNameTaken,
  listenUserDoc,
  listenRhemaMarks,
  saveRhemaMark,
  deleteRhemaMark,
  listenRhemaTrails,
  saveRhemaTrail,
  deleteRhemaTrail,
  uploadAvatarPhoto
};

// ── Calendar Events ───────────────────────────────────────────────────────────

function evtEventAtMs(date, time) {
  if (!date || !time) return null;
  const [y, m, d] = String(date).split("-").map(Number);
  const [h, mn] = String(time).split(":").map(Number);
  const ms = new Date(y, (m || 1) - 1, d || 1, h || 0, mn || 0).getTime();
  return Number.isFinite(ms) ? ms : null;
}

async function evtCreate(uid, displayName, { title, description, date, time, location, invitees, reminders, timezone }) {
  try {
    const participantUids = [uid, ...invitees.map(i => i.uid)];
    const ref = await addDoc(collection(db, "events"), {
      title, description: description || '', date, time,
      eventAtMs: evtEventAtMs(date, time),
      timezone: timezone || Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC',
      location: location || '',
      creatorUid: uid, creatorName: displayName,
      invitees,
      participantUids,
      reminders: reminders || ['1week', '3day', '1day', 'dayof'],
      sentReminders: {},
      googleCalIds: {},
      isActive: true,
      createdAt: serverTimestamp(), updatedAt: serverTimestamp()
    });
    return ref.id;
  } catch (e) { console.warn("evtCreate:", e); return null; }
}

async function evtUpdate(eventId, updates) {
  try {
    const next = { ...updates, updatedAt: serverTimestamp() };
    if (updates.date && updates.time) next.eventAtMs = evtEventAtMs(updates.date, updates.time);
    await updateDoc(doc(db, "events", eventId), next);
    return true;
  } catch (e) { console.warn("evtUpdate:", e); return false; }
}

async function evtDelete(eventId) {
  try {
    await updateDoc(doc(db, "events", eventId), { isActive: false, updatedAt: serverTimestamp() });
    return true;
  } catch (e) { console.warn("evtDelete:", e); return false; }
}

function evtListen(uid, callback) {
  const q = query(collection(db, "events"), where("participantUids", "array-contains", uid));
  return onSnapshot(q, snap => {
    const docs = snap.docs.map(d => ({ id: d.id, ...d.data() }));
    docs.sort((a, b) => (a.date || '') < (b.date || '') ? -1 : 1);
    callback(docs.filter(e => e.isActive !== false));
  }, err => console.warn("evtListen:", err));
}

async function evtRespond(eventId, uid, status) {
  try {
    const snap = await getDoc(doc(db, "events", eventId));
    if (!snap.exists()) return false;
    const data = snap.data();
    const invitees = (data.invitees || []).map(inv =>
      inv.uid === uid ? { ...inv, status } : inv
    );
    await updateDoc(doc(db, "events", eventId), { invitees, updatedAt: serverTimestamp() });
    return true;
  } catch (e) { console.warn("evtRespond:", e); return false; }
}

async function evtMarkReminderSent(eventId, reminderKey) {
  try {
    await updateDoc(doc(db, "events", eventId), {
      [`sentReminders.${reminderKey}`]: true,
      updatedAt: serverTimestamp()
    });
  } catch (e) { console.warn("evtMarkReminderSent:", e); }
}

async function evtStoreGCalId(eventId, uid, gcalEventId) {
  try {
    await updateDoc(doc(db, "events", eventId), {
      [`googleCalIds.${uid}`]: gcalEventId,
      updatedAt: serverTimestamp()
    });
  } catch (e) { console.warn("evtStoreGCalId:", e); }
}

async function evtGetById(eventId) {
  try {
    const snap = await getDoc(doc(db, "events", eventId));
    return snap.exists() ? { id: snap.id, ...snap.data() } : null;
  } catch (e) { console.warn("evtGetById:", e); return null; }
}

async function evtGCalStatus() {
  try {
    const fn = httpsCallable(functionsApp, "googleCalendarStatus");
    const res = await fn({});
    return { ok: true, linked: false, configured: false, ...(res.data || {}) };
  } catch (e) { console.warn("evtGCalStatus:", e); return { ok: false, linked: false, configured: false }; }
}

async function evtGCalConnect(code) {
  try {
    const fn = httpsCallable(functionsApp, "connectGoogleCalendar");
    const res = await fn({ code });
    return !!res.data?.linked;
  } catch (e) { console.warn("evtGCalConnect:", e); return false; }
}

async function evtGCalDisconnect() {
  try {
    const fn = httpsCallable(functionsApp, "disconnectGoogleCalendar");
    const res = await fn({});
    return res.data?.linked === false;
  } catch (e) { console.warn("evtGCalDisconnect:", e); return false; }
}

async function evtGCalSync(eventId) {
  try {
    const fn = httpsCallable(functionsApp, "syncGoogleCalendarEvent");
    const res = await fn({ eventId });
    return !!res.data?.synced;
  } catch (e) { console.warn("evtGCalSync:", e); return false; }
}

async function evtGCalDayEvents(date, timezone) {
  try {
    const fn = httpsCallable(functionsApp, "listGoogleCalendarDayEvents");
    const res = await fn({ date, timezone });
    return res.data || { linked: false, events: [] };
  } catch (e) { console.warn("evtGCalDayEvents:", e); return { linked: false, events: [] }; }
}

window.Events = {
  create:           evtCreate,
  update:           evtUpdate,
  delete:           evtDelete,
  listen:           evtListen,
  respond:          evtRespond,
  markReminderSent: evtMarkReminderSent,
  storeGCalId:      evtStoreGCalId,
  getById:          evtGetById,
  gcalStatus:       evtGCalStatus,
  gcalConnect:      evtGCalConnect,
  gcalDisconnect:   evtGCalDisconnect,
  gcalSync:         evtGCalSync,
  gcalDayEvents:    evtGCalDayEvents,
  sendNotification: fcmSendPushNotification
};

// Notify app.js when Firebase auth state is resolved
onAuthStateChanged(auth, user => {
  if (typeof window.__onAuthStateReady === "function") {
    window.__onAuthStateReady(user);
  } else {
    window.__pendingAuthUser = user;
    window.__pendingAuthResolved = true;
  }
});
